<?php
/**
 * State City List for BE - DE.
 *
 * City count: 97
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for BE - DE.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Adlershof', 'wp-ultimo'),
	__('Alt-Hohenschönhausen', 'wp-ultimo'),
	__('Alt-Treptow', 'wp-ultimo'),
	__('Altglienicke', 'wp-ultimo'),
	__('Baumschulenweg', 'wp-ultimo'),
	__('Berlin', 'wp-ultimo'),
	__('Berlin Köpenick', 'wp-ultimo'),
	__('Berlin Treptow', 'wp-ultimo'),
	__('Biesdorf', 'wp-ultimo'),
	__('Blankenburg', 'wp-ultimo'),
	__('Blankenfelde', 'wp-ultimo'),
	__('Bohnsdorf', 'wp-ultimo'),
	__('Britz', 'wp-ultimo'),
	__('Buch', 'wp-ultimo'),
	__('Buckow', 'wp-ultimo'),
	__('Charlottenburg', 'wp-ultimo'),
	__('Charlottenburg-Nord', 'wp-ultimo'),
	__('Dahlem', 'wp-ultimo'),
	__('Falkenberg', 'wp-ultimo'),
	__('Falkenhagener Feld', 'wp-ultimo'),
	__('Fennpfuhl', 'wp-ultimo'),
	__('Französisch Buchholz', 'wp-ultimo'),
	__('Friedenau', 'wp-ultimo'),
	__('Friedrichsfelde', 'wp-ultimo'),
	__('Friedrichshagen', 'wp-ultimo'),
	__('Friedrichshain', 'wp-ultimo'),
	__('Frohnau', 'wp-ultimo'),
	__('Gatow', 'wp-ultimo'),
	__('Gesundbrunnen', 'wp-ultimo'),
	__('Gropiusstadt', 'wp-ultimo'),
	__('Grunewald', 'wp-ultimo'),
	__('Grünau', 'wp-ultimo'),
	__('Hakenfelde', 'wp-ultimo'),
	__('Halensee', 'wp-ultimo'),
	__('Hansaviertel', 'wp-ultimo'),
	__('Haselhorst', 'wp-ultimo'),
	__('Heiligensee', 'wp-ultimo'),
	__('Heinersdorf', 'wp-ultimo'),
	__('Hellersdorf', 'wp-ultimo'),
	__('Hermsdorf', 'wp-ultimo'),
	__('Johannisthal', 'wp-ultimo'),
	__('Karlshorst', 'wp-ultimo'),
	__('Karow', 'wp-ultimo'),
	__('Kaulsdorf', 'wp-ultimo'),
	__('Kladow', 'wp-ultimo'),
	__('Konradshöhe', 'wp-ultimo'),
	__('Kreuzberg', 'wp-ultimo'),
	__('Köpenick', 'wp-ultimo'),
	__('Lankwitz', 'wp-ultimo'),
	__('Lichtenberg', 'wp-ultimo'),
	__('Lichtenrade', 'wp-ultimo'),
	__('Lichterfelde', 'wp-ultimo'),
	__('Lübars', 'wp-ultimo'),
	__('Mahlsdorf', 'wp-ultimo'),
	__('Mariendorf', 'wp-ultimo'),
	__('Marienfelde', 'wp-ultimo'),
	__('Marzahn', 'wp-ultimo'),
	__('Mitte', 'wp-ultimo'),
	__('Moabit', 'wp-ultimo'),
	__('Märkisches Viertel', 'wp-ultimo'),
	__('Müggelheim', 'wp-ultimo'),
	__('Neu-Hohenschönhausen', 'wp-ultimo'),
	__('Neukölln', 'wp-ultimo'),
	__('Niederschöneweide', 'wp-ultimo'),
	__('Niederschönhausen', 'wp-ultimo'),
	__('Nikolassee', 'wp-ultimo'),
	__('Oberschöneweide', 'wp-ultimo'),
	__('Pankow', 'wp-ultimo'),
	__('Plänterwald', 'wp-ultimo'),
	__('Prenzlauer Berg', 'wp-ultimo'),
	__('Rahnsdorf', 'wp-ultimo'),
	__('Reinickendorf', 'wp-ultimo'),
	__('Rosenthal', 'wp-ultimo'),
	__('Rudow', 'wp-ultimo'),
	__('Rummelsburg', 'wp-ultimo'),
	__('Schmargendorf', 'wp-ultimo'),
	__('Schmöckwitz', 'wp-ultimo'),
	__('Schöneberg', 'wp-ultimo'),
	__('Siemensstadt', 'wp-ultimo'),
	__('Spandau', 'wp-ultimo'),
	__('Staaken', 'wp-ultimo'),
	__('Stadtrandsiedlung Malchow', 'wp-ultimo'),
	__('Steglitz', 'wp-ultimo'),
	__('Tegel', 'wp-ultimo'),
	__('Tempelhof', 'wp-ultimo'),
	__('Tiergarten', 'wp-ultimo'),
	__('Waidmannslust', 'wp-ultimo'),
	__('Wannsee', 'wp-ultimo'),
	__('Wartenberg', 'wp-ultimo'),
	__('Wedding', 'wp-ultimo'),
	__('Weißensee', 'wp-ultimo'),
	__('Westend', 'wp-ultimo'),
	__('Wilhelmsruh', 'wp-ultimo'),
	__('Wilhelmstadt', 'wp-ultimo'),
	__('Wilmersdorf', 'wp-ultimo'),
	__('Wittenau', 'wp-ultimo'),
	__('Zehlendorf', 'wp-ultimo'),
);
