<?php
/**
 * State City List for HB - DE.
 *
 * City count: 4
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for HB - DE.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Bremen', 'wp-ultimo'),
	__('Bremerhaven', 'wp-ultimo'),
	__('Burglesum', 'wp-ultimo'),
	__('Vegesack', 'wp-ultimo'),
);
