<?php
/**
 * State City List for HH - DE.
 *
 * City count: 37
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for HH - DE.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Alsterdorf', 'wp-ultimo'),
	__('Altona', 'wp-ultimo'),
	__('Barmbek-Nord', 'wp-ultimo'),
	__('Bergedorf', 'wp-ultimo'),
	__('Bergstedt', 'wp-ultimo'),
	__('Borgfelde', 'wp-ultimo'),
	__('Duvenstedt', 'wp-ultimo'),
	__('Eidelstedt', 'wp-ultimo'),
	__('Eimsbüttel', 'wp-ultimo'),
	__('Farmsen-Berne', 'wp-ultimo'),
	__('Fuhlsbüttel', 'wp-ultimo'),
	__('Hamburg', 'wp-ultimo'),
	__('Hamburg-Altstadt', 'wp-ultimo'),
	__('Hamburg-Mitte', 'wp-ultimo'),
	__('Hamburg-Nord', 'wp-ultimo'),
	__('Hammerbrook', 'wp-ultimo'),
	__('Harburg', 'wp-ultimo'),
	__('Hummelsbüttel', 'wp-ultimo'),
	__('Kleiner Grasbrook', 'wp-ultimo'),
	__('Langenhorn', 'wp-ultimo'),
	__('Lemsahl-Mellingstedt', 'wp-ultimo'),
	__('Lurup', 'wp-ultimo'),
	__('Marienthal', 'wp-ultimo'),
	__('Neustadt', 'wp-ultimo'),
	__('Ohlsdorf', 'wp-ultimo'),
	__('Ottensen', 'wp-ultimo'),
	__('Poppenbüttel', 'wp-ultimo'),
	__('Rothenburgsort', 'wp-ultimo'),
	__('Sasel', 'wp-ultimo'),
	__('St. Georg', 'wp-ultimo'),
	__('St. Pauli', 'wp-ultimo'),
	__('Steilshoop', 'wp-ultimo'),
	__('Stellingen', 'wp-ultimo'),
	__('Wandsbek', 'wp-ultimo'),
	__('Wellingsbüttel', 'wp-ultimo'),
	__('Winterhude', 'wp-ultimo'),
	__('Wohldorf-Ohlstedt', 'wp-ultimo'),
);
