<?php
/**
 * State City List for SL - DE.
 *
 * City count: 60
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for SL - DE.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Beckingen', 'wp-ultimo'),
	__('Bexbach', 'wp-ultimo'),
	__('Blieskastel', 'wp-ultimo'),
	__('Bous', 'wp-ultimo'),
	__('Britten', 'wp-ultimo'),
	__('Dillingen', 'wp-ultimo'),
	__('Ensdorf', 'wp-ultimo'),
	__('Eppelborn', 'wp-ultimo'),
	__('Freisen', 'wp-ultimo'),
	__('Friedrichsthal', 'wp-ultimo'),
	__('Fürstenhausen', 'wp-ultimo'),
	__('Gersheim', 'wp-ultimo'),
	__('Großrosseln', 'wp-ultimo'),
	__('Hangard', 'wp-ultimo'),
	__('Heidstock', 'wp-ultimo'),
	__('Heusweiler', 'wp-ultimo'),
	__('Homburg', 'wp-ultimo'),
	__('Illingen', 'wp-ultimo'),
	__('Kirkel', 'wp-ultimo'),
	__('Kleinblittersdorf', 'wp-ultimo'),
	__('Lebach', 'wp-ultimo'),
	__('Losheim', 'wp-ultimo'),
	__('Ludweiler-Warndt', 'wp-ultimo'),
	__('Luisenthal', 'wp-ultimo'),
	__('Mainzweiler', 'wp-ultimo'),
	__('Marpingen', 'wp-ultimo'),
	__('Merchweiler', 'wp-ultimo'),
	__('Merzig', 'wp-ultimo'),
	__('Mettlach', 'wp-ultimo'),
	__('Nalbach', 'wp-ultimo'),
	__('Namborn', 'wp-ultimo'),
	__('Neunkirchen', 'wp-ultimo'),
	__('Nohfelden', 'wp-ultimo'),
	__('Nonnweiler', 'wp-ultimo'),
	__('Oberthal', 'wp-ultimo'),
	__('Orscholz', 'wp-ultimo'),
	__('Ottweiler', 'wp-ultimo'),
	__('Püttlingen', 'wp-ultimo'),
	__('Quierschied', 'wp-ultimo'),
	__('Riegelsberg', 'wp-ultimo'),
	__('Röchling-Höhe', 'wp-ultimo'),
	__('Saarbrücken', 'wp-ultimo'),
	__('Saarhölzbach', 'wp-ultimo'),
	__('Saarlouis', 'wp-ultimo'),
	__('Saarwellingen', 'wp-ultimo'),
	__('Sankt Ingbert', 'wp-ultimo'),
	__('Sankt Wendel', 'wp-ultimo'),
	__('Schiffweiler', 'wp-ultimo'),
	__('Schmelz', 'wp-ultimo'),
	__('Schwalbach', 'wp-ultimo'),
	__('Spiesen-Elversberg', 'wp-ultimo'),
	__('Sulzbach', 'wp-ultimo'),
	__('Tholey', 'wp-ultimo'),
	__('Völklingen', 'wp-ultimo'),
	__('Wadern', 'wp-ultimo'),
	__('Wadgassen', 'wp-ultimo'),
	__('Wallerfangen', 'wp-ultimo'),
	__('Weiskirchen', 'wp-ultimo'),
	__('Weiten', 'wp-ultimo'),
	__('Überherrn', 'wp-ultimo'),
);
