<?php
/**
 * State City List for AC - BR.
 *
 * City count: 22
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for AC - BR.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Acrelândia', 'wp-ultimo'),
	__('Assis Brasil', 'wp-ultimo'),
	__('Brasiléia', 'wp-ultimo'),
	__('Bujari', 'wp-ultimo'),
	__('Capixaba', 'wp-ultimo'),
	__('Cruzeiro do Sul', 'wp-ultimo'),
	__('Epitaciolândia', 'wp-ultimo'),
	__('Feijó', 'wp-ultimo'),
	__('Jordão', 'wp-ultimo'),
	__('Manoel Urbano', 'wp-ultimo'),
	__('Marechal Thaumaturgo', 'wp-ultimo'),
	__('Mâncio Lima', 'wp-ultimo'),
	__('Plácido de Castro', 'wp-ultimo'),
	__('Porto Acre', 'wp-ultimo'),
	__('Porto Walter', 'wp-ultimo'),
	__('Rio Branco', 'wp-ultimo'),
	__('Rodrigues Alves', 'wp-ultimo'),
	__('Santa Rosa do Purus', 'wp-ultimo'),
	__('Sena Madureira', 'wp-ultimo'),
	__('Senador Guiomard', 'wp-ultimo'),
	__('Tarauacá', 'wp-ultimo'),
	__('Xapuri', 'wp-ultimo'),
);
