<?php
/**
 * State City List for AM - BR.
 *
 * City count: 62
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for AM - BR.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Alvarães', 'wp-ultimo'),
	__('Amaturá', 'wp-ultimo'),
	__('Anamã', 'wp-ultimo'),
	__('Anori', 'wp-ultimo'),
	__('Apuí', 'wp-ultimo'),
	__('Atalaia do Norte', 'wp-ultimo'),
	__('Autazes', 'wp-ultimo'),
	__('Barcelos', 'wp-ultimo'),
	__('Barreirinha', 'wp-ultimo'),
	__('Benjamin Constant', 'wp-ultimo'),
	__('Beruri', 'wp-ultimo'),
	__('Boa Vista do Ramos', 'wp-ultimo'),
	__('Boca do Acre', 'wp-ultimo'),
	__('Borba', 'wp-ultimo'),
	__('Caapiranga', 'wp-ultimo'),
	__('Canutama', 'wp-ultimo'),
	__('Carauari', 'wp-ultimo'),
	__('Careiro', 'wp-ultimo'),
	__('Careiro da Várzea', 'wp-ultimo'),
	__('Coari', 'wp-ultimo'),
	__('Codajás', 'wp-ultimo'),
	__('Eirunepé', 'wp-ultimo'),
	__('Envira', 'wp-ultimo'),
	__('Fonte Boa', 'wp-ultimo'),
	__('Guajará', 'wp-ultimo'),
	__('Humaitá', 'wp-ultimo'),
	__('Ipixuna', 'wp-ultimo'),
	__('Iranduba', 'wp-ultimo'),
	__('Itacoatiara', 'wp-ultimo'),
	__('Itamarati', 'wp-ultimo'),
	__('Itapiranga', 'wp-ultimo'),
	__('Japurá', 'wp-ultimo'),
	__('Juruá', 'wp-ultimo'),
	__('Jutaí', 'wp-ultimo'),
	__('Lábrea', 'wp-ultimo'),
	__('Manacapuru', 'wp-ultimo'),
	__('Manaquiri', 'wp-ultimo'),
	__('Manaus', 'wp-ultimo'),
	__('Manicoré', 'wp-ultimo'),
	__('Maraã', 'wp-ultimo'),
	__('Maués', 'wp-ultimo'),
	__('Nhamundá', 'wp-ultimo'),
	__('Nova Olinda do Norte', 'wp-ultimo'),
	__('Novo Airão', 'wp-ultimo'),
	__('Novo Aripuanã', 'wp-ultimo'),
	__('Parintins', 'wp-ultimo'),
	__('Pauini', 'wp-ultimo'),
	__('Presidente Figueiredo', 'wp-ultimo'),
	__('Rio Preto da Eva', 'wp-ultimo'),
	__('Santa Isabel do Rio Negro', 'wp-ultimo'),
	__('Santo Antônio do Içá', 'wp-ultimo'),
	__('Silves', 'wp-ultimo'),
	__('São Gabriel da Cachoeira', 'wp-ultimo'),
	__('São Paulo de Olivença', 'wp-ultimo'),
	__('São Sebastião do Uatumã', 'wp-ultimo'),
	__('Tabatinga', 'wp-ultimo'),
	__('Tapauá', 'wp-ultimo'),
	__('Tefé', 'wp-ultimo'),
	__('Tonantins', 'wp-ultimo'),
	__('Uarini', 'wp-ultimo'),
	__('Urucará', 'wp-ultimo'),
	__('Urucurituba', 'wp-ultimo'),
);
