<?php
/**
 * State City List for AP - BR.
 *
 * City count: 16
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for AP - BR.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Amapá', 'wp-ultimo'),
	__('Calçoene', 'wp-ultimo'),
	__('Cutias', 'wp-ultimo'),
	__('Ferreira Gomes', 'wp-ultimo'),
	__('Itaubal', 'wp-ultimo'),
	__('Laranjal do Jari', 'wp-ultimo'),
	__('Macapá', 'wp-ultimo'),
	__('Mazagão', 'wp-ultimo'),
	__('Oiapoque', 'wp-ultimo'),
	__('Pedra Branca do Amapari', 'wp-ultimo'),
	__('Porto Grande', 'wp-ultimo'),
	__('Pracuúba', 'wp-ultimo'),
	__('Santana', 'wp-ultimo'),
	__('Serra do Navio', 'wp-ultimo'),
	__('Tartarugalzinho', 'wp-ultimo'),
	__('Vitória do Jari', 'wp-ultimo'),
);
