<?php
/**
 * State City List for ES - BR.
 *
 * City count: 80
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for ES - BR.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Afonso Cláudio', 'wp-ultimo'),
	__('Alegre', 'wp-ultimo'),
	__('Alfredo Chaves', 'wp-ultimo'),
	__('Alto Rio Novo', 'wp-ultimo'),
	__('Anchieta', 'wp-ultimo'),
	__('Apiacá', 'wp-ultimo'),
	__('Aracruz', 'wp-ultimo'),
	__('Atílio Vivacqua', 'wp-ultimo'),
	__('Baixo Guandu', 'wp-ultimo'),
	__('Barra de São Francisco', 'wp-ultimo'),
	__('Boa Esperança', 'wp-ultimo'),
	__('Bom Jesus do Norte', 'wp-ultimo'),
	__('Brejetuba', 'wp-ultimo'),
	__('Cachoeiro de Itapemirim', 'wp-ultimo'),
	__('Cariacica', 'wp-ultimo'),
	__('Castelo', 'wp-ultimo'),
	__('Colatina', 'wp-ultimo'),
	__('Conceição da Barra', 'wp-ultimo'),
	__('Conceição do Castelo', 'wp-ultimo'),
	__('Divino de São Lourenço', 'wp-ultimo'),
	__('Domingos Martins', 'wp-ultimo'),
	__('Dores do Rio Preto', 'wp-ultimo'),
	__('Ecoporanga', 'wp-ultimo'),
	__('Fundão', 'wp-ultimo'),
	__('Governador Lindenberg', 'wp-ultimo'),
	__('Guarapari', 'wp-ultimo'),
	__('Guaçuí', 'wp-ultimo'),
	__('Ibatiba', 'wp-ultimo'),
	__('Ibiraçu', 'wp-ultimo'),
	__('Ibitirama', 'wp-ultimo'),
	__('Iconha', 'wp-ultimo'),
	__('Irupi', 'wp-ultimo'),
	__('Itaguaçu', 'wp-ultimo'),
	__('Itapemirim', 'wp-ultimo'),
	__('Itarana', 'wp-ultimo'),
	__('Iúna', 'wp-ultimo'),
	__('Jaguaré', 'wp-ultimo'),
	__('Jerônimo Monteiro', 'wp-ultimo'),
	__('Jetibá', 'wp-ultimo'),
	__('João Neiva', 'wp-ultimo'),
	__('Laranja da Terra', 'wp-ultimo'),
	__('Linhares', 'wp-ultimo'),
	__('Mantenópolis', 'wp-ultimo'),
	__('Marataizes', 'wp-ultimo'),
	__('Marataízes', 'wp-ultimo'),
	__('Marechal Floriano', 'wp-ultimo'),
	__('Marilândia', 'wp-ultimo'),
	__('Mimoso do Sul', 'wp-ultimo'),
	__('Montanha', 'wp-ultimo'),
	__('Mucurici', 'wp-ultimo'),
	__('Muniz Freire', 'wp-ultimo'),
	__('Muqui', 'wp-ultimo'),
	__('Nova Venécia', 'wp-ultimo'),
	__('Pancas', 'wp-ultimo'),
	__('Pedro Canário', 'wp-ultimo'),
	__('Pinheiros', 'wp-ultimo'),
	__('Piúma', 'wp-ultimo'),
	__('Ponto Belo', 'wp-ultimo'),
	__('Presidente Kennedy', 'wp-ultimo'),
	__('Rio Bananal', 'wp-ultimo'),
	__('Rio Novo do Sul', 'wp-ultimo'),
	__('Santa Leopoldina', 'wp-ultimo'),
	__('Santa Maria de Jetibá', 'wp-ultimo'),
	__('Santa Teresa', 'wp-ultimo'),
	__('Serra', 'wp-ultimo'),
	__('Sooretama', 'wp-ultimo'),
	__('São Domingos do Norte', 'wp-ultimo'),
	__('São Gabriel da Palha', 'wp-ultimo'),
	__('São José do Calçado', 'wp-ultimo'),
	__('São Mateus', 'wp-ultimo'),
	__('São Roque do Canaã', 'wp-ultimo'),
	__('Vargem Alta', 'wp-ultimo'),
	__('Venda Nova do Imigrante', 'wp-ultimo'),
	__('Viana', 'wp-ultimo'),
	__('Vila Pavão', 'wp-ultimo'),
	__('Vila Valério', 'wp-ultimo'),
	__('Vila Velha', 'wp-ultimo'),
	__('Vitória', 'wp-ultimo'),
	__('Água Doce do Norte', 'wp-ultimo'),
	__('Águia Branca', 'wp-ultimo'),
);
