<?php
/**
 * State City List for MS - BR.
 *
 * City count: 82
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for MS - BR.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Alcinópolis', 'wp-ultimo'),
	__('Amambai', 'wp-ultimo'),
	__('Anastácio', 'wp-ultimo'),
	__('Anaurilândia', 'wp-ultimo'),
	__('Angélica', 'wp-ultimo'),
	__('Antônio João', 'wp-ultimo'),
	__('Aparecida do Taboado', 'wp-ultimo'),
	__('Aquidauana', 'wp-ultimo'),
	__('Aral Moreira', 'wp-ultimo'),
	__('Bandeirantes', 'wp-ultimo'),
	__('Bataguassu', 'wp-ultimo'),
	__('Bataiporã', 'wp-ultimo'),
	__('Batayporã', 'wp-ultimo'),
	__('Bela Vista', 'wp-ultimo'),
	__('Bodoquena', 'wp-ultimo'),
	__('Bonito', 'wp-ultimo'),
	__('Brasilândia', 'wp-ultimo'),
	__('Caarapó', 'wp-ultimo'),
	__('Camapuã', 'wp-ultimo'),
	__('Campo Grande', 'wp-ultimo'),
	__('Campo Verde', 'wp-ultimo'),
	__('Caracol', 'wp-ultimo'),
	__('Cassilândia', 'wp-ultimo'),
	__('Chapadão do Sul', 'wp-ultimo'),
	__('Corguinho', 'wp-ultimo'),
	__('Coronel Sapucaia', 'wp-ultimo'),
	__('Corumbá', 'wp-ultimo'),
	__('Costa Rica', 'wp-ultimo'),
	__('Coxim', 'wp-ultimo'),
	__('Deodápolis', 'wp-ultimo'),
	__('Dois Irmãos do Buriti', 'wp-ultimo'),
	__('Douradina', 'wp-ultimo'),
	__('Dourados', 'wp-ultimo'),
	__('Eldorado', 'wp-ultimo'),
	__('Figueirão', 'wp-ultimo'),
	__('Fátima do Sul', 'wp-ultimo'),
	__('Glória de Dourados', 'wp-ultimo'),
	__('Guia Lopes da Laguna', 'wp-ultimo'),
	__('Iguatemi', 'wp-ultimo'),
	__('Inocência', 'wp-ultimo'),
	__('Itaporã', 'wp-ultimo'),
	__('Itaquiraí', 'wp-ultimo'),
	__('Ivinhema', 'wp-ultimo'),
	__('Japorã', 'wp-ultimo'),
	__('Jaraguari', 'wp-ultimo'),
	__('Jardim', 'wp-ultimo'),
	__('Jateí', 'wp-ultimo'),
	__('Juti', 'wp-ultimo'),
	__('Ladário', 'wp-ultimo'),
	__('Laguna Carapã', 'wp-ultimo'),
	__('Maracaju', 'wp-ultimo'),
	__('Miranda', 'wp-ultimo'),
	__('Mundo Novo', 'wp-ultimo'),
	__('Naviraí', 'wp-ultimo'),
	__('Nioaque', 'wp-ultimo'),
	__('Nova Alvorada do Sul', 'wp-ultimo'),
	__('Nova Andradina', 'wp-ultimo'),
	__('Novo Horizonte do Sul', 'wp-ultimo'),
	__('Paranaíba', 'wp-ultimo'),
	__('Paranhos', 'wp-ultimo'),
	__('Paraíso das Águas', 'wp-ultimo'),
	__('Pedro Gomes', 'wp-ultimo'),
	__('Ponta Porã', 'wp-ultimo'),
	__('Porto Murtinho', 'wp-ultimo'),
	__('Pôrto Barra do Ivinheima', 'wp-ultimo'),
	__('Ribas do Rio Pardo', 'wp-ultimo'),
	__('Rio Brilhante', 'wp-ultimo'),
	__('Rio Negro', 'wp-ultimo'),
	__('Rio Verde de Mato Grosso', 'wp-ultimo'),
	__('Rochedo', 'wp-ultimo'),
	__('Santa Rita do Pardo', 'wp-ultimo'),
	__('Selvíria', 'wp-ultimo'),
	__('Sete Quedas', 'wp-ultimo'),
	__('Sidrolândia', 'wp-ultimo'),
	__('Sonora', 'wp-ultimo'),
	__('São Gabriel do Oeste', 'wp-ultimo'),
	__('Tacuru', 'wp-ultimo'),
	__('Taquarussu', 'wp-ultimo'),
	__('Terenos', 'wp-ultimo'),
	__('Três Lagoas', 'wp-ultimo'),
	__('Vicentina', 'wp-ultimo'),
	__('Água Clara', 'wp-ultimo'),
);
