<?php
/**
 * State City List for RO - BR.
 *
 * City count: 56
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for RO - BR.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__("Alta Floresta d'Oeste", 'wp-ultimo'),
	__('Alto Alegre dos Parecis', 'wp-ultimo'),
	__('Alto Paraíso', 'wp-ultimo'),
	__("Alvorada d'Oeste", 'wp-ultimo'),
	__('Ariquemes', 'wp-ultimo'),
	__('Buritis', 'wp-ultimo'),
	__('Cabixi', 'wp-ultimo'),
	__('Cacaulândia', 'wp-ultimo'),
	__('Cacoal', 'wp-ultimo'),
	__('Campo Novo de Rondônia', 'wp-ultimo'),
	__('Candeias do Jamari', 'wp-ultimo'),
	__('Castanheiras', 'wp-ultimo'),
	__('Cerejeiras', 'wp-ultimo'),
	__('Chupinguaia', 'wp-ultimo'),
	__('Colorado do Oeste', 'wp-ultimo'),
	__('Corumbiara', 'wp-ultimo'),
	__('Costa Marques', 'wp-ultimo'),
	__('Cujubim', 'wp-ultimo'),
	__("Espigão d'Oeste", 'wp-ultimo'),
	__('Extrema', 'wp-ultimo'),
	__('Governador Jorge Teixeira', 'wp-ultimo'),
	__('Guajará Mirim', 'wp-ultimo'),
	__('Guajará-Mirim', 'wp-ultimo'),
	__('Itapuã do Oeste', 'wp-ultimo'),
	__('Jaru', 'wp-ultimo'),
	__('Ji Paraná', 'wp-ultimo'),
	__('Ji-Paraná', 'wp-ultimo'),
	__("Machadinho d'Oeste", 'wp-ultimo'),
	__('Ministro Andreazza', 'wp-ultimo'),
	__('Mirante da Serra', 'wp-ultimo'),
	__('Monte Negro', 'wp-ultimo'),
	__("Nova Brasilândia d'Oeste", 'wp-ultimo'),
	__('Nova Mamoré', 'wp-ultimo'),
	__('Nova União', 'wp-ultimo'),
	__('Novo Horizonte do Oeste', 'wp-ultimo'),
	__('Ouro Preto do Oeste', 'wp-ultimo'),
	__('Parecis', 'wp-ultimo'),
	__('Pimenta Bueno', 'wp-ultimo'),
	__('Pimenteiras do Oeste', 'wp-ultimo'),
	__('Porto Velho', 'wp-ultimo'),
	__('Presidente Médici', 'wp-ultimo'),
	__('Primavera de Rondônia', 'wp-ultimo'),
	__('Pôsto Fiscal Rolim de Moura', 'wp-ultimo'),
	__('Rio Crespo', 'wp-ultimo'),
	__('Rolim de Moura', 'wp-ultimo'),
	__("Santa Luzia d'Oeste", 'wp-ultimo'),
	__('Seringueiras', 'wp-ultimo'),
	__("São Felipe d'Oeste", 'wp-ultimo'),
	__('São Francisco do Guaporé', 'wp-ultimo'),
	__('São Miguel do Guaporé', 'wp-ultimo'),
	__('Teixeirópolis', 'wp-ultimo'),
	__('Theobroma', 'wp-ultimo'),
	__('Urupá', 'wp-ultimo'),
	__('Vale do Anari', 'wp-ultimo'),
	__('Vale do Paraíso', 'wp-ultimo'),
	__('Vilhena', 'wp-ultimo'),
);
