<?php
/**
 * State City List for RR - BR.
 *
 * City count: 14
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for RR - BR.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Amajari', 'wp-ultimo'),
	__('Boa Vista', 'wp-ultimo'),
	__('Bonfim', 'wp-ultimo'),
	__('Cantá', 'wp-ultimo'),
	__('Caracaraí', 'wp-ultimo'),
	__('Caroebe', 'wp-ultimo'),
	__('Iracema', 'wp-ultimo'),
	__('Mucajaí', 'wp-ultimo'),
	__('Normandia', 'wp-ultimo'),
	__('Pacaraima', 'wp-ultimo'),
	__('Rorainópolis', 'wp-ultimo'),
	__('São João da Baliza', 'wp-ultimo'),
	__('São Luís', 'wp-ultimo'),
	__('Uiramutã', 'wp-ultimo'),
);
