<?php
/**
 * State City List for SE - BR.
 *
 * City count: 75
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for SE - BR.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Amparo de São Francisco', 'wp-ultimo'),
	__('Aquidabã', 'wp-ultimo'),
	__('Aracaju', 'wp-ultimo'),
	__('Arauá', 'wp-ultimo'),
	__('Areia Branca', 'wp-ultimo'),
	__('Barra dos Coqueiros', 'wp-ultimo'),
	__('Boquim', 'wp-ultimo'),
	__('Brejo Grande', 'wp-ultimo'),
	__('Campo do Brito', 'wp-ultimo'),
	__('Canhoba', 'wp-ultimo'),
	__('Canindé de São Francisco', 'wp-ultimo'),
	__('Capela', 'wp-ultimo'),
	__('Carira', 'wp-ultimo'),
	__('Carmópolis', 'wp-ultimo'),
	__('Cedro de São João', 'wp-ultimo'),
	__('Cristinápolis', 'wp-ultimo'),
	__('Cumbe', 'wp-ultimo'),
	__('Divina Pastora', 'wp-ultimo'),
	__('Estância', 'wp-ultimo'),
	__('Feira Nova', 'wp-ultimo'),
	__('Frei Paulo', 'wp-ultimo'),
	__('Gararu', 'wp-ultimo'),
	__('General Maynard', 'wp-ultimo'),
	__('Gracho Cardoso', 'wp-ultimo'),
	__('Ilha das Flores', 'wp-ultimo'),
	__('Indiaroba', 'wp-ultimo'),
	__('Itabaiana', 'wp-ultimo'),
	__('Itabaianinha', 'wp-ultimo'),
	__('Itabi', 'wp-ultimo'),
	__("Itaporanga d'Ajuda", 'wp-ultimo'),
	__('Japaratuba', 'wp-ultimo'),
	__('Japoatã', 'wp-ultimo'),
	__('Lagarto', 'wp-ultimo'),
	__('Laranjeiras', 'wp-ultimo'),
	__('Macambira', 'wp-ultimo'),
	__('Malhada dos Bois', 'wp-ultimo'),
	__('Malhador', 'wp-ultimo'),
	__('Maruim', 'wp-ultimo'),
	__('Moita Bonita', 'wp-ultimo'),
	__('Monte Alegre de Sergipe', 'wp-ultimo'),
	__('Muribeca', 'wp-ultimo'),
	__('Neópolis', 'wp-ultimo'),
	__('Nossa Senhora Aparecida', 'wp-ultimo'),
	__('Nossa Senhora da Glória', 'wp-ultimo'),
	__('Nossa Senhora das Dores', 'wp-ultimo'),
	__('Nossa Senhora de Lourdes', 'wp-ultimo'),
	__('Nossa Senhora do Socorro', 'wp-ultimo'),
	__('Pacatuba', 'wp-ultimo'),
	__('Pedra Mole', 'wp-ultimo'),
	__('Pedrinhas', 'wp-ultimo'),
	__('Pinhão', 'wp-ultimo'),
	__('Pirambu', 'wp-ultimo'),
	__('Porto da Folha', 'wp-ultimo'),
	__('Poço Redondo', 'wp-ultimo'),
	__('Poço Verde', 'wp-ultimo'),
	__('Propriá', 'wp-ultimo'),
	__('Riachuelo', 'wp-ultimo'),
	__('Riachão do Dantas', 'wp-ultimo'),
	__('Ribeirópolis', 'wp-ultimo'),
	__('Rosário do Catete', 'wp-ultimo'),
	__('Salgado', 'wp-ultimo'),
	__('Santa Luzia do Itanhy', 'wp-ultimo'),
	__('Santa Rosa de Lima', 'wp-ultimo'),
	__('Santana do São Francisco', 'wp-ultimo'),
	__('Santo Amaro das Brotas', 'wp-ultimo'),
	__('Simão Dias', 'wp-ultimo'),
	__('Siriri', 'wp-ultimo'),
	__('São Cristóvão', 'wp-ultimo'),
	__('São Domingos', 'wp-ultimo'),
	__('São Francisco', 'wp-ultimo'),
	__('São Miguel do Aleixo', 'wp-ultimo'),
	__('Telha', 'wp-ultimo'),
	__('Tobias Barreto', 'wp-ultimo'),
	__('Tomar do Geru', 'wp-ultimo'),
	__('Umbaúba', 'wp-ultimo'),
);
