<?php
/**
 * State City List for MC - ES.
 *
 * City count: 57
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for MC - ES.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Abanilla', 'wp-ultimo'),
	__('Abarán', 'wp-ultimo'),
	__('Albudeite', 'wp-ultimo'),
	__('Alcantarilla', 'wp-ultimo'),
	__('Aledo', 'wp-ultimo'),
	__('Alguazas', 'wp-ultimo'),
	__('Alhama de Murcia', 'wp-ultimo'),
	__('Archena', 'wp-ultimo'),
	__('Atamaría', 'wp-ultimo'),
	__('Barrio de la Concepción', 'wp-ultimo'),
	__('Beniel', 'wp-ultimo'),
	__('Blanca', 'wp-ultimo'),
	__('Bullas', 'wp-ultimo'),
	__('Calasparra', 'wp-ultimo'),
	__('Campos del Río', 'wp-ultimo'),
	__('Caravaca', 'wp-ultimo'),
	__('Cartagena', 'wp-ultimo'),
	__('Cehegín', 'wp-ultimo'),
	__('Ceuti', 'wp-ultimo'),
	__('Cieza', 'wp-ultimo'),
	__('Cobatillas', 'wp-ultimo'),
	__('El Plan', 'wp-ultimo'),
	__('Esparragal', 'wp-ultimo'),
	__('Fortuna', 'wp-ultimo'),
	__('Fuente-Álamo de Murcia', 'wp-ultimo'),
	__('Jumilla', 'wp-ultimo'),
	__('La Manga del Mar Menor', 'wp-ultimo'),
	__('La Torrecilla', 'wp-ultimo'),
	__('La Unión', 'wp-ultimo'),
	__('Las Torres de Cotillas', 'wp-ultimo'),
	__('Librilla', 'wp-ultimo'),
	__('Lo Pagán', 'wp-ultimo'),
	__('Lorca', 'wp-ultimo'),
	__('Lorquí', 'wp-ultimo'),
	__('Los Alcázares', 'wp-ultimo'),
	__('Los Gabatos', 'wp-ultimo'),
	__('Los Martínez', 'wp-ultimo'),
	__('Mazarrón', 'wp-ultimo'),
	__('Molina de Segura', 'wp-ultimo'),
	__('Moratalla', 'wp-ultimo'),
	__('Mula', 'wp-ultimo'),
	__('Murcia', 'wp-ultimo'),
	__('Ojós', 'wp-ultimo'),
	__('Pliego', 'wp-ultimo'),
	__('Puerto Lumbreras', 'wp-ultimo'),
	__('Ricote', 'wp-ultimo'),
	__('San Javier', 'wp-ultimo'),
	__('San Pedro del Pinatar', 'wp-ultimo'),
	__('Sangonera la Verde', 'wp-ultimo'),
	__('Santa Cruz', 'wp-ultimo'),
	__('Santiago de la Ribera', 'wp-ultimo'),
	__('Santomera', 'wp-ultimo'),
	__('Torre-Pacheco', 'wp-ultimo'),
	__('Totana', 'wp-ultimo'),
	__('Ulea', 'wp-ultimo'),
	__('Yecla', 'wp-ultimo'),
	__('Águilas', 'wp-ultimo'),
);
