<?php
/**
 * State City List for PM - ES.
 *
 * City count: 87
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for PM - ES.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Alaior', 'wp-ultimo'),
	__('Alaró', 'wp-ultimo'),
	__('Alcúdia', 'wp-ultimo'),
	__('Algaida', 'wp-ultimo'),
	__('Andratx', 'wp-ultimo'),
	__('Ariany', 'wp-ultimo'),
	__('Artà', 'wp-ultimo'),
	__('Banyalbufar', 'wp-ultimo'),
	__('Binissalem', 'wp-ultimo'),
	__('Bunyola', 'wp-ultimo'),
	__('Búger', 'wp-ultimo'),
	__('Cala Rajada', 'wp-ultimo'),
	__("Cala d'Or", 'wp-ultimo'),
	__('Calonge', 'wp-ultimo'),
	__('Calvià', 'wp-ultimo'),
	__('Camp de Mar', 'wp-ultimo'),
	__('Campanet', 'wp-ultimo'),
	__('Campos', 'wp-ultimo'),
	__('Can Pastilla', 'wp-ultimo'),
	__('Can Picafort', 'wp-ultimo'),
	__('Capdepera', 'wp-ultimo'),
	__('Ciutadella', 'wp-ultimo'),
	__("Coll d'en Rabassa", 'wp-ultimo'),
	__('Colònia de Sant Jordi', 'wp-ultimo'),
	__('Consell', 'wp-ultimo'),
	__('Costitx', 'wp-ultimo'),
	__('Deià', 'wp-ultimo'),
	__('El Toro', 'wp-ultimo'),
	__('Es Castell', 'wp-ultimo'),
	__('Es Molinar', 'wp-ultimo'),
	__('Escorca', 'wp-ultimo'),
	__('Esporles', 'wp-ultimo'),
	__('Estellencs', 'wp-ultimo'),
	__('Felanitx', 'wp-ultimo'),
	__('Ferreries', 'wp-ultimo'),
	__('Fornalutx', 'wp-ultimo'),
	__('Ibiza', 'wp-ultimo'),
	__('Illes Balears', 'wp-ultimo'),
	__('Inca', 'wp-ultimo'),
	__('Lloret de Vistalegre', 'wp-ultimo'),
	__('Lloseta', 'wp-ultimo'),
	__('Llubí', 'wp-ultimo'),
	__('Llucmajor', 'wp-ultimo'),
	__('Magaluf', 'wp-ultimo'),
	__('Manacor', 'wp-ultimo'),
	__('Mancor de la Vall', 'wp-ultimo'),
	__('Maria de la Salut', 'wp-ultimo'),
	__('Marratxí', 'wp-ultimo'),
	__('Maó', 'wp-ultimo'),
	__('Mercadal', 'wp-ultimo'),
	__('Montuïri', 'wp-ultimo'),
	__('Muro', 'wp-ultimo'),
	__('Palma', 'wp-ultimo'),
	__('Palmanova', 'wp-ultimo'),
	__('Peguera', 'wp-ultimo'),
	__('Petra', 'wp-ultimo'),
	__('Pollença', 'wp-ultimo'),
	__('Porreres', 'wp-ultimo'),
	__("Port d'Alcúdia", 'wp-ultimo'),
	__('Port de Pollença', 'wp-ultimo'),
	__('Port de Sóller', 'wp-ultimo'),
	__('Porto Cristo', 'wp-ultimo'),
	__('Portocolom', 'wp-ultimo'),
	__('Puigpunyent', 'wp-ultimo'),
	__('Sant Antoni de Portmany', 'wp-ultimo'),
	__('Sant Francesc de Formentera', 'wp-ultimo'),
	__('Sant Joan', 'wp-ultimo'),
	__('Sant Joan de Labritja', 'wp-ultimo'),
	__('Sant Josep de sa Talaia', 'wp-ultimo'),
	__('Sant Llorenç des Cardassar', 'wp-ultimo'),
	__('Sant Lluís', 'wp-ultimo'),
	__('Santa Eugènia', 'wp-ultimo'),
	__('Santa Eulària des Riu', 'wp-ultimo'),
	__('Santa Margalida', 'wp-ultimo'),
	__('Santa Ponsa', 'wp-ultimo'),
	__('Santanyí', 'wp-ultimo'),
	__('Selva', 'wp-ultimo'),
	__('Sencelles', 'wp-ultimo'),
	__('Ses Salines', 'wp-ultimo'),
	__('Sineu', 'wp-ultimo'),
	__('Son Ferrer', 'wp-ultimo'),
	__('Son Servera', 'wp-ultimo'),
	__('Sóller', 'wp-ultimo'),
	__('Valldemossa', 'wp-ultimo'),
	__('Vilafranca de Bonany', 'wp-ultimo'),
	__("s'Arenal", 'wp-ultimo'),
	__('sa Pobla', 'wp-ultimo'),
);
