<?php
/**
 * State City List for S - ES.
 *
 * City count: 58
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for S - ES.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Ampuero', 'wp-ultimo'),
	__('Arenas de Iguña', 'wp-ultimo'),
	__('Argoños', 'wp-ultimo'),
	__('Arnuero', 'wp-ultimo'),
	__('Arredondo', 'wp-ultimo'),
	__('Bareyo', 'wp-ultimo'),
	__('Bárcena de Cicero', 'wp-ultimo'),
	__('Bárcena de Pie de Concha', 'wp-ultimo'),
	__('Cabezón de Liébana', 'wp-ultimo'),
	__('Cabezón de la Sal', 'wp-ultimo'),
	__('Camargo', 'wp-ultimo'),
	__('Cartes', 'wp-ultimo'),
	__('Castro-Urdiales', 'wp-ultimo'),
	__('Colindres', 'wp-ultimo'),
	__('Comillas', 'wp-ultimo'),
	__('El Astillero', 'wp-ultimo'),
	__('Escalante', 'wp-ultimo'),
	__('Hazas de Cesto', 'wp-ultimo'),
	__('Laredo', 'wp-ultimo'),
	__('Limpias', 'wp-ultimo'),
	__('Los Corrales de Buelna', 'wp-ultimo'),
	__('Luzmela', 'wp-ultimo'),
	__('Mataporquera', 'wp-ultimo'),
	__('Miengo', 'wp-ultimo'),
	__('Molledo', 'wp-ultimo'),
	__('Noja', 'wp-ultimo'),
	__('Penagos', 'wp-ultimo'),
	__('Pesquera', 'wp-ultimo'),
	__('Polanco', 'wp-ultimo'),
	__('Potes', 'wp-ultimo'),
	__('Provincia de Cantabria', 'wp-ultimo'),
	__('Puente Viesgo', 'wp-ultimo'),
	__('Ramales de la Victoria', 'wp-ultimo'),
	__('Rasines', 'wp-ultimo'),
	__('Reinosa', 'wp-ultimo'),
	__('Reocín', 'wp-ultimo'),
	__('Ruente', 'wp-ultimo'),
	__('San Martín de Elines', 'wp-ultimo'),
	__('San Miguel de Aguayo', 'wp-ultimo'),
	__('San Miguel de Meruelo', 'wp-ultimo'),
	__('San Pedro del Romeral', 'wp-ultimo'),
	__('San Vicente de la Barquera', 'wp-ultimo'),
	__('Santa Cruz de Bezana', 'wp-ultimo'),
	__('Santa María de Cayón', 'wp-ultimo'),
	__('Santander', 'wp-ultimo'),
	__('Santillana', 'wp-ultimo'),
	__('Santiurde de Reinosa', 'wp-ultimo'),
	__('Santiurde de Toranzo', 'wp-ultimo'),
	__('Santoña', 'wp-ultimo'),
	__('Saro', 'wp-ultimo'),
	__('Selaya', 'wp-ultimo'),
	__('Solórzano', 'wp-ultimo'),
	__('Suances', 'wp-ultimo'),
	__('Torrelavega', 'wp-ultimo'),
	__('Vega de Pas', 'wp-ultimo'),
	__('Villacarriedo', 'wp-ultimo'),
	__('Villaescusa', 'wp-ultimo'),
	__('Villafufre', 'wp-ultimo'),
);
