<?php
/**
 * State City List for FS - ZA.
 *
 * City count: 41
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for FS - ZA.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Allanridge', 'wp-ultimo'),
	__('Bethlehem', 'wp-ultimo'),
	__('Bloemfontein', 'wp-ultimo'),
	__('Bothaville', 'wp-ultimo'),
	__('Botshabelo', 'wp-ultimo'),
	__('Brandfort', 'wp-ultimo'),
	__('Clocolan', 'wp-ultimo'),
	__('Deneysville', 'wp-ultimo'),
	__('Fezile Dabi District Municipality', 'wp-ultimo'),
	__('Frankfort', 'wp-ultimo'),
	__('Harrismith', 'wp-ultimo'),
	__('Heilbron', 'wp-ultimo'),
	__('Hennenman', 'wp-ultimo'),
	__('Hoopstad', 'wp-ultimo'),
	__('Koppies', 'wp-ultimo'),
	__('Kroonstad', 'wp-ultimo'),
	__('Kutloanong', 'wp-ultimo'),
	__('Ladybrand', 'wp-ultimo'),
	__('Lejweleputswa District Municipality', 'wp-ultimo'),
	__('Lindley', 'wp-ultimo'),
	__('Mangaung Metropolitan Municipality', 'wp-ultimo'),
	__('Marquard', 'wp-ultimo'),
	__('Parys', 'wp-ultimo'),
	__('Phuthaditjhaba', 'wp-ultimo'),
	__('Reitz', 'wp-ultimo'),
	__('Sasolburg', 'wp-ultimo'),
	__('Senekal', 'wp-ultimo'),
	__('Thaba Nchu', 'wp-ultimo'),
	__('Thabo Mofutsanyana District Municipality', 'wp-ultimo'),
	__('Theunissen', 'wp-ultimo'),
	__('Ventersburg', 'wp-ultimo'),
	__('Viljoenskroon', 'wp-ultimo'),
	__('Villiers', 'wp-ultimo'),
	__('Virginia', 'wp-ultimo'),
	__('Vrede', 'wp-ultimo'),
	__('Vredefort', 'wp-ultimo'),
	__('Welkom', 'wp-ultimo'),
	__('Wesselsbron', 'wp-ultimo'),
	__('Winburg', 'wp-ultimo'),
	__('Xhariep District Municipality', 'wp-ultimo'),
	__('Zastron', 'wp-ultimo'),
);
