<?php
/**
 * State City List for GP - ZA.
 *
 * City count: 39
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for GP - ZA.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Alberton', 'wp-ultimo'),
	__('Benoni', 'wp-ultimo'),
	__('Boksburg', 'wp-ultimo'),
	__('Brakpan', 'wp-ultimo'),
	__('Bronkhorstspruit', 'wp-ultimo'),
	__('Carletonville', 'wp-ultimo'),
	__('Centurion', 'wp-ultimo'),
	__('City of Johannesburg Metropolitan Municipality', 'wp-ultimo'),
	__('City of Tshwane Metropolitan Municipality', 'wp-ultimo'),
	__('Cullinan', 'wp-ultimo'),
	__('Diepsloot', 'wp-ultimo'),
	__('Eastleigh', 'wp-ultimo'),
	__('Eden Glen', 'wp-ultimo'),
	__('Eden Glen Ext 60', 'wp-ultimo'),
	__('Edenvale', 'wp-ultimo'),
	__('Ekangala', 'wp-ultimo'),
	__('Ekurhuleni Metropolitan Municipality', 'wp-ultimo'),
	__('Heidelberg', 'wp-ultimo'),
	__('Johannesburg', 'wp-ultimo'),
	__('Krugersdorp', 'wp-ultimo'),
	__('Mabopane', 'wp-ultimo'),
	__('Midrand', 'wp-ultimo'),
	__('Midstream', 'wp-ultimo'),
	__('Modderfontein', 'wp-ultimo'),
	__('Muldersdriseloop', 'wp-ultimo'),
	__('Nigel', 'wp-ultimo'),
	__('Orange Farm', 'wp-ultimo'),
	__('Pretoria', 'wp-ultimo'),
	__('Randburg', 'wp-ultimo'),
	__('Randfontein', 'wp-ultimo'),
	__('Roodepoort', 'wp-ultimo'),
	__('Sedibeng District Municipality', 'wp-ultimo'),
	__('Soweto', 'wp-ultimo'),
	__('Springs', 'wp-ultimo'),
	__('Tembisa', 'wp-ultimo'),
	__('Vanderbijlpark', 'wp-ultimo'),
	__('Vereeniging', 'wp-ultimo'),
	__('West Rand District Municipality', 'wp-ultimo'),
	__('Westonaria', 'wp-ultimo'),
);
