<?php
/**
 * State City List for KZN - ZA.
 *
 * City count: 43
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for KZN - ZA.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Amajuba District Municipality', 'wp-ultimo'),
	__('Ballito', 'wp-ultimo'),
	__('Berea', 'wp-ultimo'),
	__('Dundee', 'wp-ultimo'),
	__('Durban', 'wp-ultimo'),
	__('Ekuvukeni', 'wp-ultimo'),
	__('Empangeni', 'wp-ultimo'),
	__('Eshowe', 'wp-ultimo'),
	__('Glencoe', 'wp-ultimo'),
	__('Greytown', 'wp-ultimo'),
	__('Hluhluwe', 'wp-ultimo'),
	__('Howick', 'wp-ultimo'),
	__('Kokstad', 'wp-ultimo'),
	__('KwaDukuza', 'wp-ultimo'),
	__('Margate', 'wp-ultimo'),
	__('Mondlo', 'wp-ultimo'),
	__('Mooirivier', 'wp-ultimo'),
	__('Mpophomeni', 'wp-ultimo'),
	__('Mpumalanga', 'wp-ultimo'),
	__('Mtubatuba', 'wp-ultimo'),
	__('Ndwedwe', 'wp-ultimo'),
	__('Newcastle', 'wp-ultimo'),
	__('Pietermaritzburg', 'wp-ultimo'),
	__('Port Shepstone', 'wp-ultimo'),
	__('Richards Bay', 'wp-ultimo'),
	__('Richmond', 'wp-ultimo'),
	__('Scottburgh', 'wp-ultimo'),
	__('Sisonke District Municipality', 'wp-ultimo'),
	__('Sundumbili', 'wp-ultimo'),
	__('Ugu District Municipality', 'wp-ultimo'),
	__('Ulundi', 'wp-ultimo'),
	__('Utrecht', 'wp-ultimo'),
	__('Vryheid', 'wp-ultimo'),
	__('Zululand District Municipality', 'wp-ultimo'),
	__('eMkhomazi', 'wp-ultimo'),
	__('eSikhaleni', 'wp-ultimo'),
	__('eThekwini Metropolitan Municipality', 'wp-ultimo'),
	__('iLembe District Municipality', 'wp-ultimo'),
	__('uMgungundlovu District Municipality', 'wp-ultimo'),
	__('uMkhanyakude District Municipality', 'wp-ultimo'),
	__('uMzinyathi District Municipality', 'wp-ultimo'),
	__('uThukela District Municipality', 'wp-ultimo'),
	__('uThungulu District Municipality', 'wp-ultimo'),
);
