<?php
/**
 * State City List for LP - ZA.
 *
 * City count: 23
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for LP - ZA.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Bochum', 'wp-ultimo'),
	__('Capricorn District Municipality', 'wp-ultimo'),
	__('Duiwelskloof', 'wp-ultimo'),
	__('Ga-Kgapane', 'wp-ultimo'),
	__('Giyani', 'wp-ultimo'),
	__('Lebowakgomo', 'wp-ultimo'),
	__('Louis Trichardt', 'wp-ultimo'),
	__('Mankoeng', 'wp-ultimo'),
	__('Modimolle', 'wp-ultimo'),
	__('Mokopane', 'wp-ultimo'),
	__('Mopani District Municipality', 'wp-ultimo'),
	__('Musina', 'wp-ultimo'),
	__('Nkowakowa', 'wp-ultimo'),
	__('Phalaborwa', 'wp-ultimo'),
	__('Polokwane', 'wp-ultimo'),
	__('Sekhukhune District Municipality', 'wp-ultimo'),
	__('Thabazimbi', 'wp-ultimo'),
	__('Thohoyandou', 'wp-ultimo'),
	__('Thulamahashi', 'wp-ultimo'),
	__('Tzaneen', 'wp-ultimo'),
	__('Vhembe District Municipality', 'wp-ultimo'),
	__('Warmbaths', 'wp-ultimo'),
	__('Waterberg District Municipality', 'wp-ultimo'),
);
