<?php
/**
 * State City List for MP - ZA.
 *
 * City count: 26
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for MP - ZA.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Balfour', 'wp-ultimo'),
	__('Barberton', 'wp-ultimo'),
	__('Belfast', 'wp-ultimo'),
	__('Bethal', 'wp-ultimo'),
	__('Breyten', 'wp-ultimo'),
	__('Carolina', 'wp-ultimo'),
	__('Delmas', 'wp-ultimo'),
	__('Driefontein', 'wp-ultimo'),
	__('Ehlanzeni District', 'wp-ultimo'),
	__('Ermelo', 'wp-ultimo'),
	__('Gert Sibande District Municipality', 'wp-ultimo'),
	__('Hendrina', 'wp-ultimo'),
	__('Komatipoort', 'wp-ultimo'),
	__('Kriel', 'wp-ultimo'),
	__('Lydenburg', 'wp-ultimo'),
	__('Middelburg', 'wp-ultimo'),
	__('Nelspruit', 'wp-ultimo'),
	__('Nkangala District Municipality', 'wp-ultimo'),
	__('Piet Retief', 'wp-ultimo'),
	__('Secunda', 'wp-ultimo'),
	__('Siyabuswa', 'wp-ultimo'),
	__('Standerton', 'wp-ultimo'),
	__('Volksrust', 'wp-ultimo'),
	__('White River', 'wp-ultimo'),
	__('Witbank', 'wp-ultimo'),
	__('eMbalenhle', 'wp-ultimo'),
);
