<?php
/**
 * State City List for NC - ZA.
 *
 * City count: 28
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for NC - ZA.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Barkly West', 'wp-ultimo'),
	__('Brandvlei', 'wp-ultimo'),
	__('Calvinia', 'wp-ultimo'),
	__('Carnarvon', 'wp-ultimo'),
	__('Colesberg', 'wp-ultimo'),
	__('Daniëlskuil', 'wp-ultimo'),
	__('De Aar', 'wp-ultimo'),
	__('Frances Baard District Municipality', 'wp-ultimo'),
	__('Fraserburg', 'wp-ultimo'),
	__('John Taolo Gaetsewe District Municipality', 'wp-ultimo'),
	__('Kathu', 'wp-ultimo'),
	__('Kenhardt', 'wp-ultimo'),
	__('Kimberley', 'wp-ultimo'),
	__('Kuruman', 'wp-ultimo'),
	__('Namakwa District Municipality', 'wp-ultimo'),
	__('Noupoort', 'wp-ultimo'),
	__('Orania', 'wp-ultimo'),
	__('Pampierstad', 'wp-ultimo'),
	__('Pixley ka Seme District Municipality', 'wp-ultimo'),
	__('Pofadder', 'wp-ultimo'),
	__('Postmasburg', 'wp-ultimo'),
	__('Prieska', 'wp-ultimo'),
	__('Ritchie', 'wp-ultimo'),
	__('Siyanda District Municipality', 'wp-ultimo'),
	__('Springbok', 'wp-ultimo'),
	__('Upington', 'wp-ultimo'),
	__('Van Wyksvlei', 'wp-ultimo'),
	__('Warrenton', 'wp-ultimo'),
);
