<?php
/**
 * State City List for NW - ZA.
 *
 * City count: 24
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for NW - ZA.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Bloemhof', 'wp-ultimo'),
	__('Bojanala Platinum District Municipality', 'wp-ultimo'),
	__('Brits', 'wp-ultimo'),
	__('Christiana', 'wp-ultimo'),
	__('Dr Kenneth Kaunda District Municipality', 'wp-ultimo'),
	__('Dr Ruth Segomotsi Mompati District Municipality', 'wp-ultimo'),
	__('Fochville', 'wp-ultimo'),
	__('Ga-Rankuwa', 'wp-ultimo'),
	__('Jan Kempdorp', 'wp-ultimo'),
	__('Klerksdorp', 'wp-ultimo'),
	__('Koster', 'wp-ultimo'),
	__('Lichtenburg', 'wp-ultimo'),
	__('Mahikeng', 'wp-ultimo'),
	__('Maile', 'wp-ultimo'),
	__('Mmabatho', 'wp-ultimo'),
	__('Ngaka Modiri Molema District Municipality', 'wp-ultimo'),
	__('Orkney', 'wp-ultimo'),
	__('Potchefstroom', 'wp-ultimo'),
	__('Rustenburg', 'wp-ultimo'),
	__('Schweizer-Reneke', 'wp-ultimo'),
	__('Stilfontein', 'wp-ultimo'),
	__('Vryburg', 'wp-ultimo'),
	__('Wolmaransstad', 'wp-ultimo'),
	__('Zeerust', 'wp-ultimo'),
);
