<?php
/**
 * State City List for WC - ZA.
 *
 * City count: 52
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for WC - ZA.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Albertina', 'wp-ultimo'),
	__('Arniston', 'wp-ultimo'),
	__('Atlantis', 'wp-ultimo'),
	__('Beaufort West', 'wp-ultimo'),
	__('Bergvliet', 'wp-ultimo'),
	__('Bredasdorp', 'wp-ultimo'),
	__('Caledon', 'wp-ultimo'),
	__('Calitzdorp', 'wp-ultimo'),
	__('Cape Town', 'wp-ultimo'),
	__('Cape Winelands District Municipality', 'wp-ultimo'),
	__('Central Karoo District Municipality', 'wp-ultimo'),
	__('Ceres', 'wp-ultimo'),
	__('City of Cape Town', 'wp-ultimo'),
	__('Clanwilliam', 'wp-ultimo'),
	__('Claremont', 'wp-ultimo'),
	__('Constantia', 'wp-ultimo'),
	__('De Rust', 'wp-ultimo'),
	__('Eden District Municipality', 'wp-ultimo'),
	__('George', 'wp-ultimo'),
	__('Grabouw', 'wp-ultimo'),
	__('Hardys Memories of Africa', 'wp-ultimo'),
	__('Hermanus', 'wp-ultimo'),
	__('Knysna', 'wp-ultimo'),
	__('Kraaifontein', 'wp-ultimo'),
	__('Ladismith', 'wp-ultimo'),
	__('Lansdowne', 'wp-ultimo'),
	__('Malmesbury', 'wp-ultimo'),
	__('Montagu', 'wp-ultimo'),
	__('Moorreesburg', 'wp-ultimo'),
	__('Mossel Bay', 'wp-ultimo'),
	__('Newlands', 'wp-ultimo'),
	__('Oudtshoorn', 'wp-ultimo'),
	__('Overberg District Municipality', 'wp-ultimo'),
	__('Paarl', 'wp-ultimo'),
	__('Piketberg', 'wp-ultimo'),
	__('Plettenberg Bay', 'wp-ultimo'),
	__('Prince Albert', 'wp-ultimo'),
	__('Retreat', 'wp-ultimo'),
	__('Riversdale', 'wp-ultimo'),
	__('Robertson', 'wp-ultimo'),
	__('Rondebosch', 'wp-ultimo'),
	__('Rosebank', 'wp-ultimo'),
	__('Saldanha', 'wp-ultimo'),
	__('Stellenbosch', 'wp-ultimo'),
	__('Sunset Beach', 'wp-ultimo'),
	__('Swellendam', 'wp-ultimo'),
	__('Vredenburg', 'wp-ultimo'),
	__('Vredendal', 'wp-ultimo'),
	__('Wellington', 'wp-ultimo'),
	__('West Coast District Municipality', 'wp-ultimo'),
	__('Worcester', 'wp-ultimo'),
	__('Zoar', 'wp-ultimo'),
);
