<?php
/**
 * State City List for MB - CA.
 *
 * City count: 43
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for MB - CA.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Altona', 'wp-ultimo'),
	__('Beausejour', 'wp-ultimo'),
	__('Boissevain', 'wp-ultimo'),
	__('Brandon', 'wp-ultimo'),
	__('Carberry', 'wp-ultimo'),
	__('Carman', 'wp-ultimo'),
	__('Cross Lake 19A', 'wp-ultimo'),
	__('Dauphin', 'wp-ultimo'),
	__('De Salaberry', 'wp-ultimo'),
	__('Deloraine', 'wp-ultimo'),
	__('Flin Flon', 'wp-ultimo'),
	__('Gimli', 'wp-ultimo'),
	__('Grunthal', 'wp-ultimo'),
	__('Headingley', 'wp-ultimo'),
	__('Ile des Chênes', 'wp-ultimo'),
	__('Killarney', 'wp-ultimo'),
	__('La Broquerie', 'wp-ultimo'),
	__('Lac du Bonnet', 'wp-ultimo'),
	__('Landmark', 'wp-ultimo'),
	__('Lorette', 'wp-ultimo'),
	__('Melita', 'wp-ultimo'),
	__('Minnedosa', 'wp-ultimo'),
	__('Moose Lake', 'wp-ultimo'),
	__('Morden', 'wp-ultimo'),
	__('Morris', 'wp-ultimo'),
	__('Neepawa', 'wp-ultimo'),
	__('Niverville', 'wp-ultimo'),
	__('Portage la Prairie', 'wp-ultimo'),
	__('Rivers', 'wp-ultimo'),
	__('Roblin', 'wp-ultimo'),
	__('Selkirk', 'wp-ultimo'),
	__('Shilo', 'wp-ultimo'),
	__('Souris', 'wp-ultimo'),
	__('St. Adolphe', 'wp-ultimo'),
	__('Steinbach', 'wp-ultimo'),
	__('Stonewall', 'wp-ultimo'),
	__('Swan River', 'wp-ultimo'),
	__('The Pas', 'wp-ultimo'),
	__('Thompson', 'wp-ultimo'),
	__('Virden', 'wp-ultimo'),
	__('West St. Paul', 'wp-ultimo'),
	__('Winkler', 'wp-ultimo'),
	__('Winnipeg', 'wp-ultimo'),
);
