<?php
/**
 * State City List for NB - CA.
 *
 * City count: 37
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for NB - CA.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Baie Ste. Anne', 'wp-ultimo'),
	__('Bathurst', 'wp-ultimo'),
	__('Bouctouche', 'wp-ultimo'),
	__('Campbellton', 'wp-ultimo'),
	__('Dieppe', 'wp-ultimo'),
	__('Edmundston', 'wp-ultimo'),
	__('Florenceville-Bristol', 'wp-ultimo'),
	__('Fredericton', 'wp-ultimo'),
	__('Fundy Bay', 'wp-ultimo'),
	__('Grande-Digue', 'wp-ultimo'),
	__('Greater Lakeburn', 'wp-ultimo'),
	__('Hampton', 'wp-ultimo'),
	__('Harrison Brook', 'wp-ultimo'),
	__('Keswick Ridge', 'wp-ultimo'),
	__('Lincoln', 'wp-ultimo'),
	__('Lutes Mountain', 'wp-ultimo'),
	__('McEwen', 'wp-ultimo'),
	__('Miramichi', 'wp-ultimo'),
	__('Moncton', 'wp-ultimo'),
	__('Nackawic', 'wp-ultimo'),
	__('New Maryland', 'wp-ultimo'),
	__('Noonan', 'wp-ultimo'),
	__('Oromocto', 'wp-ultimo'),
	__('Richibucto', 'wp-ultimo'),
	__('Sackville', 'wp-ultimo'),
	__('Saint Andrews', 'wp-ultimo'),
	__('Saint John', 'wp-ultimo'),
	__('Saint-Antoine', 'wp-ultimo'),
	__('Saint-Léonard', 'wp-ultimo'),
	__('Salisbury', 'wp-ultimo'),
	__('Shediac', 'wp-ultimo'),
	__('Shediac Bridge-Shediac River', 'wp-ultimo'),
	__('Shippagan', 'wp-ultimo'),
	__('Starlight Village', 'wp-ultimo'),
	__('Sussex', 'wp-ultimo'),
	__('Tracadie-Sheila', 'wp-ultimo'),
	__('Wells', 'wp-ultimo'),
);
