<?php
/**
 * State City List for NS - CA.
 *
 * City count: 43
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for NS - CA.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Amherst', 'wp-ultimo'),
	__('Annapolis County', 'wp-ultimo'),
	__('Antigonish', 'wp-ultimo'),
	__('Berwick', 'wp-ultimo'),
	__('Bridgewater', 'wp-ultimo'),
	__('Cape Breton County', 'wp-ultimo'),
	__('Chester', 'wp-ultimo'),
	__('Colchester', 'wp-ultimo'),
	__('Cole Harbour', 'wp-ultimo'),
	__('Cow Bay', 'wp-ultimo'),
	__('Dartmouth', 'wp-ultimo'),
	__('Digby', 'wp-ultimo'),
	__('Digby County', 'wp-ultimo'),
	__('English Corner', 'wp-ultimo'),
	__('Eskasoni 3', 'wp-ultimo'),
	__('Fall River', 'wp-ultimo'),
	__('Glace Bay', 'wp-ultimo'),
	__('Greenwood', 'wp-ultimo'),
	__('Halifax', 'wp-ultimo'),
	__('Hantsport', 'wp-ultimo'),
	__('Hayes Subdivision', 'wp-ultimo'),
	__('Kentville', 'wp-ultimo'),
	__('Lake Echo', 'wp-ultimo'),
	__('Lantz', 'wp-ultimo'),
	__('Lower Sackville', 'wp-ultimo'),
	__('Lunenburg', 'wp-ultimo'),
	__('Middleton', 'wp-ultimo'),
	__('New Glasgow', 'wp-ultimo'),
	__('Oxford', 'wp-ultimo'),
	__('Parrsboro', 'wp-ultimo'),
	__('Pictou', 'wp-ultimo'),
	__('Pictou County', 'wp-ultimo'),
	__('Port Hawkesbury', 'wp-ultimo'),
	__('Port Williams', 'wp-ultimo'),
	__('Princeville', 'wp-ultimo'),
	__('Shelburne', 'wp-ultimo'),
	__('Springhill', 'wp-ultimo'),
	__('Sydney', 'wp-ultimo'),
	__('Sydney Mines', 'wp-ultimo'),
	__('Truro', 'wp-ultimo'),
	__('Windsor', 'wp-ultimo'),
	__('Wolfville', 'wp-ultimo'),
	__('Yarmouth', 'wp-ultimo'),
);
