<?php
/**
 * State City List for NT - CA.
 *
 * City count: 7
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for NT - CA.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Behchokǫ̀', 'wp-ultimo'),
	__('Fort McPherson', 'wp-ultimo'),
	__('Fort Smith', 'wp-ultimo'),
	__('Hay River', 'wp-ultimo'),
	__('Inuvik', 'wp-ultimo'),
	__('Norman Wells', 'wp-ultimo'),
	__('Yellowknife', 'wp-ultimo'),
);
