<?php
/**
 * State City List for NU - CA.
 *
 * City count: 6
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for NU - CA.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Clyde River', 'wp-ultimo'),
	__('Gjoa Haven', 'wp-ultimo'),
	__('Iqaluit', 'wp-ultimo'),
	__('Kugluktuk', 'wp-ultimo'),
	__('Pangnirtung', 'wp-ultimo'),
	__('Rankin Inlet', 'wp-ultimo'),
);
