<?php
/**
 * State City List for PE - CA.
 *
 * City count: 9
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for PE - CA.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Alberton', 'wp-ultimo'),
	__('Belfast', 'wp-ultimo'),
	__('Charlottetown', 'wp-ultimo'),
	__('Cornwall', 'wp-ultimo'),
	__('Fallingbrook', 'wp-ultimo'),
	__('Kensington', 'wp-ultimo'),
	__('Montague', 'wp-ultimo'),
	__('Souris', 'wp-ultimo'),
	__('Summerside', 'wp-ultimo'),
);
