<?php
/**
 * State City List for SK - CA.
 *
 * City count: 54
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for SK - CA.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Assiniboia', 'wp-ultimo'),
	__('Biggar', 'wp-ultimo'),
	__('Canora', 'wp-ultimo'),
	__('Carlyle', 'wp-ultimo'),
	__('Dalmeny', 'wp-ultimo'),
	__('Esterhazy', 'wp-ultimo'),
	__('Estevan', 'wp-ultimo'),
	__('Foam Lake', 'wp-ultimo'),
	__('Gravelbourg', 'wp-ultimo'),
	__('Hudson Bay', 'wp-ultimo'),
	__('Humboldt', 'wp-ultimo'),
	__('Indian Head', 'wp-ultimo'),
	__('Kamsack', 'wp-ultimo'),
	__('Kerrobert', 'wp-ultimo'),
	__('Kindersley', 'wp-ultimo'),
	__('La Ronge', 'wp-ultimo'),
	__('Langenburg', 'wp-ultimo'),
	__('Langham', 'wp-ultimo'),
	__('Lanigan', 'wp-ultimo'),
	__('Lumsden', 'wp-ultimo'),
	__('Macklin', 'wp-ultimo'),
	__('Maple Creek', 'wp-ultimo'),
	__('Martensville', 'wp-ultimo'),
	__('Meadow Lake', 'wp-ultimo'),
	__('Melfort', 'wp-ultimo'),
	__('Melville', 'wp-ultimo'),
	__('Moose Jaw', 'wp-ultimo'),
	__('Moosomin', 'wp-ultimo'),
	__('Nipawin', 'wp-ultimo'),
	__('North Battleford', 'wp-ultimo'),
	__('Outlook', 'wp-ultimo'),
	__('Oxbow', 'wp-ultimo'),
	__('Pelican Narrows', 'wp-ultimo'),
	__('Pilot Butte', 'wp-ultimo'),
	__('Preeceville', 'wp-ultimo'),
	__('Prince Albert', 'wp-ultimo'),
	__('Regina', 'wp-ultimo'),
	__('Regina Beach', 'wp-ultimo'),
	__('Rosetown', 'wp-ultimo'),
	__('Rosthern', 'wp-ultimo'),
	__('Saskatoon', 'wp-ultimo'),
	__('Shaunavon', 'wp-ultimo'),
	__('Shellbrook', 'wp-ultimo'),
	__('Swift Current', 'wp-ultimo'),
	__('Tisdale', 'wp-ultimo'),
	__('Unity', 'wp-ultimo'),
	__('Wadena', 'wp-ultimo'),
	__('Warman', 'wp-ultimo'),
	__('Watrous', 'wp-ultimo'),
	__('Weyburn', 'wp-ultimo'),
	__('White City', 'wp-ultimo'),
	__('Wilkie', 'wp-ultimo'),
	__('Wynyard', 'wp-ultimo'),
	__('Yorkton', 'wp-ultimo'),
);
