<?php
/**
 * State City List for YT - CA.
 *
 * City count: 4
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for YT - CA.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Dawson City', 'wp-ultimo'),
	__('Haines Junction', 'wp-ultimo'),
	__('Watson Lake', 'wp-ultimo'),
	__('Whitehorse', 'wp-ultimo'),
);
