<?php

// scoper-autoload.php @generated by PhpScoper

$loader = require_once __DIR__.'/autoload.php';

// Functions whitelisting. For more information see:
// https://github.com/humbug/php-scoper/blob/master/README.md#functions-whitelisting
if (!function_exists('_manually_load_plugin')) {
    function _manually_load_plugin() {
        return \WP_Ultimo\Dependencies\_manually_load_plugin(...func_get_args());
    }
}

return $loader;
