<?php
/**
 * State City List for FL - NL.
 *
 * City count: 14
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for FL - NL.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Almere Stad', 'wp-ultimo'),
	__('Biddinghuizen', 'wp-ultimo'),
	__('Dronten', 'wp-ultimo'),
	__('Emmeloord', 'wp-ultimo'),
	__('Ens', 'wp-ultimo'),
	__('Gemeente Almere', 'wp-ultimo'),
	__('Gemeente Dronten', 'wp-ultimo'),
	__('Gemeente Lelystad', 'wp-ultimo'),
	__('Gemeente Noordoostpolder', 'wp-ultimo'),
	__('Gemeente Urk', 'wp-ultimo'),
	__('Gemeente Zeewolde', 'wp-ultimo'),
	__('Lelystad', 'wp-ultimo'),
	__('Urk', 'wp-ultimo'),
	__('Zeewolde', 'wp-ultimo'),
);
