<?php
/**
 * State City List for OV - NL.
 *
 * City count: 90
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for OV - NL.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Almelo', 'wp-ultimo'),
	__('Baalder', 'wp-ultimo'),
	__('Berkum', 'wp-ultimo'),
	__('Blokzijl', 'wp-ultimo'),
	__('Borgele', 'wp-ultimo'),
	__('Borne', 'wp-ultimo'),
	__('Boskamp', 'wp-ultimo'),
	__('Brunnepe', 'wp-ultimo'),
	__('Dalfsen', 'wp-ultimo'),
	__('De Hoven', 'wp-ultimo'),
	__('Delden', 'wp-ultimo'),
	__('Den Ham', 'wp-ultimo'),
	__('Deventer', 'wp-ultimo'),
	__('Diepenheim', 'wp-ultimo'),
	__('Enschede', 'wp-ultimo'),
	__('Flevowijk', 'wp-ultimo'),
	__('Frankhuis', 'wp-ultimo'),
	__('Gemeente Almelo', 'wp-ultimo'),
	__('Gemeente Borne', 'wp-ultimo'),
	__('Gemeente Dalfsen', 'wp-ultimo'),
	__('Gemeente Deventer', 'wp-ultimo'),
	__('Gemeente Dinkelland', 'wp-ultimo'),
	__('Gemeente Enschede', 'wp-ultimo'),
	__('Gemeente Haaksbergen', 'wp-ultimo'),
	__('Gemeente Hardenberg', 'wp-ultimo'),
	__('Gemeente Hellendoorn', 'wp-ultimo'),
	__('Gemeente Hengelo', 'wp-ultimo'),
	__('Gemeente Hof van Twente', 'wp-ultimo'),
	__('Gemeente Kampen', 'wp-ultimo'),
	__('Gemeente Losser', 'wp-ultimo'),
	__('Gemeente Oldenzaal', 'wp-ultimo'),
	__('Gemeente Olst-Wijhe', 'wp-ultimo'),
	__('Gemeente Ommen', 'wp-ultimo'),
	__('Gemeente Raalte', 'wp-ultimo'),
	__('Gemeente Rijssen-Holten', 'wp-ultimo'),
	__('Gemeente Staphorst', 'wp-ultimo'),
	__('Gemeente Steenwijkerland', 'wp-ultimo'),
	__('Gemeente Tubbergen', 'wp-ultimo'),
	__('Gemeente Twenterand', 'wp-ultimo'),
	__('Gemeente Wierden', 'wp-ultimo'),
	__('Gemeente Zwartewaterland', 'wp-ultimo'),
	__('Gemeente Zwolle', 'wp-ultimo'),
	__('Giethoorn', 'wp-ultimo'),
	__('Goor', 'wp-ultimo'),
	__('Grafhorst', 'wp-ultimo'),
	__('Haaksbergen', 'wp-ultimo'),
	__('Haarle', 'wp-ultimo'),
	__('Hardenberg', 'wp-ultimo'),
	__('Hasselt', 'wp-ultimo'),
	__('Heino', 'wp-ultimo'),
	__('Hengelo', 'wp-ultimo'),
	__('Hengevelde', 'wp-ultimo'),
	__('Het Oostrik', 'wp-ultimo'),
	__('Kampen', 'wp-ultimo'),
	__('Klein Driene', 'wp-ultimo'),
	__('Losser', 'wp-ultimo'),
	__('Magele', 'wp-ultimo'),
	__('Markelo', 'wp-ultimo'),
	__('Mekkelholt', 'wp-ultimo'),
	__('Nieuwoord', 'wp-ultimo'),
	__('Nijrees', 'wp-ultimo'),
	__('Oldemarkt', 'wp-ultimo'),
	__('Oldenzaal', 'wp-ultimo'),
	__('Olst', 'wp-ultimo'),
	__('Ommen', 'wp-ultimo'),
	__('Oosterholt', 'wp-ultimo'),
	__('Oostermeenthe', 'wp-ultimo'),
	__('Ootmarsum', 'wp-ultimo'),
	__('Pathmos', 'wp-ultimo'),
	__('Pierik', 'wp-ultimo'),
	__('Raalte', 'wp-ultimo'),
	__('Rossum', 'wp-ultimo'),
	__('Schalkhaar', 'wp-ultimo'),
	__('Sint Jansklooster', 'wp-ultimo'),
	__('Staphorst', 'wp-ultimo'),
	__('Steenwijk', 'wp-ultimo'),
	__('Steenwijkerwold', 'wp-ultimo'),
	__('Tubbergen', 'wp-ultimo'),
	__('Tuk', 'wp-ultimo'),
	__('Twekkelerveld', 'wp-ultimo'),
	__('Vollenhove', 'wp-ultimo'),
	__('Vriezenveen', 'wp-ultimo'),
	__('Vroomshoop', 'wp-ultimo'),
	__('Westerhaar-Vriezenveensewijk', 'wp-ultimo'),
	__('Wierden', 'wp-ultimo'),
	__('Wijhe', 'wp-ultimo'),
	__('Woolde', 'wp-ultimo'),
	__('Wooldrik', 'wp-ultimo'),
	__('Zuid-Berghuizen', 'wp-ultimo'),
	__('Zwolle', 'wp-ultimo'),
);
