<?php
/**
 * State City List for UT - NL.
 *
 * City count: 86
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for UT - NL.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Abcoude', 'wp-ultimo'),
	__('Amerongen', 'wp-ultimo'),
	__('Amersfoort', 'wp-ultimo'),
	__('Austerlitz', 'wp-ultimo'),
	__('Baambrugge', 'wp-ultimo'),
	__('Baarn', 'wp-ultimo'),
	__('Bosch en Duin', 'wp-ultimo'),
	__('Breukelen', 'wp-ultimo'),
	__('Bunnik', 'wp-ultimo'),
	__('Bunschoten', 'wp-ultimo'),
	__('Cothen', 'wp-ultimo'),
	__('De Bilt', 'wp-ultimo'),
	__('De Hagen', 'wp-ultimo'),
	__('De Uithof', 'wp-ultimo'),
	__('Doorn', 'wp-ultimo'),
	__('Driebergen-Rijsenburg', 'wp-ultimo'),
	__('Gemeente Amersfoort', 'wp-ultimo'),
	__('Gemeente Baarn', 'wp-ultimo'),
	__('Gemeente Bunnik', 'wp-ultimo'),
	__('Gemeente Bunschoten', 'wp-ultimo'),
	__('Gemeente De Bilt', 'wp-ultimo'),
	__('Gemeente De Ronde Venen', 'wp-ultimo'),
	__('Gemeente Eemnes', 'wp-ultimo'),
	__('Gemeente Houten', 'wp-ultimo'),
	__('Gemeente IJsselstein', 'wp-ultimo'),
	__('Gemeente Leusden', 'wp-ultimo'),
	__('Gemeente Lopik', 'wp-ultimo'),
	__('Gemeente Montfoort', 'wp-ultimo'),
	__('Gemeente Nieuwegein', 'wp-ultimo'),
	__('Gemeente Oudewater', 'wp-ultimo'),
	__('Gemeente Renswoude', 'wp-ultimo'),
	__('Gemeente Rhenen', 'wp-ultimo'),
	__('Gemeente Soest', 'wp-ultimo'),
	__('Gemeente Utrecht', 'wp-ultimo'),
	__('Gemeente Utrechtse Heuvelrug', 'wp-ultimo'),
	__('Gemeente Veenendaal', 'wp-ultimo'),
	__('Gemeente Wijk bij Duurstede', 'wp-ultimo'),
	__('Gemeente Woerden', 'wp-ultimo'),
	__('Gemeente Woudenberg', 'wp-ultimo'),
	__('Gemeente Zeist', 'wp-ultimo'),
	__('Groenekan', 'wp-ultimo'),
	__('Hollandsche Rading', 'wp-ultimo'),
	__('Houten', 'wp-ultimo'),
	__('IJsselstein', 'wp-ultimo'),
	__('Kedichem', 'wp-ultimo'),
	__('Kerckebosch', 'wp-ultimo'),
	__('Langenoord', 'wp-ultimo'),
	__('Leerdam', 'wp-ultimo'),
	__('Leersum', 'wp-ultimo'),
	__('Leusden', 'wp-ultimo'),
	__('Linschoten', 'wp-ultimo'),
	__('Lopik', 'wp-ultimo'),
	__('Lunetten', 'wp-ultimo'),
	__('Maarn', 'wp-ultimo'),
	__('Maarssen', 'wp-ultimo'),
	__('Maartensdijk', 'wp-ultimo'),
	__('Mijdrecht', 'wp-ultimo'),
	__('Montfoort', 'wp-ultimo'),
	__('Nieuwegein', 'wp-ultimo'),
	__('Nijenheim', 'wp-ultimo'),
	__('Odijk', 'wp-ultimo'),
	__('Oog in Al', 'wp-ultimo'),
	__('Oudewater', 'wp-ultimo'),
	__('Overberg', 'wp-ultimo'),
	__('Randenbroek', 'wp-ultimo'),
	__('Renswoude', 'wp-ultimo'),
	__('Rhenen', 'wp-ultimo'),
	__('Schoonrewoerd', 'wp-ultimo'),
	__('Soest', 'wp-ultimo'),
	__('Soestdijk', 'wp-ultimo'),
	__('Spakenburg', 'wp-ultimo'),
	__('Spechtenkamp', 'wp-ultimo'),
	__('Stichtse Vecht', 'wp-ultimo'),
	__('Utrecht', 'wp-ultimo'),
	__('Veenendaal', 'wp-ultimo'),
	__('Veldhuizen', 'wp-ultimo'),
	__('Vianen', 'wp-ultimo'),
	__('Vinkeveen', 'wp-ultimo'),
	__('Vleuten', 'wp-ultimo'),
	__('Vreeswijk', 'wp-ultimo'),
	__('Werkhoven', 'wp-ultimo'),
	__('Wijk bij Duurstede', 'wp-ultimo'),
	__('Wilnis', 'wp-ultimo'),
	__('Woerden', 'wp-ultimo'),
	__('Woudenberg', 'wp-ultimo'),
	__('Zeist', 'wp-ultimo'),
);
