<?php
/**
 * State City List for AK - US.
 *
 * City count: 95
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for AK - US.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Akutan', 'wp-ultimo'),
	__('Aleutians East Borough', 'wp-ultimo'),
	__('Aleutians West Census Area', 'wp-ultimo'),
	__('Anchor Point', 'wp-ultimo'),
	__('Anchorage', 'wp-ultimo'),
	__('Anchorage Municipality', 'wp-ultimo'),
	__('Badger', 'wp-ultimo'),
	__('Barrow', 'wp-ultimo'),
	__('Bear Creek', 'wp-ultimo'),
	__('Bethel', 'wp-ultimo'),
	__('Bethel Census Area', 'wp-ultimo'),
	__('Big Lake', 'wp-ultimo'),
	__('Bristol Bay Borough', 'wp-ultimo'),
	__('Butte', 'wp-ultimo'),
	__('Chevak', 'wp-ultimo'),
	__('City and Borough of Wrangell', 'wp-ultimo'),
	__('Cohoe', 'wp-ultimo'),
	__('College', 'wp-ultimo'),
	__('Cordova', 'wp-ultimo'),
	__('Craig', 'wp-ultimo'),
	__('Deltana', 'wp-ultimo'),
	__('Denali Borough', 'wp-ultimo'),
	__('Diamond Ridge', 'wp-ultimo'),
	__('Dillingham', 'wp-ultimo'),
	__('Dillingham Census Area', 'wp-ultimo'),
	__('Dutch Harbor', 'wp-ultimo'),
	__('Eagle River', 'wp-ultimo'),
	__('Eielson Air Force Base', 'wp-ultimo'),
	__('Elmendorf Air Force Base', 'wp-ultimo'),
	__('Ester', 'wp-ultimo'),
	__('Fairbanks', 'wp-ultimo'),
	__('Fairbanks North Star Borough', 'wp-ultimo'),
	__('Farm Loop', 'wp-ultimo'),
	__('Farmers Loop', 'wp-ultimo'),
	__('Fishhook', 'wp-ultimo'),
	__('Fritz Creek', 'wp-ultimo'),
	__('Gateway', 'wp-ultimo'),
	__('Girdwood', 'wp-ultimo'),
	__('Haines', 'wp-ultimo'),
	__('Haines Borough', 'wp-ultimo'),
	__('Healy', 'wp-ultimo'),
	__('Homer', 'wp-ultimo'),
	__('Hoonah-Angoon Census Area', 'wp-ultimo'),
	__('Hooper Bay', 'wp-ultimo'),
	__('Houston', 'wp-ultimo'),
	__('Juneau', 'wp-ultimo'),
	__('Kalifornsky', 'wp-ultimo'),
	__('Kenai', 'wp-ultimo'),
	__('Kenai Peninsula Borough', 'wp-ultimo'),
	__('Ketchikan', 'wp-ultimo'),
	__('Ketchikan Gateway Borough', 'wp-ultimo'),
	__('King Cove', 'wp-ultimo'),
	__('Knik-Fairview', 'wp-ultimo'),
	__('Kodiak', 'wp-ultimo'),
	__('Kodiak Island Borough', 'wp-ultimo'),
	__('Kodiak Station', 'wp-ultimo'),
	__('Kotzebue', 'wp-ultimo'),
	__('Lake and Peninsula Borough', 'wp-ultimo'),
	__('Lakes', 'wp-ultimo'),
	__('Lazy Mountain', 'wp-ultimo'),
	__('Matanuska-Susitna Borough', 'wp-ultimo'),
	__('Meadow Lakes', 'wp-ultimo'),
	__('Metlakatla', 'wp-ultimo'),
	__('Nikiski', 'wp-ultimo'),
	__('Nome', 'wp-ultimo'),
	__('Nome Census Area', 'wp-ultimo'),
	__('North Pole', 'wp-ultimo'),
	__('North Slope Borough', 'wp-ultimo'),
	__('Northwest Arctic Borough', 'wp-ultimo'),
	__('Palmer', 'wp-ultimo'),
	__('Petersburg', 'wp-ultimo'),
	__('Petersburg Borough', 'wp-ultimo'),
	__('Prudhoe Bay', 'wp-ultimo'),
	__('Ridgeway', 'wp-ultimo'),
	__('Salcha', 'wp-ultimo'),
	__('Sand Point', 'wp-ultimo'),
	__('Seward', 'wp-ultimo'),
	__('Sitka', 'wp-ultimo'),
	__('Sitka City and Borough', 'wp-ultimo'),
	__('Skagway Municipality', 'wp-ultimo'),
	__('Soldotna', 'wp-ultimo'),
	__('Southeast Fairbanks Census Area', 'wp-ultimo'),
	__('Sterling', 'wp-ultimo'),
	__('Sutton-Alpine', 'wp-ultimo'),
	__('Tanaina', 'wp-ultimo'),
	__('Tok', 'wp-ultimo'),
	__('Unalaska', 'wp-ultimo'),
	__('Valdez', 'wp-ultimo'),
	__('Valdez-Cordova Census Area', 'wp-ultimo'),
	__('Wasilla', 'wp-ultimo'),
	__('Willow', 'wp-ultimo'),
	__('Wrangell', 'wp-ultimo'),
	__('Y', 'wp-ultimo'),
	__('Yakutat City and Borough', 'wp-ultimo'),
	__('Yukon-Koyukuk Census Area', 'wp-ultimo'),
);
