<?php
/**
 * State City List for DC - US.
 *
 * City count: 5
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for DC - US.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Adams Morgan', 'wp-ultimo'),
	__('Bloomingdale', 'wp-ultimo'),
	__('Chevy Chase', 'wp-ultimo'),
	__('Shaw', 'wp-ultimo'),
	__('Washington, D.C.', 'wp-ultimo'),
);
