<?php
/**
 * State City List for DE - US.
 *
 * City count: 54
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for DE - US.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Bear', 'wp-ultimo'),
	__('Bellefonte', 'wp-ultimo'),
	__('Bethany Beach', 'wp-ultimo'),
	__('Blades', 'wp-ultimo'),
	__('Bridgeville', 'wp-ultimo'),
	__('Brookside', 'wp-ultimo'),
	__('Camden', 'wp-ultimo'),
	__('Cheswold', 'wp-ultimo'),
	__('Claymont', 'wp-ultimo'),
	__('Clayton', 'wp-ultimo'),
	__('Delaware City', 'wp-ultimo'),
	__('Delmar', 'wp-ultimo'),
	__('Dover', 'wp-ultimo'),
	__('Dover Base Housing', 'wp-ultimo'),
	__('Edgemoor', 'wp-ultimo'),
	__('Elsmere', 'wp-ultimo'),
	__('Felton', 'wp-ultimo'),
	__('Georgetown', 'wp-ultimo'),
	__('Glasgow', 'wp-ultimo'),
	__('Greenville', 'wp-ultimo'),
	__('Greenwood', 'wp-ultimo'),
	__('Harrington', 'wp-ultimo'),
	__('Highland Acres', 'wp-ultimo'),
	__('Hockessin', 'wp-ultimo'),
	__('Kent Acres', 'wp-ultimo'),
	__('Kent County', 'wp-ultimo'),
	__('Laurel', 'wp-ultimo'),
	__('Lewes', 'wp-ultimo'),
	__('Long Neck', 'wp-ultimo'),
	__('Middletown', 'wp-ultimo'),
	__('Milford', 'wp-ultimo'),
	__('Millsboro', 'wp-ultimo'),
	__('Milton', 'wp-ultimo'),
	__('New Castle', 'wp-ultimo'),
	__('New Castle County', 'wp-ultimo'),
	__('Newark', 'wp-ultimo'),
	__('Newport', 'wp-ultimo'),
	__('North Star', 'wp-ultimo'),
	__('Ocean View', 'wp-ultimo'),
	__('Pike Creek', 'wp-ultimo'),
	__('Pike Creek Valley', 'wp-ultimo'),
	__('Rehoboth Beach', 'wp-ultimo'),
	__('Rising Sun-Lebanon', 'wp-ultimo'),
	__('Riverview', 'wp-ultimo'),
	__('Rodney Village', 'wp-ultimo'),
	__('Seaford', 'wp-ultimo'),
	__('Selbyville', 'wp-ultimo'),
	__('Smyrna', 'wp-ultimo'),
	__('Sussex County', 'wp-ultimo'),
	__('Townsend', 'wp-ultimo'),
	__('Wilmington', 'wp-ultimo'),
	__('Wilmington Manor', 'wp-ultimo'),
	__('Woodside East', 'wp-ultimo'),
	__('Wyoming', 'wp-ultimo'),
);
