<?php
/**
 * State City List for NV - US.
 *
 * City count: 82
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for NV - US.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Alamo', 'wp-ultimo'),
	__('Battle Mountain', 'wp-ultimo'),
	__('Beatty', 'wp-ultimo'),
	__('Boulder City', 'wp-ultimo'),
	__('Bunkerville', 'wp-ultimo'),
	__('Caliente', 'wp-ultimo'),
	__('Carlin', 'wp-ultimo'),
	__('Carson City', 'wp-ultimo'),
	__('Churchill County', 'wp-ultimo'),
	__('Clark County', 'wp-ultimo'),
	__('Cold Springs', 'wp-ultimo'),
	__('Dayton', 'wp-ultimo'),
	__('Douglas County', 'wp-ultimo'),
	__('East Valley', 'wp-ultimo'),
	__('Elko', 'wp-ultimo'),
	__('Elko County', 'wp-ultimo'),
	__('Ely', 'wp-ultimo'),
	__('Enterprise', 'wp-ultimo'),
	__('Esmeralda County', 'wp-ultimo'),
	__('Eureka', 'wp-ultimo'),
	__('Eureka County', 'wp-ultimo'),
	__('Fallon', 'wp-ultimo'),
	__('Fernley', 'wp-ultimo'),
	__('Gardnerville', 'wp-ultimo'),
	__('Gardnerville Ranchos', 'wp-ultimo'),
	__('Golden Valley', 'wp-ultimo'),
	__('Goldfield', 'wp-ultimo'),
	__('Hawthorne', 'wp-ultimo'),
	__('Henderson', 'wp-ultimo'),
	__('Humboldt County', 'wp-ultimo'),
	__('Incline Village', 'wp-ultimo'),
	__('Indian Hills', 'wp-ultimo'),
	__('Jackpot', 'wp-ultimo'),
	__('Johnson Lane', 'wp-ultimo'),
	__('Kingsbury', 'wp-ultimo'),
	__('Lander County', 'wp-ultimo'),
	__('Las Vegas', 'wp-ultimo'),
	__('Laughlin', 'wp-ultimo'),
	__('Lemmon Valley', 'wp-ultimo'),
	__('Lincoln County', 'wp-ultimo'),
	__('Lovelock', 'wp-ultimo'),
	__('Lyon County', 'wp-ultimo'),
	__('McGill', 'wp-ultimo'),
	__('Mesquite', 'wp-ultimo'),
	__('Minden', 'wp-ultimo'),
	__('Mineral County', 'wp-ultimo'),
	__('Moapa Town', 'wp-ultimo'),
	__('Moapa Valley', 'wp-ultimo'),
	__('Mogul', 'wp-ultimo'),
	__('Nellis Air Force Base', 'wp-ultimo'),
	__('North Las Vegas', 'wp-ultimo'),
	__('Nye County', 'wp-ultimo'),
	__('Pahrump', 'wp-ultimo'),
	__('Paradise', 'wp-ultimo'),
	__('Pershing County', 'wp-ultimo'),
	__('Pioche', 'wp-ultimo'),
	__('Reno', 'wp-ultimo'),
	__('Sandy Valley', 'wp-ultimo'),
	__('Silver Springs', 'wp-ultimo'),
	__('Smith', 'wp-ultimo'),
	__('Smith Valley', 'wp-ultimo'),
	__('Spanish Springs', 'wp-ultimo'),
	__('Sparks', 'wp-ultimo'),
	__('Spring Creek', 'wp-ultimo'),
	__('Spring Valley', 'wp-ultimo'),
	__('Stagecoach', 'wp-ultimo'),
	__('Storey County', 'wp-ultimo'),
	__('Summerlin South', 'wp-ultimo'),
	__('Sun Valley', 'wp-ultimo'),
	__('Sunrise Manor', 'wp-ultimo'),
	__('Tonopah', 'wp-ultimo'),
	__('Topaz Ranch Estates', 'wp-ultimo'),
	__('Verdi', 'wp-ultimo'),
	__('Virginia City', 'wp-ultimo'),
	__('Washoe County', 'wp-ultimo'),
	__('Wells', 'wp-ultimo'),
	__('West Wendover', 'wp-ultimo'),
	__('White Pine County', 'wp-ultimo'),
	__('Whitney', 'wp-ultimo'),
	__('Winchester', 'wp-ultimo'),
	__('Winnemucca', 'wp-ultimo'),
	__('Yerington', 'wp-ultimo'),
);
