<?php
/**
 * State City List for RI - US.
 *
 * City count: 54
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for RI - US.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Ashaway', 'wp-ultimo'),
	__('Barrington', 'wp-ultimo'),
	__('Bradford', 'wp-ultimo'),
	__('Bristol', 'wp-ultimo'),
	__('Bristol County', 'wp-ultimo'),
	__('Central Falls', 'wp-ultimo'),
	__('Charlestown', 'wp-ultimo'),
	__('Chepachet', 'wp-ultimo'),
	__('Coventry', 'wp-ultimo'),
	__('Cranston', 'wp-ultimo'),
	__('Cumberland', 'wp-ultimo'),
	__('Cumberland Hill', 'wp-ultimo'),
	__('East Greenwich', 'wp-ultimo'),
	__('East Providence', 'wp-ultimo'),
	__('Exeter', 'wp-ultimo'),
	__('Foster', 'wp-ultimo'),
	__('Greenville', 'wp-ultimo'),
	__('Harrisville', 'wp-ultimo'),
	__('Hope Valley', 'wp-ultimo'),
	__('Hopkinton', 'wp-ultimo'),
	__('Jamestown', 'wp-ultimo'),
	__('Johnston', 'wp-ultimo'),
	__('Kent County', 'wp-ultimo'),
	__('Kingston', 'wp-ultimo'),
	__('Lincoln', 'wp-ultimo'),
	__('Melville', 'wp-ultimo'),
	__('Middletown', 'wp-ultimo'),
	__('Narragansett', 'wp-ultimo'),
	__('Narragansett Pier', 'wp-ultimo'),
	__('New Shoreham', 'wp-ultimo'),
	__('Newport', 'wp-ultimo'),
	__('Newport County', 'wp-ultimo'),
	__('Newport East', 'wp-ultimo'),
	__('North Kingstown', 'wp-ultimo'),
	__('North Providence', 'wp-ultimo'),
	__('North Scituate', 'wp-ultimo'),
	__('North Smithfield', 'wp-ultimo'),
	__('Pascoag', 'wp-ultimo'),
	__('Pawtucket', 'wp-ultimo'),
	__('Portsmouth', 'wp-ultimo'),
	__('Providence', 'wp-ultimo'),
	__('Providence County', 'wp-ultimo'),
	__('Smithfield', 'wp-ultimo'),
	__('South Kingstown', 'wp-ultimo'),
	__('Tiverton', 'wp-ultimo'),
	__('Valley Falls', 'wp-ultimo'),
	__('Wakefield-Peacedale', 'wp-ultimo'),
	__('Warren', 'wp-ultimo'),
	__('Warwick', 'wp-ultimo'),
	__('Washington County', 'wp-ultimo'),
	__('West Greenwich', 'wp-ultimo'),
	__('West Warwick', 'wp-ultimo'),
	__('Westerly', 'wp-ultimo'),
	__('Woonsocket', 'wp-ultimo'),
);
