<?php
/**
 * State City List for VT - US.
 *
 * City count: 96
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for VT - US.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Addison', 'wp-ultimo'),
	__('Addison County', 'wp-ultimo'),
	__('Arlington', 'wp-ultimo'),
	__('Barre', 'wp-ultimo'),
	__('Bellows Falls', 'wp-ultimo'),
	__('Bennington', 'wp-ultimo'),
	__('Bennington County', 'wp-ultimo'),
	__('Brandon', 'wp-ultimo'),
	__('Brattleboro', 'wp-ultimo'),
	__('Bridport', 'wp-ultimo'),
	__('Bristol', 'wp-ultimo'),
	__('Burlington', 'wp-ultimo'),
	__('Caledonia County', 'wp-ultimo'),
	__('Castleton', 'wp-ultimo'),
	__('Charlotte', 'wp-ultimo'),
	__('Chelsea', 'wp-ultimo'),
	__('Chester', 'wp-ultimo'),
	__('Chittenden', 'wp-ultimo'),
	__('Chittenden County', 'wp-ultimo'),
	__('Clarendon', 'wp-ultimo'),
	__('Colchester', 'wp-ultimo'),
	__('Danby', 'wp-ultimo'),
	__('Dover', 'wp-ultimo'),
	__('Enosburg Falls', 'wp-ultimo'),
	__('Essex County', 'wp-ultimo'),
	__('Essex Junction', 'wp-ultimo'),
	__('Fair Haven', 'wp-ultimo'),
	__('Ferrisburgh', 'wp-ultimo'),
	__('Franklin County', 'wp-ultimo'),
	__('Grand Isle County', 'wp-ultimo'),
	__('Guildhall', 'wp-ultimo'),
	__('Hardwick', 'wp-ultimo'),
	__('Hartford', 'wp-ultimo'),
	__('Hinesburg', 'wp-ultimo'),
	__('Hyde Park', 'wp-ultimo'),
	__('Jamaica', 'wp-ultimo'),
	__('Jericho', 'wp-ultimo'),
	__('Johnson', 'wp-ultimo'),
	__('Lamoille County', 'wp-ultimo'),
	__('Leicester', 'wp-ultimo'),
	__('Lincoln', 'wp-ultimo'),
	__('Londonderry', 'wp-ultimo'),
	__('Lunenburg', 'wp-ultimo'),
	__('Lyndon', 'wp-ultimo'),
	__('Lyndonville', 'wp-ultimo'),
	__('Manchester Center', 'wp-ultimo'),
	__('Mendon', 'wp-ultimo'),
	__('Middlebury (village)', 'wp-ultimo'),
	__('Milton', 'wp-ultimo'),
	__('Montgomery', 'wp-ultimo'),
	__('Montpelier', 'wp-ultimo'),
	__('Moretown', 'wp-ultimo'),
	__('Morristown', 'wp-ultimo'),
	__('Morrisville', 'wp-ultimo'),
	__('Mount Holly', 'wp-ultimo'),
	__('Newfane', 'wp-ultimo'),
	__('Newport', 'wp-ultimo'),
	__('North Bennington', 'wp-ultimo'),
	__('North Hero', 'wp-ultimo'),
	__('Northfield', 'wp-ultimo'),
	__('Orange County', 'wp-ultimo'),
	__('Orleans County', 'wp-ultimo'),
	__('Pawlet', 'wp-ultimo'),
	__('Poultney', 'wp-ultimo'),
	__('Pownal', 'wp-ultimo'),
	__('Randolph', 'wp-ultimo'),
	__('Richford', 'wp-ultimo'),
	__('Rockingham', 'wp-ultimo'),
	__('Rutland', 'wp-ultimo'),
	__('Rutland County', 'wp-ultimo'),
	__('Saint Albans', 'wp-ultimo'),
	__('Saint Johnsbury', 'wp-ultimo'),
	__('Salisbury', 'wp-ultimo'),
	__('South Barre', 'wp-ultimo'),
	__('South Burlington', 'wp-ultimo'),
	__('Springfield', 'wp-ultimo'),
	__('St Johnsbury', 'wp-ultimo'),
	__('Starksboro', 'wp-ultimo'),
	__('Stowe', 'wp-ultimo'),
	__('Swanton', 'wp-ultimo'),
	__('Townshend', 'wp-ultimo'),
	__('Vergennes', 'wp-ultimo'),
	__('Washington', 'wp-ultimo'),
	__('Washington County', 'wp-ultimo'),
	__('Waterbury', 'wp-ultimo'),
	__('West Brattleboro', 'wp-ultimo'),
	__('West Rutland', 'wp-ultimo'),
	__('White River Junction', 'wp-ultimo'),
	__('Wilder', 'wp-ultimo'),
	__('Williamstown', 'wp-ultimo'),
	__('Williston', 'wp-ultimo'),
	__('Windham County', 'wp-ultimo'),
	__('Windsor', 'wp-ultimo'),
	__('Windsor County', 'wp-ultimo'),
	__('Winooski', 'wp-ultimo'),
	__('Woodstock', 'wp-ultimo'),
);
