<?php
/**
 * State City List for WY - US.
 *
 * City count: 80
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for WY - US.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Afton', 'wp-ultimo'),
	__('Albany County', 'wp-ultimo'),
	__('Antelope Valley-Crestview', 'wp-ultimo'),
	__('Arapahoe', 'wp-ultimo'),
	__('Bar Nunn', 'wp-ultimo'),
	__('Basin', 'wp-ultimo'),
	__('Big Horn County', 'wp-ultimo'),
	__('Buffalo', 'wp-ultimo'),
	__('Campbell County', 'wp-ultimo'),
	__('Carbon County', 'wp-ultimo'),
	__('Casper', 'wp-ultimo'),
	__('Cheyenne', 'wp-ultimo'),
	__('Cody', 'wp-ultimo'),
	__('Converse County', 'wp-ultimo'),
	__('Crook County', 'wp-ultimo'),
	__('Douglas', 'wp-ultimo'),
	__('Ethete', 'wp-ultimo'),
	__('Evanston', 'wp-ultimo'),
	__('Evansville', 'wp-ultimo'),
	__('Fort Washakie', 'wp-ultimo'),
	__('Fox Farm-College', 'wp-ultimo'),
	__('Fremont County', 'wp-ultimo'),
	__('Gillette', 'wp-ultimo'),
	__('Glenrock', 'wp-ultimo'),
	__('Goshen County', 'wp-ultimo'),
	__('Green River', 'wp-ultimo'),
	__('Greybull', 'wp-ultimo'),
	__('Guernsey', 'wp-ultimo'),
	__('Hoback', 'wp-ultimo'),
	__('Hot Springs County', 'wp-ultimo'),
	__('Jackson', 'wp-ultimo'),
	__('Johnson County', 'wp-ultimo'),
	__('Kemmerer', 'wp-ultimo'),
	__('Lander', 'wp-ultimo'),
	__('Laramie', 'wp-ultimo'),
	__('Laramie County', 'wp-ultimo'),
	__('Lincoln County', 'wp-ultimo'),
	__('Lovell', 'wp-ultimo'),
	__('Lusk', 'wp-ultimo'),
	__('Lyman', 'wp-ultimo'),
	__('Marbleton', 'wp-ultimo'),
	__('Mills', 'wp-ultimo'),
	__('Moorcroft', 'wp-ultimo'),
	__('Moose Wilson Road', 'wp-ultimo'),
	__('Mountain View', 'wp-ultimo'),
	__('Natrona County', 'wp-ultimo'),
	__('Newcastle', 'wp-ultimo'),
	__('Niobrara County', 'wp-ultimo'),
	__('North Rock Springs', 'wp-ultimo'),
	__('Park County', 'wp-ultimo'),
	__('Pine Bluffs', 'wp-ultimo'),
	__('Pinedale', 'wp-ultimo'),
	__('Platte County', 'wp-ultimo'),
	__('Powell', 'wp-ultimo'),
	__('Rafter J Ranch', 'wp-ultimo'),
	__('Ranchettes', 'wp-ultimo'),
	__('Rawlins', 'wp-ultimo'),
	__('Riverton', 'wp-ultimo'),
	__('Rock Springs', 'wp-ultimo'),
	__('Saratoga', 'wp-ultimo'),
	__('Sheridan', 'wp-ultimo'),
	__('Sheridan County', 'wp-ultimo'),
	__('Sleepy Hollow', 'wp-ultimo'),
	__('South Greeley', 'wp-ultimo'),
	__('South Park', 'wp-ultimo'),
	__('Star Valley Ranch', 'wp-ultimo'),
	__('Sublette County', 'wp-ultimo'),
	__('Sundance', 'wp-ultimo'),
	__('Sweetwater County', 'wp-ultimo'),
	__('Teton County', 'wp-ultimo'),
	__('Thermopolis', 'wp-ultimo'),
	__('Torrington', 'wp-ultimo'),
	__('Uinta County', 'wp-ultimo'),
	__('Upton', 'wp-ultimo'),
	__('Washakie County', 'wp-ultimo'),
	__('Weston County', 'wp-ultimo'),
	__('Wheatland', 'wp-ultimo'),
	__('Wilson', 'wp-ultimo'),
	__('Worland', 'wp-ultimo'),
	__('Wright', 'wp-ultimo'),
);
