<?php
/**
 * State City List for AD - RU.
 *
 * City count: 30
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for AD - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Abadzekhskaya', 'wp-ultimo'),
	__('Adygeysk', 'wp-ultimo'),
	__('Adygeysk Republican Urban Okrug', 'wp-ultimo'),
	__('Beloye', 'wp-ultimo'),
	__('Blechepsin', 'wp-ultimo'),
	__('Dondukovskaya', 'wp-ultimo'),
	__('Enem', 'wp-ultimo'),
	__('Giaginskaya', 'wp-ultimo'),
	__('Giaginskiy Rayon', 'wp-ultimo'),
	__('Kamennomostskiy', 'wp-ultimo'),
	__('Khanskaya', 'wp-ultimo'),
	__('Khatukay', 'wp-ultimo'),
	__('Khodz’', 'wp-ultimo'),
	__('Koshekhabl’', 'wp-ultimo'),
	__('Koshekhabl’skiy Rayon', 'wp-ultimo'),
	__('Krasnogvardeyskiy Rayon', 'wp-ultimo'),
	__('Krasnogvardeyskoye', 'wp-ultimo'),
	__('Kuzhorskaya', 'wp-ultimo'),
	__('Maykop', 'wp-ultimo'),
	__('Maykop Republican Urban Okrug', 'wp-ultimo'),
	__('Maykopskiy Rayon', 'wp-ultimo'),
	__('Natyrbovo', 'wp-ultimo'),
	__('Ponezhukay', 'wp-ultimo'),
	__('Shovgenovskiy', 'wp-ultimo'),
	__('Shovgenovskiy Rayon', 'wp-ultimo'),
	__('Takhtamukay', 'wp-ultimo'),
	__('Takhtamukayskiy Rayon', 'wp-ultimo'),
	__('Teuchezhskiy Rayon', 'wp-ultimo'),
	__('Tlyustenkhabl’', 'wp-ultimo'),
	__('Yablonovskiy', 'wp-ultimo'),
);
