<?php
/**
 * State City List for AL - RU.
 *
 * City count: 25
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for AL - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Aktash', 'wp-ultimo'),
	__('Artybash', 'wp-ultimo'),
	__('Belyashi', 'wp-ultimo'),
	__('Chemal', 'wp-ultimo'),
	__('Cherga', 'wp-ultimo'),
	__('Choya', 'wp-ultimo'),
	__('Elekmonar', 'wp-ultimo'),
	__('Gorno-Altaysk', 'wp-ultimo'),
	__('Inya', 'wp-ultimo'),
	__('Iogach', 'wp-ultimo'),
	__('Kosh-Agach', 'wp-ultimo'),
	__('Manzherok', 'wp-ultimo'),
	__('Mayma', 'wp-ultimo'),
	__('Mayminskiy Rayon', 'wp-ultimo'),
	__('Onguday', 'wp-ultimo'),
	__('Ongudayskiy Rayon', 'wp-ultimo'),
	__('Shebalino', 'wp-ultimo'),
	__('Shebalinskiy Rayon', 'wp-ultimo'),
	__('Souzga', 'wp-ultimo'),
	__('Tashanta', 'wp-ultimo'),
	__('Turochak', 'wp-ultimo'),
	__('Ust’-Kan', 'wp-ultimo'),
	__('Ust’-Koksa', 'wp-ultimo'),
	__('Ust’-Koksinskiy Rayon', 'wp-ultimo'),
	__('Ust’-Ulagan', 'wp-ultimo'),
);
