<?php
/**
 * State City List for ARK - RU.
 *
 * City count: 71
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for ARK - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Arkhangel’sk', 'wp-ultimo'),
	__('Berëznik', 'wp-ultimo'),
	__('Cheremushskiy', 'wp-ultimo'),
	__('Dvinskoy', 'wp-ultimo'),
	__('Ileza', 'wp-ultimo'),
	__('Il’insko-Podomskoye', 'wp-ultimo'),
	__('Isakogorka', 'wp-ultimo'),
	__('Kamenka', 'wp-ultimo'),
	__('Kargopol’', 'wp-ultimo'),
	__('Kargopol’skiy Rayon', 'wp-ultimo'),
	__('Karpogory', 'wp-ultimo'),
	__('Katunino', 'wp-ultimo'),
	__('Kharitonovo', 'wp-ultimo'),
	__('Kholmogorskiy Rayon', 'wp-ultimo'),
	__('Kholmogory', 'wp-ultimo'),
	__('Kizema', 'wp-ultimo'),
	__('Kodino', 'wp-ultimo'),
	__('Konosha', 'wp-ultimo'),
	__('Konëvo', 'wp-ultimo'),
	__('Koryazhma', 'wp-ultimo'),
	__('Kotlas', 'wp-ultimo'),
	__('Kotlasskiy Rayon', 'wp-ultimo'),
	__('Krasnoborsk', 'wp-ultimo'),
	__('Kuloy', 'wp-ultimo'),
	__('Lenskiy Rayon', 'wp-ultimo'),
	__('Leshukonskiy Rayon', 'wp-ultimo'),
	__('Leshukonskoye', 'wp-ultimo'),
	__('Loyga', 'wp-ultimo'),
	__('Lukovetskiy', 'wp-ultimo'),
	__('Mezenskiy Rayon', 'wp-ultimo'),
	__('Mezen’', 'wp-ultimo'),
	__('Mirnyy', 'wp-ultimo'),
	__('Novodvinsk', 'wp-ultimo'),
	__('Nyandoma', 'wp-ultimo'),
	__('Nyandomskiy Rayon', 'wp-ultimo'),
	__('Oksovskiy', 'wp-ultimo'),
	__('Onega', 'wp-ultimo'),
	__('Onezhskiy Rayon', 'wp-ultimo'),
	__('Pinega', 'wp-ultimo'),
	__('Pinezhskiy Rayon', 'wp-ultimo'),
	__('Plesetsk', 'wp-ultimo'),
	__('Podyuga', 'wp-ultimo'),
	__('Primorskiy Rayon', 'wp-ultimo'),
	__('Privodino', 'wp-ultimo'),
	__('Puksoozero', 'wp-ultimo'),
	__('Rochegda', 'wp-ultimo'),
	__('Samoded', 'wp-ultimo'),
	__('Severodvinsk', 'wp-ultimo'),
	__('Shalakusha', 'wp-ultimo'),
	__('Shangaly', 'wp-ultimo'),
	__('Shenkursk', 'wp-ultimo'),
	__('Shenkurskiy Rayon', 'wp-ultimo'),
	__('Shipitsyno', 'wp-ultimo'),
	__('Solginskiy', 'wp-ultimo'),
	__('Sol’vychegodsk', 'wp-ultimo'),
	__('Udimskiy', 'wp-ultimo'),
	__('Urdoma', 'wp-ultimo'),
	__('Ust’-Shonosha', 'wp-ultimo'),
	__('Ust’yanskiy Rayon', 'wp-ultimo'),
	__('Uyemskiy', 'wp-ultimo'),
	__('Vas’kovo', 'wp-ultimo'),
	__('Vel’sk', 'wp-ultimo'),
	__('Vel’skiy Rayon', 'wp-ultimo'),
	__('Verkhnyaya Toyma', 'wp-ultimo'),
	__('Voloshka', 'wp-ultimo'),
	__('Vychegodskiy', 'wp-ultimo'),
	__('Yagry', 'wp-ultimo'),
	__('Yarensk', 'wp-ultimo'),
	__('Yemetsk', 'wp-ultimo'),
	__('Yemtsa', 'wp-ultimo'),
	__('Yertsevo', 'wp-ultimo'),
);
