<?php
/**
 * State City List for AST - RU.
 *
 * City count: 40
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for AST - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Akhtubinsk', 'wp-ultimo'),
	__('Akhtubinskiy Rayon', 'wp-ultimo'),
	__('Aksarayskiy', 'wp-ultimo'),
	__('Astrakhan', 'wp-ultimo'),
	__('Chyorny Yar', 'wp-ultimo'),
	__('Ikryanoye', 'wp-ultimo'),
	__('Kamyzyak', 'wp-ultimo'),
	__('Kapustin Yar', 'wp-ultimo'),
	__('Karalat', 'wp-ultimo'),
	__('Kharabali', 'wp-ultimo'),
	__('Kirovskiy', 'wp-ultimo'),
	__('Krasnoyarskiy Rayon', 'wp-ultimo'),
	__('Krasnyy Yar', 'wp-ultimo'),
	__('Krasnyye Barrikady', 'wp-ultimo'),
	__('Liman', 'wp-ultimo'),
	__('Limanskiy Rayon', 'wp-ultimo'),
	__('Marfino', 'wp-ultimo'),
	__('Mumra', 'wp-ultimo'),
	__('Nachalovo', 'wp-ultimo'),
	__('Narimanov', 'wp-ultimo'),
	__('Nizhniy Baskunchak', 'wp-ultimo'),
	__('Oranzherei', 'wp-ultimo'),
	__('Poldnëvoye', 'wp-ultimo'),
	__('Privolzhskiy Rayon', 'wp-ultimo'),
	__('Sasykoli', 'wp-ultimo'),
	__('Sizyy Bugor', 'wp-ultimo'),
	__('Solyanka', 'wp-ultimo'),
	__('Starokucherganovka', 'wp-ultimo'),
	__('Tambovka', 'wp-ultimo'),
	__('Trudfront', 'wp-ultimo'),
	__('Tumak', 'wp-ultimo'),
	__('Uvary', 'wp-ultimo'),
	__('Verkhniy Baskunchak', 'wp-ultimo'),
	__('Volgo-Kaspiyskiy', 'wp-ultimo'),
	__('Volodarskiy', 'wp-ultimo'),
	__('Yaksatovo', 'wp-ultimo'),
	__('Yandyki', 'wp-ultimo'),
	__('Yenotayevka', 'wp-ultimo'),
	__('Zenzeli', 'wp-ultimo'),
	__('Znamensk', 'wp-ultimo'),
);
