<?php
/**
 * State City List for BEL - RU.
 *
 * City count: 56
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for BEL - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Alekseyevka', 'wp-ultimo'),
	__('Bekhteyevka', 'wp-ultimo'),
	__('Belgorod', 'wp-ultimo'),
	__('Belgorodskiy Rayon', 'wp-ultimo'),
	__('Bessonovka', 'wp-ultimo'),
	__('Borisovka', 'wp-ultimo'),
	__('Borisovskiy Rayon', 'wp-ultimo'),
	__('Chernyanka', 'wp-ultimo'),
	__('Chernyanskiy Rayon', 'wp-ultimo'),
	__('Golovchino', 'wp-ultimo'),
	__('Grayvoron', 'wp-ultimo'),
	__('Grayvoronskiy Rayon', 'wp-ultimo'),
	__('Gubkin', 'wp-ultimo'),
	__('Ilovka', 'wp-ultimo'),
	__('Ivnya', 'wp-ultimo'),
	__('Ivnyanskiy Rayon', 'wp-ultimo'),
	__('Korocha', 'wp-ultimo'),
	__('Korochanskiy Rayon', 'wp-ultimo'),
	__('Krasnaya Yaruga', 'wp-ultimo'),
	__('Krasnenskiy Rayon', 'wp-ultimo'),
	__('Krasnogvardeyskiy Rayon', 'wp-ultimo'),
	__('Krasnogvardeyskoye', 'wp-ultimo'),
	__('Krasnoyaruzhskiy Rayon', 'wp-ultimo'),
	__('Krasnoye', 'wp-ultimo'),
	__('Livenka', 'wp-ultimo'),
	__('Maslova Pristan’', 'wp-ultimo'),
	__('Mayskiy', 'wp-ultimo'),
	__('Novaya Tavolzhanka', 'wp-ultimo'),
	__('Novooskol’skiy Rayon', 'wp-ultimo'),
	__('Novyy Oskol', 'wp-ultimo'),
	__('Prokhorovka', 'wp-ultimo'),
	__('Prokhorovskiy Rayon', 'wp-ultimo'),
	__('Proletarskiy', 'wp-ultimo'),
	__('Pyatnitskoye', 'wp-ultimo'),
	__('Rakitnoye', 'wp-ultimo'),
	__('Rakityanskiy Rayon', 'wp-ultimo'),
	__('Razumnoye', 'wp-ultimo'),
	__('Rogovatoye', 'wp-ultimo'),
	__('Roven’skiy Rayon', 'wp-ultimo'),
	__('Severnyy', 'wp-ultimo'),
	__('Shebekino', 'wp-ultimo'),
	__('Shebekinskiy Rayon', 'wp-ultimo'),
	__('Skorodnoye', 'wp-ultimo'),
	__('Staryy Oskol', 'wp-ultimo'),
	__('Stroitel’', 'wp-ultimo'),
	__('Tomarovka', 'wp-ultimo'),
	__('Troitskiy', 'wp-ultimo'),
	__('Urazovo', 'wp-ultimo'),
	__('Valuyki', 'wp-ultimo'),
	__('Valuyskiy Rayon', 'wp-ultimo'),
	__('Veydelevka', 'wp-ultimo'),
	__('Volokonovka', 'wp-ultimo'),
	__('Volokonovskiy Rayon', 'wp-ultimo'),
	__('Yakovlevo', 'wp-ultimo'),
	__('Yakovlevskiy Rayon', 'wp-ultimo'),
	__('Zasosna', 'wp-ultimo'),
);
