<?php
/**
 * State City List for BRY - RU.
 *
 * City count: 83
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for BRY - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Altukhovo', 'wp-ultimo'),
	__('Ardon’', 'wp-ultimo'),
	__('Belyye Berega', 'wp-ultimo'),
	__('Brasovskiy Rayon', 'wp-ultimo'),
	__('Bryansk', 'wp-ultimo'),
	__('Bryanskiy Rayon', 'wp-ultimo'),
	__('Bytosh’', 'wp-ultimo'),
	__('Churovichi', 'wp-ultimo'),
	__('Dobrun’', 'wp-ultimo'),
	__('Dubrovka', 'wp-ultimo'),
	__('Dubrovskiy Rayon', 'wp-ultimo'),
	__('Dyat’kovo', 'wp-ultimo'),
	__('Dyat’kovskiy Rayon', 'wp-ultimo'),
	__('Glinishchevo', 'wp-ultimo'),
	__('Gordeyevka', 'wp-ultimo'),
	__('Gordeyevskiy Rayon', 'wp-ultimo'),
	__('Gorod Bryansk', 'wp-ultimo'),
	__('Gorod Dyat’kovo', 'wp-ultimo'),
	__('Ivanovka', 'wp-ultimo'),
	__('Ivot', 'wp-ultimo'),
	__('Karachev', 'wp-ultimo'),
	__('Kletnya', 'wp-ultimo'),
	__('Kletnyanskiy Rayon', 'wp-ultimo'),
	__('Klimovo', 'wp-ultimo'),
	__('Klimovskiy Rayon', 'wp-ultimo'),
	__('Klintsovskiy Rayon', 'wp-ultimo'),
	__('Klintsy', 'wp-ultimo'),
	__('Kokino', 'wp-ultimo'),
	__('Kokorevka', 'wp-ultimo'),
	__('Komarichi', 'wp-ultimo'),
	__('Komarichskiy Rayon', 'wp-ultimo'),
	__('Korzhovka-Golubovka', 'wp-ultimo'),
	__('Krasnaya Gora', 'wp-ultimo'),
	__('Krasnogorskiy Rayon', 'wp-ultimo'),
	__('Lokot’', 'wp-ultimo'),
	__('Lopandino', 'wp-ultimo'),
	__('Lyubokhna', 'wp-ultimo'),
	__('Lyubovsho', 'wp-ultimo'),
	__('Mglin', 'wp-ultimo'),
	__('Mglinskiy Rayon', 'wp-ultimo'),
	__('Navlinskiy Rayon', 'wp-ultimo'),
	__('Navlya', 'wp-ultimo'),
	__('Net’inka', 'wp-ultimo'),
	__('Novozybkov', 'wp-ultimo'),
	__('Novozybkovskiy Rayon', 'wp-ultimo'),
	__('Novyy Ropsk', 'wp-ultimo'),
	__('Pochep', 'wp-ultimo'),
	__('Pochepskiy Rayon', 'wp-ultimo'),
	__('Pogar', 'wp-ultimo'),
	__('Pogarskiy Rayon', 'wp-ultimo'),
	__('Putëvka', 'wp-ultimo'),
	__('Raditsa-Krylovka', 'wp-ultimo'),
	__('Rognedino', 'wp-ultimo'),
	__('Rognedinskiy Rayon', 'wp-ultimo'),
	__('Rzhanitsa', 'wp-ultimo'),
	__('Sachkovichi', 'wp-ultimo'),
	__('Sel’tso', 'wp-ultimo'),
	__('Seshcha', 'wp-ultimo'),
	__('Sevsk', 'wp-ultimo'),
	__('Sevskiy Rayon', 'wp-ultimo'),
	__('Starodub', 'wp-ultimo'),
	__('Starodubskiy Rayon', 'wp-ultimo'),
	__('Star’', 'wp-ultimo'),
	__('Suponevo', 'wp-ultimo'),
	__('Surazh', 'wp-ultimo'),
	__('Surazhskiy Rayon', 'wp-ultimo'),
	__('Suzemskiy Rayon', 'wp-ultimo'),
	__('Suzëmka', 'wp-ultimo'),
	__('Sven’', 'wp-ultimo'),
	__('Trubchevsk', 'wp-ultimo'),
	__('Trubchevskiy Rayon', 'wp-ultimo'),
	__('Unecha', 'wp-ultimo'),
	__('Unechskiy Rayon', 'wp-ultimo'),
	__('Vygonichi', 'wp-ultimo'),
	__('Vygonichskiy Rayon', 'wp-ultimo'),
	__('Vyshkov', 'wp-ultimo'),
	__('Zamishevo', 'wp-ultimo'),
	__('Zaymishche', 'wp-ultimo'),
	__('Zhiryatino', 'wp-ultimo'),
	__('Zhiryatinskiy Rayon', 'wp-ultimo'),
	__('Zhukovka', 'wp-ultimo'),
	__('Zhukovskiy Rayon', 'wp-ultimo'),
	__('Zlynka', 'wp-ultimo'),
);
