<?php
/**
 * State City List for BU - RU.
 *
 * City count: 66
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for BU - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Babushkin', 'wp-ultimo'),
	__('Bagdarin', 'wp-ultimo'),
	__('Barguzin', 'wp-ultimo'),
	__('Bayangol', 'wp-ultimo'),
	__('Bichura', 'wp-ultimo'),
	__('Bol’shoy Kunaley', 'wp-ultimo'),
	__('Dzhida', 'wp-ultimo'),
	__('Gusinoozyorsk', 'wp-ultimo'),
	__('Gusinoye Ozero', 'wp-ultimo'),
	__('Il’inka', 'wp-ultimo'),
	__('Il’ka', 'wp-ultimo'),
	__('Istok', 'wp-ultimo'),
	__('Ivolginsk', 'wp-ultimo'),
	__('Ivolginskiy Rayon', 'wp-ultimo'),
	__('Kabansk', 'wp-ultimo'),
	__('Kholtoson', 'wp-ultimo'),
	__('Khonkholoy', 'wp-ultimo'),
	__('Khorinsk', 'wp-ultimo'),
	__('Kichera', 'wp-ultimo'),
	__('Kizhinga', 'wp-ultimo'),
	__('Kudara-Somon', 'wp-ultimo'),
	__('Kurumkan', 'wp-ultimo'),
	__('Kyakhta', 'wp-ultimo'),
	__('Kyren', 'wp-ultimo'),
	__('Mukhorshibirskiy Rayon', 'wp-ultimo'),
	__('Mukhorshibir’', 'wp-ultimo'),
	__('Muyskiy Rayon', 'wp-ultimo'),
	__('Naushki', 'wp-ultimo'),
	__('Nikolayevskiy', 'wp-ultimo'),
	__('Nikol’sk', 'wp-ultimo'),
	__('Nizhneangarsk', 'wp-ultimo'),
	__('Nizhniy Sayantuy', 'wp-ultimo'),
	__('Novaya Bryan’', 'wp-ultimo'),
	__('Novokizhinginsk', 'wp-ultimo'),
	__('Novyy Uoyan', 'wp-ultimo'),
	__('Novyy Zagan', 'wp-ultimo'),
	__('Okino-Klyuchi', 'wp-ultimo'),
	__('Okinskiy Rayon', 'wp-ultimo'),
	__('Onokhoy', 'wp-ultimo'),
	__('Orlik', 'wp-ultimo'),
	__('Petropavlovka', 'wp-ultimo'),
	__('Pribaykal’skiy Rayon', 'wp-ultimo'),
	__('Rechka-Vydrino', 'wp-ultimo'),
	__('Sagan-Nur', 'wp-ultimo'),
	__('Selenduma', 'wp-ultimo'),
	__('Selenginskiy Rayon', 'wp-ultimo'),
	__('Severo-Baykal’skiy Rayon', 'wp-ultimo'),
	__('Severobaykal’sk', 'wp-ultimo'),
	__('Severomuysk', 'wp-ultimo'),
	__('Sharalday', 'wp-ultimo'),
	__('Sokol', 'wp-ultimo'),
	__('Sosnovo-Ozerskoye', 'wp-ultimo'),
	__('Sotnikovo', 'wp-ultimo'),
	__('Taksimo', 'wp-ultimo'),
	__('Tankhoy', 'wp-ultimo'),
	__('Tarbagatay', 'wp-ultimo'),
	__('Tataurovo', 'wp-ultimo'),
	__('Turka', 'wp-ultimo'),
	__('Turuntayevo', 'wp-ultimo'),
	__('Ulan-Ude', 'wp-ultimo'),
	__('Ust’-Barguzin', 'wp-ultimo'),
	__('Vydrino', 'wp-ultimo'),
	__('Zaigrayevo', 'wp-ultimo'),
	__('Zakamensk', 'wp-ultimo'),
	__('Zarechnyy', 'wp-ultimo'),
	__('Zhemchug', 'wp-ultimo'),
);
