<?php
/**
 * State City List for CE - RU.
 *
 * City count: 85
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for CE - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Achkhoy-Martan', 'wp-ultimo'),
	__('Achkhoy-Martanovskiy Rayon', 'wp-ultimo'),
	__('Alkhan-Kala', 'wp-ultimo'),
	__('Alkhan-Yurt', 'wp-ultimo'),
	__('Alkhazurovo', 'wp-ultimo'),
	__('Alleroy', 'wp-ultimo'),
	__('Alpatovo', 'wp-ultimo'),
	__('Argun', 'wp-ultimo'),
	__('Assinovskaya', 'wp-ultimo'),
	__('Avtury', 'wp-ultimo'),
	__('Bachi-Yurt', 'wp-ultimo'),
	__('Bamut', 'wp-ultimo'),
	__('Belgatoy', 'wp-ultimo'),
	__('Benoy-Yurt', 'wp-ultimo'),
	__('Borzoy', 'wp-ultimo'),
	__('Chechen-Aul', 'wp-ultimo'),
	__('Chiri-Yurt', 'wp-ultimo'),
	__('Duba-Yurt', 'wp-ultimo'),
	__('Dyshne-Vedeno', 'wp-ultimo'),
	__('Dzhalka', 'wp-ultimo'),
	__('Elin-Yurt', 'wp-ultimo'),
	__('Engel’-Yurt', 'wp-ultimo'),
	__('Gekhi', 'wp-ultimo'),
	__('Germenchuk', 'wp-ultimo'),
	__('Gerzel’-Aul', 'wp-ultimo'),
	__('Goragorskiy', 'wp-ultimo'),
	__('Goyty', 'wp-ultimo'),
	__('Grebenskaya', 'wp-ultimo'),
	__('Groznenskiy Rayon', 'wp-ultimo'),
	__('Groznyy', 'wp-ultimo'),
	__('Gudermes', 'wp-ultimo'),
	__('Gudermesskiy Rayon', 'wp-ultimo'),
	__('Ilaskhan-Yurt', 'wp-ultimo'),
	__('Ishcherskaya', 'wp-ultimo'),
	__('Ishkhoy-Yurt', 'wp-ultimo'),
	__('Itum-Kali', 'wp-ultimo'),
	__('Itum-Kalinskiy Rayon', 'wp-ultimo'),
	__('Kalinovskaya', 'wp-ultimo'),
	__('Kargalinskaya', 'wp-ultimo'),
	__('Katyr-Yurt', 'wp-ultimo'),
	__('Khambi-Irze', 'wp-ultimo'),
	__('Khankala', 'wp-ultimo'),
	__('Kulary', 'wp-ultimo'),
	__('Kurchaloy', 'wp-ultimo'),
	__('Lakha Nëvre', 'wp-ultimo'),
	__('Lakkha Nëvre', 'wp-ultimo'),
	__('Martan-Chu', 'wp-ultimo'),
	__('Mayrtup', 'wp-ultimo'),
	__('Mesker-Yurt', 'wp-ultimo'),
	__('Nadterechnyy Rayon', 'wp-ultimo'),
	__('Naurskaya', 'wp-ultimo'),
	__('Naurskiy Rayon', 'wp-ultimo'),
	__('Nogamerzin-Yurt', 'wp-ultimo'),
	__('Novyye Atagi', 'wp-ultimo'),
	__('Nozhay-Yurt', 'wp-ultimo'),
	__('Nozhay-Yurtovskiy Rayon', 'wp-ultimo'),
	__('Oyskhara', 'wp-ultimo'),
	__('Pervomayskaya', 'wp-ultimo'),
	__('Petropavlovskaya', 'wp-ultimo'),
	__('Prigorodnoye', 'wp-ultimo'),
	__('Roshni-Chu', 'wp-ultimo'),
	__('Samashki', 'wp-ultimo'),
	__('Sernovodsk', 'wp-ultimo'),
	__('Serzhen’-Yurt', 'wp-ultimo'),
	__('Shaami-Yurt', 'wp-ultimo'),
	__('Shalazhi', 'wp-ultimo'),
	__('Shali', 'wp-ultimo'),
	__('Shalinskiy Rayon', 'wp-ultimo'),
	__('Shatoy', 'wp-ultimo'),
	__('Shelkovskiy Rayon', 'wp-ultimo'),
	__('Shëlkovskaya', 'wp-ultimo'),
	__('Staraya Sunzha', 'wp-ultimo'),
	__('Staryye Atagi', 'wp-ultimo'),
	__('Tolstoy-Yurt', 'wp-ultimo'),
	__('Tsentoroy', 'wp-ultimo'),
	__('Tsotsin-Yurt', 'wp-ultimo'),
	__('Urus-Martan', 'wp-ultimo'),
	__('Urus-Martanovskiy Rayon', 'wp-ultimo'),
	__('Valerik', 'wp-ultimo'),
	__('Vedeno', 'wp-ultimo'),
	__('Vedenskiy Rayon', 'wp-ultimo'),
	__('Yalkhoy-Mokhk', 'wp-ultimo'),
	__('Zakan-Yurt', 'wp-ultimo'),
	__('Zandak', 'wp-ultimo'),
	__('Znamenskoye', 'wp-ultimo'),
);
