<?php
/**
 * State City List for CHE - RU.
 *
 * City count: 94
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for CHE - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Agapovka', 'wp-ultimo'),
	__('Agapovskiy Rayon', 'wp-ultimo'),
	__('Argayash', 'wp-ultimo'),
	__('Asha', 'wp-ultimo'),
	__('Ashinskiy Rayon', 'wp-ultimo'),
	__('Bakal', 'wp-ultimo'),
	__('Bazhovo', 'wp-ultimo'),
	__('Berdyaush', 'wp-ultimo'),
	__('Bobrovka', 'wp-ultimo'),
	__('Bredy', 'wp-ultimo'),
	__('Brodokalmak', 'wp-ultimo'),
	__('Chebarkul’', 'wp-ultimo'),
	__('Chebarkul’skiy Rayon', 'wp-ultimo'),
	__('Chelyabinsk', 'wp-ultimo'),
	__('Cheremshanka', 'wp-ultimo'),
	__('Chesma', 'wp-ultimo'),
	__('Dolgoderevenskoye', 'wp-ultimo'),
	__('Fershampenuaz', 'wp-ultimo'),
	__('Gornyak', 'wp-ultimo'),
	__('Gorod Chelyabinsk', 'wp-ultimo'),
	__('Kanashevo', 'wp-ultimo'),
	__('Karabash', 'wp-ultimo'),
	__('Kartalinskiy Rayon', 'wp-ultimo'),
	__('Kartaly', 'wp-ultimo'),
	__('Kasli', 'wp-ultimo'),
	__('Katav-Ivanovsk', 'wp-ultimo'),
	__('Katav-Ivanovskiy Rayon', 'wp-ultimo'),
	__('Kizil’skiy Rayon', 'wp-ultimo'),
	__('Kopeysk', 'wp-ultimo'),
	__('Korkino', 'wp-ultimo'),
	__('Koyelga', 'wp-ultimo'),
	__('Krasnogorskiy', 'wp-ultimo'),
	__('Kropachëvo', 'wp-ultimo'),
	__('Kunashak', 'wp-ultimo'),
	__('Kusa', 'wp-ultimo'),
	__('Kyshtym', 'wp-ultimo'),
	__('Leninsk', 'wp-ultimo'),
	__('Lokomotivnyy', 'wp-ultimo'),
	__('Magnitka', 'wp-ultimo'),
	__('Magnitogorsk', 'wp-ultimo'),
	__('Mezhevoy', 'wp-ultimo'),
	__('Miass', 'wp-ultimo'),
	__('Miasskoye', 'wp-ultimo'),
	__('Muslyumovo', 'wp-ultimo'),
	__('Nagaybakskiy Rayon', 'wp-ultimo'),
	__('Nizhniy Ufaley', 'wp-ultimo'),
	__('Novogornyy', 'wp-ultimo'),
	__('Novosineglazovskiy', 'wp-ultimo'),
	__('Nyazepetrovsk', 'wp-ultimo'),
	__('Nyazepetrovskiy Rayon', 'wp-ultimo'),
	__('Oktyabr’skiy Rayon', 'wp-ultimo'),
	__('Ozersk', 'wp-ultimo'),
	__('Parizh', 'wp-ultimo'),
	__('Plast', 'wp-ultimo'),
	__('Poletayevo', 'wp-ultimo'),
	__('Potanino', 'wp-ultimo'),
	__('Roshchino', 'wp-ultimo'),
	__('Roza', 'wp-ultimo'),
	__('Sargazy', 'wp-ultimo'),
	__('Satka', 'wp-ultimo'),
	__('Satkinskiy Rayon', 'wp-ultimo'),
	__('Selezyan', 'wp-ultimo'),
	__('Sim', 'wp-ultimo'),
	__('Snezhinsk', 'wp-ultimo'),
	__('Sosnovskiy Rayon', 'wp-ultimo'),
	__('Starokamyshinsk', 'wp-ultimo'),
	__('Syrostan', 'wp-ultimo'),
	__('Tayginka', 'wp-ultimo'),
	__('Timiryazevskiy', 'wp-ultimo'),
	__('Troitsk', 'wp-ultimo'),
	__('Trëkhgornyy', 'wp-ultimo'),
	__('Turgoyak', 'wp-ultimo'),
	__('Tyubuk', 'wp-ultimo'),
	__('Ust’-Bagaryak', 'wp-ultimo'),
	__('Ust’-Katav', 'wp-ultimo'),
	__('Uvel’skiy', 'wp-ultimo'),
	__('Uvel’skiy Rayon', 'wp-ultimo'),
	__('Uyskiy Rayon', 'wp-ultimo'),
	__('Uyskoye', 'wp-ultimo'),
	__('Vakhrushevo', 'wp-ultimo'),
	__('Varna', 'wp-ultimo'),
	__('Varnenskiy Rayon', 'wp-ultimo'),
	__('Velikopetrovka', 'wp-ultimo'),
	__('Verkhneural’sk', 'wp-ultimo'),
	__('Verkhniy Ufaley', 'wp-ultimo'),
	__('Vishnëvogorsk', 'wp-ultimo'),
	__('Vyazovaya', 'wp-ultimo'),
	__('Yemanzhelinka', 'wp-ultimo'),
	__('Yemanzhelinsk', 'wp-ultimo'),
	__('Yetkul’', 'wp-ultimo'),
	__('Yuryuzan’', 'wp-ultimo'),
	__('Yuzhnoural’sk', 'wp-ultimo'),
	__('Zheleznodorozhnyy', 'wp-ultimo'),
	__('Zlatoust', 'wp-ultimo'),
);
