<?php
/**
 * State City List for CHU - RU.
 *
 * City count: 10
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for CHU - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Anadyr', 'wp-ultimo'),
	__('Anadyrskiy Rayon', 'wp-ultimo'),
	__('Beringovskiy', 'wp-ultimo'),
	__('Bilibino', 'wp-ultimo'),
	__('Egvekinot', 'wp-ultimo'),
	__('Lavrentiya', 'wp-ultimo'),
	__('Lorino', 'wp-ultimo'),
	__('Pevek', 'wp-ultimo'),
	__('Provideniya', 'wp-ultimo'),
	__('Providenskiy Rayon', 'wp-ultimo'),
);
