<?php
/**
 * State City List for IN - RU.
 *
 * City count: 25
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for IN - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Ali-Yurt', 'wp-ultimo'),
	__('Alkhan-Churt', 'wp-ultimo'),
	__('Dalakovo', 'wp-ultimo'),
	__('Dzhayrakh', 'wp-ultimo'),
	__('Dzhayrakhskiy Rayon', 'wp-ultimo'),
	__('Ekazhevo', 'wp-ultimo'),
	__('Galashki', 'wp-ultimo'),
	__('Kantyshevo', 'wp-ultimo'),
	__('Karabulak', 'wp-ultimo'),
	__('Magas', 'wp-ultimo'),
	__('Malgobek', 'wp-ultimo'),
	__('Malgobekskiy Rayon', 'wp-ultimo'),
	__('Nazranovskiy Rayon', 'wp-ultimo'),
	__('Nazran’', 'wp-ultimo'),
	__('Nesterovskaya', 'wp-ultimo'),
	__('Nizhniye Achaluki', 'wp-ultimo'),
	__('Psedakh', 'wp-ultimo'),
	__('Sagopshi', 'wp-ultimo'),
	__('Staryy Malgobek', 'wp-ultimo'),
	__('Sunzha', 'wp-ultimo'),
	__('Sunzhenskiy Rayon', 'wp-ultimo'),
	__('Surkhakhi', 'wp-ultimo'),
	__('Troitskaya', 'wp-ultimo'),
	__('Verkhniye Achaluki', 'wp-ultimo'),
	__('Voznesenskaya', 'wp-ultimo'),
);
