<?php
/**
 * State City List for IVA - RU.
 *
 * City count: 61
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for IVA - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Arkhipovka', 'wp-ultimo'),
	__('Bogorodskoye', 'wp-ultimo'),
	__('Dulyapino', 'wp-ultimo'),
	__('Furmanov', 'wp-ultimo'),
	__('Gavrilov Posad', 'wp-ultimo'),
	__('Il’inskoye-Khovanskoye', 'wp-ultimo'),
	__('Ivanovo', 'wp-ultimo'),
	__('Ivanovskiy Rayon', 'wp-ultimo'),
	__('Kamenka', 'wp-ultimo'),
	__('Kaminskiy', 'wp-ultimo'),
	__('Kineshemskiy Rayon', 'wp-ultimo'),
	__('Kineshma', 'wp-ultimo'),
	__('Kitovo', 'wp-ultimo'),
	__('Kokhma', 'wp-ultimo'),
	__('Kolobovo', 'wp-ultimo'),
	__('Komsomol’sk', 'wp-ultimo'),
	__('Komsomol’skiy Rayon', 'wp-ultimo'),
	__('Kuznechikha', 'wp-ultimo'),
	__('Lezhnevo', 'wp-ultimo'),
	__('Lezhnevskiy Rayon', 'wp-ultimo'),
	__('Lukh', 'wp-ultimo'),
	__('Lukhskiy Rayon', 'wp-ultimo'),
	__('Markovo', 'wp-ultimo'),
	__('Navoloki', 'wp-ultimo'),
	__('Nerl’', 'wp-ultimo'),
	__('Novo-Talitsy', 'wp-ultimo'),
	__('Novopistsovo', 'wp-ultimo'),
	__('Novoye Leushino', 'wp-ultimo'),
	__('Novyye Gorki', 'wp-ultimo'),
	__('Palekh', 'wp-ultimo'),
	__('Palekhskiy Rayon', 'wp-ultimo'),
	__('Pestyaki', 'wp-ultimo'),
	__('Pestyakovskiy Rayon', 'wp-ultimo'),
	__('Petrovskiy', 'wp-ultimo'),
	__('Pistsovo', 'wp-ultimo'),
	__('Plës', 'wp-ultimo'),
	__('Privolzhsk', 'wp-ultimo'),
	__('Privolzhskiy Rayon', 'wp-ultimo'),
	__('Puchezh', 'wp-ultimo'),
	__('Puchezhskiy Rayon', 'wp-ultimo'),
	__('Rodniki', 'wp-ultimo'),
	__('Rodnikovskiy Rayon', 'wp-ultimo'),
	__('Savino', 'wp-ultimo'),
	__('Savinskiy Rayon', 'wp-ultimo'),
	__('Shuya', 'wp-ultimo'),
	__('Shuyskiy Rayon', 'wp-ultimo'),
	__('Staraya Vichuga', 'wp-ultimo'),
	__('Talitsy', 'wp-ultimo'),
	__('Teykovo', 'wp-ultimo'),
	__('Teykovskiy Rayon', 'wp-ultimo'),
	__('Verkhnelandekhovskiy Rayon', 'wp-ultimo'),
	__('Verkhniy Landekh', 'wp-ultimo'),
	__('Vichuga', 'wp-ultimo'),
	__('Vichugskiy Rayon', 'wp-ultimo'),
	__('Yur’yevets', 'wp-ultimo'),
	__('Yur’yevetskiy Rayon', 'wp-ultimo'),
	__('Yuzha', 'wp-ultimo'),
	__('Yuzhskiy Rayon', 'wp-ultimo'),
	__('Zarechnyy', 'wp-ultimo'),
	__('Zavolzhsk', 'wp-ultimo'),
	__('Zavolzhskiy Rayon', 'wp-ultimo'),
);
