<?php
/**
 * State City List for KAM - RU.
 *
 * City count: 26
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for KAM - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Aleutskiy Rayon', 'wp-ultimo'),
	__('Atlasovo', 'wp-ultimo'),
	__('Bystrinskiy Rayon', 'wp-ultimo'),
	__('Esso', 'wp-ultimo'),
	__('Karaginsky District', 'wp-ultimo'),
	__('Klyuchi', 'wp-ultimo'),
	__('Kozyrëvsk', 'wp-ultimo'),
	__('Mil’kovo', 'wp-ultimo'),
	__('Mil’kovskiy Rayon', 'wp-ultimo'),
	__('Olyutorskiy Rayon', 'wp-ultimo'),
	__('Ossora', 'wp-ultimo'),
	__('Ozernovskiy', 'wp-ultimo'),
	__('Palana', 'wp-ultimo'),
	__('Paratunka', 'wp-ultimo'),
	__('Penzhinskiy Rayon', 'wp-ultimo'),
	__('Petropavlovsk-Kamchatsky', 'wp-ultimo'),
	__('Sobolevskiy Rayon', 'wp-ultimo'),
	__('Tigil’', 'wp-ultimo'),
	__('Tigil’skiy Rayon', 'wp-ultimo'),
	__('Tilichiki', 'wp-ultimo'),
	__('Ust’-Bol’sheretskiy Rayon', 'wp-ultimo'),
	__('Ust’-Kamchatsk Staryy', 'wp-ultimo'),
	__('Ust’-Kamchatskiy Rayon', 'wp-ultimo'),
	__('Vilyuchinsk', 'wp-ultimo'),
	__('Yelizovo', 'wp-ultimo'),
	__('Yelizovskiy Rayon', 'wp-ultimo'),
);
