<?php
/**
 * State City List for KC - RU.
 *
 * City count: 34
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for KC - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Adyge-Khabl’', 'wp-ultimo'),
	__('Ali-Berdukovskiy', 'wp-ultimo'),
	__('Besleney', 'wp-ultimo'),
	__('Cherkessk', 'wp-ultimo'),
	__('Druzhba', 'wp-ultimo'),
	__('Ikon-Khalk', 'wp-ultimo'),
	__('Ispravnaya', 'wp-ultimo'),
	__('Karachayevsk', 'wp-ultimo'),
	__('Karachayevskiy Rayon', 'wp-ultimo'),
	__('Kardonikskaya', 'wp-ultimo'),
	__('Kavkazskiy', 'wp-ultimo'),
	__('Khabez', 'wp-ultimo'),
	__('Krasnyy Kurgan', 'wp-ultimo'),
	__('Kumysh', 'wp-ultimo'),
	__('Kurdzhinovo', 'wp-ultimo'),
	__('Kyzyl-Oktyabr’skiy', 'wp-ultimo'),
	__('Malokarachayevskiy Rayon', 'wp-ultimo'),
	__('Mednogorskiy', 'wp-ultimo'),
	__('Nizhniy Arkhyz', 'wp-ultimo'),
	__('Novyy Karachay', 'wp-ultimo'),
	__('Ordzhonikidzevskiy', 'wp-ultimo'),
	__('Pervomayskoye', 'wp-ultimo'),
	__('Pravokubanskiy', 'wp-ultimo'),
	__('Pregradnaya', 'wp-ultimo'),
	__('Prikubanskiy Rayon', 'wp-ultimo'),
	__('Psyzh', 'wp-ultimo'),
	__('Sary-Tyuz', 'wp-ultimo'),
	__('Storozhevaya', 'wp-ultimo'),
	__('Tereze', 'wp-ultimo'),
	__('Uchkeken', 'wp-ultimo'),
	__('Uchkulan', 'wp-ultimo'),
	__('Udarnyy', 'wp-ultimo'),
	__('Ust’-Dzheguta', 'wp-ultimo'),
	__('Zelenchukskaya', 'wp-ultimo'),
);
