<?php
/**
 * State City List for KGD - RU.
 *
 * City count: 37
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for KGD - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Bagrationovsk', 'wp-ultimo'),
	__('Baltiysk', 'wp-ultimo'),
	__("Bol'shoe Isakovo", 'wp-ultimo'),
	__('Chernyakhovsk', 'wp-ultimo'),
	__('Donskoye', 'wp-ultimo'),
	__('Gur’yevsk', 'wp-ultimo'),
	__('Gusev', 'wp-ultimo'),
	__('Gvardeysk', 'wp-ultimo'),
	__('Kaliningrad', 'wp-ultimo'),
	__('Khrabrovo', 'wp-ultimo'),
	__('Krasnoznamensk', 'wp-ultimo'),
	__('Ladushkin', 'wp-ultimo'),
	__('Maloye Isakovo', 'wp-ultimo'),
	__('Mamonovo', 'wp-ultimo'),
	__('Neman', 'wp-ultimo'),
	__('Nemanskiy Rayon', 'wp-ultimo'),
	__('Nesterov', 'wp-ultimo'),
	__('Nesterovskiy Rayon', 'wp-ultimo'),
	__('Otradnoye', 'wp-ultimo'),
	__('Ozerskiy Rayon', 'wp-ultimo'),
	__('Ozërsk', 'wp-ultimo'),
	__('Pionerskiy', 'wp-ultimo'),
	__('Polessk', 'wp-ultimo'),
	__('Pravdinsk', 'wp-ultimo'),
	__('Primorsk', 'wp-ultimo'),
	__('Slavsk', 'wp-ultimo'),
	__('Slavskiy Rayon', 'wp-ultimo'),
	__('Sovetsk', 'wp-ultimo'),
	__('Svetlogorsk', 'wp-ultimo'),
	__('Svetlyy', 'wp-ultimo'),
	__('Volochayevskoye', 'wp-ultimo'),
	__('Vzmorye', 'wp-ultimo'),
	__('Yantarnyy', 'wp-ultimo'),
	__('Yuzhnyy', 'wp-ultimo'),
	__('Zelenogradsk', 'wp-ultimo'),
	__('Zheleznodorozhnyy', 'wp-ultimo'),
	__('Znamensk', 'wp-ultimo'),
);
