<?php
/**
 * State City List for KGN - RU.
 *
 * City count: 31
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for KGN - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Belozërskoye', 'wp-ultimo'),
	__('Dalmatovo', 'wp-ultimo'),
	__('Glyadyanskoye', 'wp-ultimo'),
	__('Ikovka', 'wp-ultimo'),
	__('Kataysk', 'wp-ultimo'),
	__('Ketovo', 'wp-ultimo'),
	__('Krasnyy Oktyabr’', 'wp-ultimo'),
	__('Kurgan', 'wp-ultimo'),
	__('Kurtamysh', 'wp-ultimo'),
	__('Lebyazh’ye', 'wp-ultimo'),
	__('Lebyazh’yevskiy Rayon', 'wp-ultimo'),
	__('Lesnikovo', 'wp-ultimo'),
	__('Makushino', 'wp-ultimo'),
	__('Mishkino', 'wp-ultimo'),
	__('Mokrousovo', 'wp-ultimo'),
	__('Mokrousovskiy Rayon', 'wp-ultimo'),
	__('Petukhovo', 'wp-ultimo'),
	__('Polovinnoye', 'wp-ultimo'),
	__('Prosvet', 'wp-ultimo'),
	__('Safakulevo', 'wp-ultimo'),
	__('Safakulevskiy Rayon', 'wp-ultimo'),
	__('Shadrinsk', 'wp-ultimo'),
	__('Shatrovo', 'wp-ultimo'),
	__('Shumikha', 'wp-ultimo'),
	__('Shumikhinskiy Rayon', 'wp-ultimo'),
	__('Tselinnoye', 'wp-ultimo'),
	__('Vargashi', 'wp-ultimo'),
	__('Vargashinskiy Rayon', 'wp-ultimo'),
	__('Vvedenskoye', 'wp-ultimo'),
	__('Yurgamysh', 'wp-ultimo'),
	__('Zverinogolovskoye', 'wp-ultimo'),
);
