<?php
/**
 * State City List for KHA - RU.
 *
 * City count: 40
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for KHA - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Amursk', 'wp-ultimo'),
	__('Ayan', 'wp-ultimo'),
	__('Berëzovyy', 'wp-ultimo'),
	__('Bikin', 'wp-ultimo'),
	__('Bikinskiy Rayon', 'wp-ultimo'),
	__('Bogorodskoye', 'wp-ultimo'),
	__('Chegdomyn', 'wp-ultimo'),
	__('Chumikan', 'wp-ultimo'),
	__('De-Kastri', 'wp-ultimo'),
	__('Gorin', 'wp-ultimo'),
	__('Gornyy', 'wp-ultimo'),
	__('Imeni Poliny Osipenko', 'wp-ultimo'),
	__('Khabarovsk', 'wp-ultimo'),
	__('Khabarovsk Vtoroy', 'wp-ultimo'),
	__('Khor', 'wp-ultimo'),
	__('Khurba', 'wp-ultimo'),
	__('Knyaze-Volkonskoye', 'wp-ultimo'),
	__('Komsomolsk-on-Amur', 'wp-ultimo'),
	__('Korfovskiy', 'wp-ultimo'),
	__('Lazarev', 'wp-ultimo'),
	__('Lermontovka', 'wp-ultimo'),
	__('Litovko', 'wp-ultimo'),
	__('Lososina', 'wp-ultimo'),
	__('Mago', 'wp-ultimo'),
	__('Mayskiy', 'wp-ultimo'),
	__('Mnogovershinnyy', 'wp-ultimo'),
	__('Mukhen', 'wp-ultimo'),
	__('Nekrasovka', 'wp-ultimo'),
	__('Nikolayevsk-on-Amure', 'wp-ultimo'),
	__('Novyy Urgal', 'wp-ultimo'),
	__('Okhotsk', 'wp-ultimo'),
	__('Selikhino', 'wp-ultimo'),
	__('Solnechnyy', 'wp-ultimo'),
	__('Sovetskaya Gavan’', 'wp-ultimo'),
	__('Topolëvo', 'wp-ultimo'),
	__('Tyrma', 'wp-ultimo'),
	__('Vanino', 'wp-ultimo'),
	__('Vyazemskiy', 'wp-ultimo'),
	__('Vysokogornyy', 'wp-ultimo'),
	__('Zavety Il’icha', 'wp-ultimo'),
);
