<?php
/**
 * State City List for KHM - RU.
 *
 * City count: 44
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for KHM - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Agirish', 'wp-ultimo'),
	__('Andra', 'wp-ultimo'),
	__('Barsovo', 'wp-ultimo'),
	__('Beloyarskiy', 'wp-ultimo'),
	__('Berëzovo', 'wp-ultimo'),
	__('Fedorovskiy', 'wp-ultimo'),
	__('Gornopravdinsk', 'wp-ultimo'),
	__('Igrim', 'wp-ultimo'),
	__('Izluchinsk', 'wp-ultimo'),
	__('Khanty-Mansiysk', 'wp-ultimo'),
	__('Khulimsunt', 'wp-ultimo'),
	__('Kogalym', 'wp-ultimo'),
	__('Kommunisticheskiy', 'wp-ultimo'),
	__('Kondinskoye', 'wp-ultimo'),
	__('Kuminskiy', 'wp-ultimo'),
	__('Langepas', 'wp-ultimo'),
	__('Lokosovo', 'wp-ultimo'),
	__('Lyantor', 'wp-ultimo'),
	__('Malinovskiy', 'wp-ultimo'),
	__('Megion', 'wp-ultimo'),
	__('Mezhdurechenskiy', 'wp-ultimo'),
	__('Mortka', 'wp-ultimo'),
	__('Nefteyugansk', 'wp-ultimo'),
	__('Nizhnesortymskiy', 'wp-ultimo'),
	__('Nizhnevartovsk', 'wp-ultimo'),
	__('Novoagansk', 'wp-ultimo'),
	__('Nyagan', 'wp-ultimo'),
	__('Pionerskiy', 'wp-ultimo'),
	__('Pokachi', 'wp-ultimo'),
	__('Poykovskiy', 'wp-ultimo'),
	__('Priob’ye', 'wp-ultimo'),
	__('Pyt-Yakh', 'wp-ultimo'),
	__('Raduzhny', 'wp-ultimo'),
	__('Russkinskiye', 'wp-ultimo'),
	__('Salym', 'wp-ultimo'),
	__('Saranpaul’', 'wp-ultimo'),
	__('Sherkaly', 'wp-ultimo'),
	__('Singapay', 'wp-ultimo'),
	__('Solnechniy', 'wp-ultimo'),
	__('Sovetskiy', 'wp-ultimo'),
	__('Surgut', 'wp-ultimo'),
	__('Uray', 'wp-ultimo'),
	__('Yugorsk', 'wp-ultimo'),
	__('Zelenoborsk', 'wp-ultimo'),
);
