<?php
/**
 * State City List for KIR - RU.
 *
 * City count: 89
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for KIR - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Afanas’yevskiy Rayon', 'wp-ultimo'),
	__('Arbazh', 'wp-ultimo'),
	__('Arkul’', 'wp-ultimo'),
	__('Belaya Kholunitsa', 'wp-ultimo'),
	__('Belorechensk', 'wp-ultimo'),
	__('Bogorodskoye', 'wp-ultimo'),
	__('Chërnaya Kholunitsa', 'wp-ultimo'),
	__('Darovskoy', 'wp-ultimo'),
	__('Dem’yanovo', 'wp-ultimo'),
	__('Dubrovka', 'wp-ultimo'),
	__('Falënki', 'wp-ultimo'),
	__('Falënskiy Rayon', 'wp-ultimo'),
	__('Kiknur', 'wp-ultimo'),
	__('Kiknurskiy Rayon', 'wp-ultimo'),
	__('Kil’mez’', 'wp-ultimo'),
	__('Kirov', 'wp-ultimo'),
	__('Kirovo-Chepetsk', 'wp-ultimo'),
	__('Kirovo-Chepetskiy Rayon', 'wp-ultimo'),
	__('Kirs', 'wp-ultimo'),
	__('Kosino', 'wp-ultimo'),
	__('Kostino', 'wp-ultimo'),
	__('Kotel’nich', 'wp-ultimo'),
	__('Krasnaya Polyana', 'wp-ultimo'),
	__('Kumëny', 'wp-ultimo'),
	__('Lal’sk', 'wp-ultimo'),
	__('Leninskoye', 'wp-ultimo'),
	__('Lesnoy', 'wp-ultimo'),
	__('Lesnyye Polyany', 'wp-ultimo'),
	__('Luza', 'wp-ultimo'),
	__('Luzskiy Rayon', 'wp-ultimo'),
	__('Lyangasovo', 'wp-ultimo'),
	__('Malmyzh', 'wp-ultimo'),
	__('Malmyzhskiy Rayon', 'wp-ultimo'),
	__('Maromitsa', 'wp-ultimo'),
	__('Medvedok', 'wp-ultimo'),
	__('Mirnyy', 'wp-ultimo'),
	__('Murashi', 'wp-ultimo'),
	__('Murashinskiy Rayon', 'wp-ultimo'),
	__('Murygino', 'wp-ultimo'),
	__('Nagorsk', 'wp-ultimo'),
	__('Nagorskiy Rayon', 'wp-ultimo'),
	__('Nema', 'wp-ultimo'),
	__('Nemskiy Rayon', 'wp-ultimo'),
	__('Nizhneivkino', 'wp-ultimo'),
	__('Nolinsk', 'wp-ultimo'),
	__('Nolinskiy Rayon', 'wp-ultimo'),
	__('Omutninsk', 'wp-ultimo'),
	__('Oparino', 'wp-ultimo'),
	__('Orichevskiy Rayon', 'wp-ultimo'),
	__('Orichi', 'wp-ultimo'),
	__('Orlov', 'wp-ultimo'),
	__('Orlovskiy Rayon', 'wp-ultimo'),
	__('Pasegovo', 'wp-ultimo'),
	__('Peskovka', 'wp-ultimo'),
	__('Pinyug', 'wp-ultimo'),
	__('Pizhanka', 'wp-ultimo'),
	__('Pizhanskiy Rayon', 'wp-ultimo'),
	__('Podosinovets', 'wp-ultimo'),
	__('Podosinovskiy Rayon', 'wp-ultimo'),
	__('Raduzhnyy', 'wp-ultimo'),
	__('Rudnichnyy', 'wp-ultimo'),
	__('Sanchursk', 'wp-ultimo'),
	__('Sanchurskiy Rayon', 'wp-ultimo'),
	__('Shabalinskiy Rayon', 'wp-ultimo'),
	__('Slobodskoy', 'wp-ultimo'),
	__('Slobodskoy Rayon', 'wp-ultimo'),
	__('Sosnovka', 'wp-ultimo'),
	__('Sovetsk', 'wp-ultimo'),
	__('Sovetskiy Rayon', 'wp-ultimo'),
	__('Sozimskiy', 'wp-ultimo'),
	__('Strizhi', 'wp-ultimo'),
	__('Stulovo', 'wp-ultimo'),
	__('Suna', 'wp-ultimo'),
	__('Sunskiy Rayon', 'wp-ultimo'),
	__('Svecha', 'wp-ultimo'),
	__('Svetlopolyansk', 'wp-ultimo'),
	__('Torfyanoy', 'wp-ultimo'),
	__('Tuzha', 'wp-ultimo'),
	__('Uni', 'wp-ultimo'),
	__('Uninskiy Rayon', 'wp-ultimo'),
	__('Urzhum', 'wp-ultimo'),
	__('Vakhrushi', 'wp-ultimo'),
	__('Verkhoshizhem’ye', 'wp-ultimo'),
	__('Vostochnyy', 'wp-ultimo'),
	__('Vyatskiye Polyany', 'wp-ultimo'),
	__('Yaransk', 'wp-ultimo'),
	__('Yaranskiy Rayon', 'wp-ultimo'),
	__('Yur’yanskiy Rayon', 'wp-ultimo'),
	__('Zuyevka', 'wp-ultimo'),
);
