<?php
/**
 * State City List for KK - RU.
 *
 * City count: 22
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for KK - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Abakan', 'wp-ultimo'),
	__('Abakan Gorod', 'wp-ultimo'),
	__('Abaza', 'wp-ultimo'),
	__('Altayskiy Rayon', 'wp-ultimo'),
	__('Askiz', 'wp-ultimo'),
	__('Belyy Yar', 'wp-ultimo'),
	__('Beya', 'wp-ultimo'),
	__('Biskamzha', 'wp-ultimo'),
	__('Bograd', 'wp-ultimo'),
	__('Bogradskiy Rayon', 'wp-ultimo'),
	__('Chernogorsk', 'wp-ultimo'),
	__('Cherëmushki', 'wp-ultimo'),
	__('Kommunar', 'wp-ultimo'),
	__('Mayna', 'wp-ultimo'),
	__('Podsineye', 'wp-ultimo'),
	__('Sayanogorsk', 'wp-ultimo'),
	__('Shira', 'wp-ultimo'),
	__('Sorsk', 'wp-ultimo'),
	__('Tashtyp', 'wp-ultimo'),
	__('Tuim', 'wp-ultimo'),
	__('Ust’-Abakan', 'wp-ultimo'),
	__('Vershina Tei', 'wp-ultimo'),
);
