<?php
/**
 * State City List for KL - RU.
 *
 * City count: 18
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for KL - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Arshan’', 'wp-ultimo'),
	__('Elista', 'wp-ultimo'),
	__('Gorodoviki', 'wp-ultimo'),
	__('Gorodovikovsk', 'wp-ultimo'),
	__('Iki-Burul', 'wp-ultimo'),
	__('Iki-Burul’skiy Rayon', 'wp-ultimo'),
	__('Kaspiyskiy', 'wp-ultimo'),
	__('Komsomol’skiy', 'wp-ultimo'),
	__('Malyye Derbety', 'wp-ultimo'),
	__('Priyutnoye', 'wp-ultimo'),
	__('Sadovoye', 'wp-ultimo'),
	__('Sarpinskiy Rayon', 'wp-ultimo'),
	__('Sovetskoye', 'wp-ultimo'),
	__('Troitskoye', 'wp-ultimo'),
	__('Tsagan Aman', 'wp-ultimo'),
	__('Yashalta', 'wp-ultimo'),
	__('Yashaltinskiy Rayon', 'wp-ultimo'),
	__('Yashkul’', 'wp-ultimo'),
);
