<?php
/**
 * State City List for KLU - RU.
 *
 * City count: 70
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for KLU - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Babynino', 'wp-ultimo'),
	__('Babyninskiy Rayon', 'wp-ultimo'),
	__('Balabanovo', 'wp-ultimo'),
	__('Baryatino', 'wp-ultimo'),
	__('Baryatinskiy Rayon', 'wp-ultimo'),
	__('Belousovo', 'wp-ultimo'),
	__('Betlitsa', 'wp-ultimo'),
	__('Borovsk', 'wp-ultimo'),
	__('Borovskiy Rayon', 'wp-ultimo'),
	__('Deshovki', 'wp-ultimo'),
	__('Detchino', 'wp-ultimo'),
	__('Duminichi', 'wp-ultimo'),
	__('Duminichskiy Rayon', 'wp-ultimo'),
	__('Dvortsy', 'wp-ultimo'),
	__('Dzerzhinskiy Rayon', 'wp-ultimo'),
	__('Ferzikovo', 'wp-ultimo'),
	__('Ferzikovskiy Rayon', 'wp-ultimo'),
	__('Iznoski', 'wp-ultimo'),
	__('Iznoskovskiy rayon', 'wp-ultimo'),
	__('Kaluga', 'wp-ultimo'),
	__('Khvastovichi', 'wp-ultimo'),
	__('Khvastovichskiy Rayon', 'wp-ultimo'),
	__('Kirov', 'wp-ultimo'),
	__('Kirovskiy Rayon', 'wp-ultimo'),
	__('Kondrovo', 'wp-ultimo'),
	__('Kozel’sk', 'wp-ultimo'),
	__('Kozel’skiy Rayon', 'wp-ultimo'),
	__('Kremenki', 'wp-ultimo'),
	__('Kudinovo', 'wp-ultimo'),
	__('Kurovskoye', 'wp-ultimo'),
	__('Kuybyshevskiy Rayon', 'wp-ultimo'),
	__('Lyudinovo', 'wp-ultimo'),
	__('Lyudinovskiy Rayon', 'wp-ultimo'),
	__('Maloyaroslavets', 'wp-ultimo'),
	__('Maloyaroslavetskiy Rayon', 'wp-ultimo'),
	__('Medynskiy Rayon', 'wp-ultimo'),
	__('Medyn’', 'wp-ultimo'),
	__('Meshchovsk', 'wp-ultimo'),
	__('Meshchovskiy Rayon', 'wp-ultimo'),
	__('Mosal’sk', 'wp-ultimo'),
	__('Mosal’skiy Rayon', 'wp-ultimo'),
	__('Mstikhino', 'wp-ultimo'),
	__('Myatlevo', 'wp-ultimo'),
	__('Nikola-Lenivets', 'wp-ultimo'),
	__('Obninsk', 'wp-ultimo'),
	__('Peremyshl’', 'wp-ultimo'),
	__('Peremyshl’skiy Rayon', 'wp-ultimo'),
	__('Polotnyanyy Zavod', 'wp-ultimo'),
	__('Pyatovskiy', 'wp-ultimo'),
	__('Seredeyskiy', 'wp-ultimo'),
	__('Sosenskiy', 'wp-ultimo'),
	__('Spas-Demensk', 'wp-ultimo'),
	__('Spas-Demenskiy Rayon', 'wp-ultimo'),
	__('Sukhinichi', 'wp-ultimo'),
	__('Sukhinichskiy Rayon', 'wp-ultimo'),
	__('Tarusa', 'wp-ultimo'),
	__('Tarusskiy Rayon', 'wp-ultimo'),
	__('Tovarkovo', 'wp-ultimo'),
	__('Ul’yanovskiy Rayon', 'wp-ultimo'),
	__('Vorotynsk', 'wp-ultimo'),
	__('Vysokinichi', 'wp-ultimo'),
	__('Yermolino', 'wp-ultimo'),
	__('Yukhnov', 'wp-ultimo'),
	__('Yukhnovskiy Rayon', 'wp-ultimo'),
	__('Zarech’ye', 'wp-ultimo'),
	__('Zhiletovo', 'wp-ultimo'),
	__('Zhizdra', 'wp-ultimo'),
	__('Zhizdrinskiy Rayon', 'wp-ultimo'),
	__('Zhukovo', 'wp-ultimo'),
	__('Zhukovskiy Rayon', 'wp-ultimo'),
);
