<?php
/**
 * State City List for KO - RU.
 *
 * City count: 51
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for KO - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Aykino', 'wp-ultimo'),
	__('Blagoyevo', 'wp-ultimo'),
	__('Borovoy', 'wp-ultimo'),
	__('Ezhva', 'wp-ultimo'),
	__('Inta', 'wp-ultimo'),
	__('Izhma', 'wp-ultimo'),
	__('Knyazhpogostskiy Rayon', 'wp-ultimo'),
	__('Kortkeros', 'wp-ultimo'),
	__('Koslan', 'wp-ultimo'),
	__('Koygorodok', 'wp-ultimo'),
	__('Koygorodskiy Rayon', 'wp-ultimo'),
	__('Kozhva', 'wp-ultimo'),
	__('Letka', 'wp-ultimo'),
	__('Mezhdurechensk', 'wp-ultimo'),
	__('Mikun’', 'wp-ultimo'),
	__('Mordino', 'wp-ultimo'),
	__('Nizhniy Odes', 'wp-ultimo'),
	__('Parma', 'wp-ultimo'),
	__('Pechora', 'wp-ultimo'),
	__('Priluzskiy Rayon', 'wp-ultimo'),
	__('Promyshlennyy', 'wp-ultimo'),
	__('Puteyets', 'wp-ultimo'),
	__('Sedkyrkeshch', 'wp-ultimo'),
	__('Shudayag', 'wp-ultimo'),
	__('Sindor', 'wp-ultimo'),
	__('Sosnogorsk', 'wp-ultimo'),
	__('Sovetskiy', 'wp-ultimo'),
	__('Syktyvkar', 'wp-ultimo'),
	__('Synya', 'wp-ultimo'),
	__('Troitsko-Pechorsk', 'wp-ultimo'),
	__('Troitsko-Pechorskiy Rayon', 'wp-ultimo'),
	__('Tsementnozavodskiy', 'wp-ultimo'),
	__('Ukhta', 'wp-ultimo'),
	__('Usinsk', 'wp-ultimo'),
	__('Usogorsk', 'wp-ultimo'),
	__('Ust-Tsilma', 'wp-ultimo'),
	__('Ust’-Kulom', 'wp-ultimo'),
	__('Ust’-Tsilemskiy Rayon', 'wp-ultimo'),
	__('Verkhnyaya Inta', 'wp-ultimo'),
	__('Verkhnyaya Maksakovka', 'wp-ultimo'),
	__('Vizinga', 'wp-ultimo'),
	__('Vodnyy', 'wp-ultimo'),
	__('Vorgashor', 'wp-ultimo'),
	__('Vorkuta', 'wp-ultimo'),
	__('Voyvozh', 'wp-ultimo'),
	__('Vuktyl', 'wp-ultimo'),
	__('Yarega', 'wp-ultimo'),
	__('Yemva', 'wp-ultimo'),
	__('Zapolyarnyy', 'wp-ultimo'),
	__('Zelenets', 'wp-ultimo'),
	__('Zheshart', 'wp-ultimo'),
);
