<?php
/**
 * State City List for KOS - RU.
 *
 * City count: 44
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for KOS - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Antropovo', 'wp-ultimo'),
	__('Antropovskiy Rayon', 'wp-ultimo'),
	__('Bogovarovo', 'wp-ultimo'),
	__('Buy', 'wp-ultimo'),
	__('Buyskiy Rayon', 'wp-ultimo'),
	__('Chistyye Bory', 'wp-ultimo'),
	__('Chukhloma', 'wp-ultimo'),
	__('Galich', 'wp-ultimo'),
	__('Galichskiy Rayon', 'wp-ultimo'),
	__('Georgiyevskoye', 'wp-ultimo'),
	__('Kadyy', 'wp-ultimo'),
	__('Kadyyskiy Rayon', 'wp-ultimo'),
	__('Kologriv', 'wp-ultimo'),
	__('Kosmynino', 'wp-ultimo'),
	__('Kostroma', 'wp-ultimo'),
	__('Kostromskoy Rayon', 'wp-ultimo'),
	__('Krasnosel’skiy Rayon', 'wp-ultimo'),
	__('Krasnoye-na-Volge', 'wp-ultimo'),
	__('Makar’yev', 'wp-ultimo'),
	__('Manturovo', 'wp-ultimo'),
	__('Manturovskiy Rayon', 'wp-ultimo'),
	__('Nerekhta', 'wp-ultimo'),
	__('Nerekhtskiy Rayon', 'wp-ultimo'),
	__('Neya', 'wp-ultimo'),
	__('Neyskiy Rayon', 'wp-ultimo'),
	__('Ostrovskiy Rayon', 'wp-ultimo'),
	__('Ostrovskoye', 'wp-ultimo'),
	__('Parfen’yevo', 'wp-ultimo'),
	__('Parfen’yevskiy Rayon', 'wp-ultimo'),
	__('Pavino', 'wp-ultimo'),
	__('Ponazyrevo', 'wp-ultimo'),
	__('Ponazyrevskiy Rayon', 'wp-ultimo'),
	__('Pyshchug', 'wp-ultimo'),
	__('Shar’inskiy Rayon', 'wp-ultimo'),
	__('Shar’ya', 'wp-ultimo'),
	__('Soligalich', 'wp-ultimo'),
	__('Soligalichskiy Rayon', 'wp-ultimo'),
	__('Sudislavl’', 'wp-ultimo'),
	__('Sudislavskiy Rayon', 'wp-ultimo'),
	__('Susanino', 'wp-ultimo'),
	__('Vetluzhskiy', 'wp-ultimo'),
	__('Vokhma', 'wp-ultimo'),
	__('Vokhomskiy Rayon', 'wp-ultimo'),
	__('Volgorechensk', 'wp-ultimo'),
);
