<?php
/**
 * State City List for KR - RU.
 *
 * City count: 48
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for KR - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Belomorsk', 'wp-ultimo'),
	__('Borovoy', 'wp-ultimo'),
	__('Chupa', 'wp-ultimo'),
	__('Essoyla', 'wp-ultimo'),
	__('Girvas', 'wp-ultimo'),
	__('Kalevala', 'wp-ultimo'),
	__('Kem’', 'wp-ultimo'),
	__('Kharlu', 'wp-ultimo'),
	__('Khelyulya', 'wp-ultimo'),
	__('Kondopoga', 'wp-ultimo'),
	__('Kostomuksha', 'wp-ultimo'),
	__('Kvartsitnyy', 'wp-ultimo'),
	__('Lakhdenpokh’ya', 'wp-ultimo'),
	__('Ledmozero', 'wp-ultimo'),
	__('Loukhi', 'wp-ultimo'),
	__('Lyaskelya', 'wp-ultimo'),
	__('Matrosy', 'wp-ultimo'),
	__('Medvezh’yegorsk', 'wp-ultimo'),
	__('Muyezerskiy', 'wp-ultimo'),
	__('Nadvoitsy', 'wp-ultimo'),
	__('Olonets', 'wp-ultimo'),
	__('Petrozavodsk', 'wp-ultimo'),
	__('Pindushi', 'wp-ultimo'),
	__('Pitkyaranta', 'wp-ultimo'),
	__('Pitkyarantskiy Rayon', 'wp-ultimo'),
	__('Porosozero', 'wp-ultimo'),
	__('Povenets', 'wp-ultimo'),
	__('Prionezhskiy Rayon', 'wp-ultimo'),
	__('Pryazha', 'wp-ultimo'),
	__('Pudozh', 'wp-ultimo'),
	__('Pyaozerskiy', 'wp-ultimo'),
	__('Rabocheostrovsk', 'wp-ultimo'),
	__('Ruskeala', 'wp-ultimo'),
	__('Salmi', 'wp-ultimo'),
	__('Segezha', 'wp-ultimo'),
	__('Shal’skiy', 'wp-ultimo'),
	__('Sheltozero', 'wp-ultimo'),
	__('Shun’ga', 'wp-ultimo'),
	__('Shuya', 'wp-ultimo'),
	__('Sortavala', 'wp-ultimo'),
	__('Sortaval’skiy Rayon', 'wp-ultimo'),
	__('Sukkozero', 'wp-ultimo'),
	__('Suoyarvi', 'wp-ultimo'),
	__('Suoyarvskiy Rayon', 'wp-ultimo'),
	__('Vyartsilya', 'wp-ultimo'),
	__('Yanishpole', 'wp-ultimo'),
	__('Yanis’yarvi', 'wp-ultimo'),
	__('Yushkozero', 'wp-ultimo'),
);
