<?php
/**
 * State City List for KRS - RU.
 *
 * City count: 44
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for KRS - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Belaya', 'wp-ultimo'),
	__('Cheremisinovo', 'wp-ultimo'),
	__('Cheremisinovskiy Rayon', 'wp-ultimo'),
	__('Chernitsyno', 'wp-ultimo'),
	__('Fatezh', 'wp-ultimo'),
	__('Fatezhskiy Rayon', 'wp-ultimo'),
	__('Glushkovo', 'wp-ultimo'),
	__('Gorshechenskiy Rayon', 'wp-ultimo'),
	__('Gorshechnoye', 'wp-ultimo'),
	__('Ivanino', 'wp-ultimo'),
	__('Kastorenskiy Rayon', 'wp-ultimo'),
	__('Kastornoye', 'wp-ultimo'),
	__('Khomutovka', 'wp-ultimo'),
	__('Kirovskiy', 'wp-ultimo'),
	__('Konyshevka', 'wp-ultimo'),
	__('Korenëvo', 'wp-ultimo'),
	__('Kshenskiy', 'wp-ultimo'),
	__('Kurchatov', 'wp-ultimo'),
	__('Kursk', 'wp-ultimo'),
	__('Kurskiy Rayon', 'wp-ultimo'),
	__('L’govskiy', 'wp-ultimo'),
	__('L’govskiy Rayon', 'wp-ultimo'),
	__('Manturovo', 'wp-ultimo'),
	__('Medvenskiy Rayon', 'wp-ultimo'),
	__('Mikhaylovka', 'wp-ultimo'),
	__('Oboyanskiy Rayon', 'wp-ultimo'),
	__('Oboyan’', 'wp-ultimo'),
	__('Olym', 'wp-ultimo'),
	__('Pervoavgustovskiy', 'wp-ultimo'),
	__('Ponyri Vtoryye', 'wp-ultimo'),
	__('Pristenskiy Rayon', 'wp-ultimo'),
	__('Pristen’', 'wp-ultimo'),
	__('Pryamitsyno', 'wp-ultimo'),
	__('Ryl’sk', 'wp-ultimo'),
	__('Shchigry', 'wp-ultimo'),
	__('Solntsevo', 'wp-ultimo'),
	__('Solntsevskiy Rayon', 'wp-ultimo'),
	__('Sovetskiy Rayon', 'wp-ultimo'),
	__('Sudzha', 'wp-ultimo'),
	__('Tim', 'wp-ultimo'),
	__('Voroshnëvo', 'wp-ultimo'),
	__('Zheleznogorsk', 'wp-ultimo'),
	__('Zolotukhino', 'wp-ultimo'),
	__('Zolotukhinskiy Rayon', 'wp-ultimo'),
);
