<?php
/**
 * State City List for LIP - RU.
 *
 * City count: 47
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for LIP - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Bol’shoy Khomutets', 'wp-ultimo'),
	__('Borinskoye', 'wp-ultimo'),
	__('Chaplygin', 'wp-ultimo'),
	__('Chaplyginskiy Rayon', 'wp-ultimo'),
	__('Dankov', 'wp-ultimo'),
	__('Dankovskiy Rayon', 'wp-ultimo'),
	__('Dobrinka', 'wp-ultimo'),
	__('Dobrinskiy Rayon', 'wp-ultimo'),
	__('Dobrovskiy Rayon', 'wp-ultimo'),
	__('Dobroye', 'wp-ultimo'),
	__('Dolgorukovo', 'wp-ultimo'),
	__('Dolgorukovskiy Rayon', 'wp-ultimo'),
	__('Donskoye', 'wp-ultimo'),
	__('Gryazi', 'wp-ultimo'),
	__('Gryazinskiy Rayon', 'wp-ultimo'),
	__('Izmalkovo', 'wp-ultimo'),
	__('Izmalkovskiy Rayon', 'wp-ultimo'),
	__('Kalikino', 'wp-ultimo'),
	__('Kazaki', 'wp-ultimo'),
	__('Kazinka', 'wp-ultimo'),
	__('Khlevenskiy Rayon', 'wp-ultimo'),
	__('Khlevnoye', 'wp-ultimo'),
	__('Krasninskiy Rayon', 'wp-ultimo'),
	__('Krasnoye', 'wp-ultimo'),
	__('Kuz’minskiye Otverzhki', 'wp-ultimo'),
	__('Lebedyanskiy Rayon', 'wp-ultimo'),
	__('Lebedyan’', 'wp-ultimo'),
	__('Lev Tolstoy', 'wp-ultimo'),
	__('Lev-Tolstovskiy Rayon', 'wp-ultimo'),
	__('Lipetsk', 'wp-ultimo'),
	__('Lipetskiy Rayon', 'wp-ultimo'),
	__('Petrovskiy', 'wp-ultimo'),
	__('Plekhanovo', 'wp-ultimo'),
	__('Prigorodka', 'wp-ultimo'),
	__('Stanovlyanskiy Rayon', 'wp-ultimo'),
	__('Stanovoye', 'wp-ultimo'),
	__('Syrskoye', 'wp-ultimo'),
	__('Terbunskiy Rayon', 'wp-ultimo'),
	__('Terbuny', 'wp-ultimo'),
	__('Usmanskiy Rayon', 'wp-ultimo'),
	__('Usman’', 'wp-ultimo'),
	__('Volovo', 'wp-ultimo'),
	__('Volovskiy Rayon', 'wp-ultimo'),
	__('Yelets', 'wp-ultimo'),
	__('Yeletskiy Rayon', 'wp-ultimo'),
	__('Zadonsk', 'wp-ultimo'),
	__('Zadonskiy Rayon', 'wp-ultimo'),
);
