<?php
/**
 * State City List for MAG - RU.
 *
 * City count: 22
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for MAG - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Arman’', 'wp-ultimo'),
	__('Dukat', 'wp-ultimo'),
	__('Evensk', 'wp-ultimo'),
	__('Gorod Magadan', 'wp-ultimo'),
	__('Kholodnyy', 'wp-ultimo'),
	__('Magadan', 'wp-ultimo'),
	__('Myaundzha', 'wp-ultimo'),
	__('Ola', 'wp-ultimo'),
	__('Ol’skiy Rayon', 'wp-ultimo'),
	__('Omsukchan', 'wp-ultimo'),
	__('Omsukchanskiy Rayon', 'wp-ultimo'),
	__('Orotukan', 'wp-ultimo'),
	__('Palatka', 'wp-ultimo'),
	__('Seymchan', 'wp-ultimo'),
	__("Sinegor'ye", 'wp-ultimo'),
	__('Sokol', 'wp-ultimo'),
	__('Srednekanskiy Rayon', 'wp-ultimo'),
	__('Susuman', 'wp-ultimo'),
	__('Talaya', 'wp-ultimo'),
	__('Uptar', 'wp-ultimo'),
	__('Ust’-Omchug', 'wp-ultimo'),
	__('Yagodnoye', 'wp-ultimo'),
);
