<?php
/**
 * State City List for ME - RU.
 *
 * City count: 35
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for ME - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Gornomariyskiy Rayon', 'wp-ultimo'),
	__('Kilemarskiy Rayon', 'wp-ultimo'),
	__('Kilemary', 'wp-ultimo'),
	__('Koz’modem’yansk', 'wp-ultimo'),
	__('Krasnogorskiy', 'wp-ultimo'),
	__('Kuzhener', 'wp-ultimo'),
	__('Kuzhenerskiy Rayon', 'wp-ultimo'),
	__('Mari-Turek', 'wp-ultimo'),
	__('Mari-Turekskiy Rayon', 'wp-ultimo'),
	__('Medvedevo', 'wp-ultimo'),
	__('Medvedevskiy Rayon', 'wp-ultimo'),
	__('Mochalishche', 'wp-ultimo'),
	__('Morki', 'wp-ultimo'),
	__('Morkinskiy Rayon', 'wp-ultimo'),
	__('Novotor”yal’skiy Rayon', 'wp-ultimo'),
	__('Orshanka', 'wp-ultimo'),
	__('Orshanskiy Rayon', 'wp-ultimo'),
	__('Paran’ga', 'wp-ultimo'),
	__('Paran’ginskiy Rayon', 'wp-ultimo'),
	__('Pomary', 'wp-ultimo'),
	__('Privolzhskiy', 'wp-ultimo'),
	__('Sernur', 'wp-ultimo'),
	__('Sernurskiy Rayon', 'wp-ultimo'),
	__('Sovetskiy', 'wp-ultimo'),
	__('Sovetskiy Rayon', 'wp-ultimo'),
	__('Surok', 'wp-ultimo'),
	__('Suslonger', 'wp-ultimo'),
	__('Vilovatovo', 'wp-ultimo'),
	__('Volzhsk', 'wp-ultimo'),
	__('Volzhskiy Rayon', 'wp-ultimo'),
	__('Yoshkar-Ola', 'wp-ultimo'),
	__('Yurino', 'wp-ultimo'),
	__('Yurinskiy Rayon', 'wp-ultimo'),
	__('Zvenigovo', 'wp-ultimo'),
	__('Zvenigovskiy Rayon', 'wp-ultimo'),
);
