<?php
/**
 * State City List for MUR - RU.
 *
 * City count: 42
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for MUR - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Abram Mys', 'wp-ultimo'),
	__('Afrikanda', 'wp-ultimo'),
	__('Alakurtti', 'wp-ultimo'),
	__('Apatity', 'wp-ultimo'),
	__('Gadzhiyevo', 'wp-ultimo'),
	__('Kandalaksha', 'wp-ultimo'),
	__('Kandalakshskiy rayon', 'wp-ultimo'),
	__('Kirovsk', 'wp-ultimo'),
	__('Kola', 'wp-ultimo'),
	__('Kol’skiy Rayon', 'wp-ultimo'),
	__('Kovdor', 'wp-ultimo'),
	__('Kovdorskiy Rayon', 'wp-ultimo'),
	__('Lovozero', 'wp-ultimo'),
	__('Lovozerskiy Rayon', 'wp-ultimo'),
	__('Molochnyy', 'wp-ultimo'),
	__('Monchegorsk', 'wp-ultimo'),
	__('Murmansk', 'wp-ultimo'),
	__('Murmashi', 'wp-ultimo'),
	__('Nikel', 'wp-ultimo'),
	__('Olenegorsk', 'wp-ultimo'),
	__('Ostrovnoy', 'wp-ultimo'),
	__('Pechenga', 'wp-ultimo'),
	__('Pechengskiy Rayon', 'wp-ultimo'),
	__('Polyarnyy', 'wp-ultimo'),
	__('Polyarnyye Zori', 'wp-ultimo'),
	__('Poyakonda', 'wp-ultimo'),
	__('Revda', 'wp-ultimo'),
	__('Roslyakovo', 'wp-ultimo'),
	__('Safonovo', 'wp-ultimo'),
	__('Severomorsk', 'wp-ultimo'),
	__('Severomorsk-3', 'wp-ultimo'),
	__('Shonguy', 'wp-ultimo'),
	__('Snezhnogorsk', 'wp-ultimo'),
	__('Teribërka', 'wp-ultimo'),
	__('Terskiy Rayon', 'wp-ultimo'),
	__('Umba', 'wp-ultimo'),
	__('Verkhnetulomskiy', 'wp-ultimo'),
	__('Vidyayevo', 'wp-ultimo'),
	__('Vysokiy', 'wp-ultimo'),
	__('Zaozërsk', 'wp-ultimo'),
	__('Zapolyarnyy', 'wp-ultimo'),
	__('Zelenoborskiy', 'wp-ultimo'),
);
