<?php
/**
 * State City List for NEN - RU.
 *
 * City count: 2
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for NEN - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Iskateley', 'wp-ultimo'),
	__("Nar'yan-Mar", 'wp-ultimo'),
);
