<?php
/**
 * State City List for NGR - RU.
 *
 * City count: 54
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for NGR - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Batetskiy', 'wp-ultimo'),
	__('Batetskiy Rayon', 'wp-ultimo'),
	__('Borovichi', 'wp-ultimo'),
	__('Borovichskiy Rayon', 'wp-ultimo'),
	__('Chudovo', 'wp-ultimo'),
	__('Chudovskiy Rayon', 'wp-ultimo'),
	__('Demyansk', 'wp-ultimo'),
	__('Demyanskiy Rayon', 'wp-ultimo'),
	__('Kholm', 'wp-ultimo'),
	__('Kholmskiy Rayon', 'wp-ultimo'),
	__('Khvoynaya', 'wp-ultimo'),
	__('Khvoyninskiy Rayon', 'wp-ultimo'),
	__('Krasnofarfornyy', 'wp-ultimo'),
	__('Krechevitsy', 'wp-ultimo'),
	__('Krestetskiy Rayon', 'wp-ultimo'),
	__('Kresttsy', 'wp-ultimo'),
	__('Kulotino', 'wp-ultimo'),
	__('Lyubytino', 'wp-ultimo'),
	__('Lyubytinskiy Rayon', 'wp-ultimo'),
	__('Malaya Vishera', 'wp-ultimo'),
	__('Malovisherskiy Rayon', 'wp-ultimo'),
	__('Marevo', 'wp-ultimo'),
	__('Marevskiy Rayon', 'wp-ultimo'),
	__('Moshenskoy Rayon', 'wp-ultimo'),
	__('Moshenskoye', 'wp-ultimo'),
	__('Nebolchi', 'wp-ultimo'),
	__('Novgorodskiy Rayon', 'wp-ultimo'),
	__('Okulovka', 'wp-ultimo'),
	__('Okulovskiy Rayon', 'wp-ultimo'),
	__('Opechenskiy Posad', 'wp-ultimo'),
	__('Pankovka', 'wp-ultimo'),
	__('Parfino', 'wp-ultimo'),
	__('Parfinskiy Rayon', 'wp-ultimo'),
	__('Pestovo', 'wp-ultimo'),
	__('Pestovskiy Rayon', 'wp-ultimo'),
	__('Poddorskiy Rayon', 'wp-ultimo'),
	__('Poddor’ye', 'wp-ultimo'),
	__('Proletariy', 'wp-ultimo'),
	__('Shimsk', 'wp-ultimo'),
	__('Shimskiy Rayon', 'wp-ultimo'),
	__('Soletskiy Rayon', 'wp-ultimo'),
	__('Sol’tsy', 'wp-ultimo'),
	__('Staraya Russa', 'wp-ultimo'),
	__('Starorusskiy Rayon', 'wp-ultimo'),
	__('Uglovka', 'wp-ultimo'),
	__('Utorgosh', 'wp-ultimo'),
	__('Valday', 'wp-ultimo'),
	__('Valdayskiy Rayon', 'wp-ultimo'),
	__('Velikiy Novgorod', 'wp-ultimo'),
	__('Volkhovskiy', 'wp-ultimo'),
	__('Volot', 'wp-ultimo'),
	__('Volotovskiy Rayon', 'wp-ultimo'),
	__('Yedrovo', 'wp-ultimo'),
	__('Zarubino', 'wp-ultimo'),
);
