<?php
/**
 * State City List for NVS - RU.
 *
 * City count: 59
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for NVS - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Akademgorodok', 'wp-ultimo'),
	__('Bagan', 'wp-ultimo'),
	__('Barabinsk', 'wp-ultimo'),
	__('Baryshevo', 'wp-ultimo'),
	__('Berdsk', 'wp-ultimo'),
	__('Bolotnoye', 'wp-ultimo'),
	__('Chany', 'wp-ultimo'),
	__('Cherepanovo', 'wp-ultimo'),
	__('Chulym', 'wp-ultimo'),
	__('Dorogino', 'wp-ultimo'),
	__('Dubrovino', 'wp-ultimo'),
	__('Gornyy', 'wp-ultimo'),
	__('Iskitim', 'wp-ultimo'),
	__('Iskitimskiy Rayon', 'wp-ultimo'),
	__('Karasuk', 'wp-ultimo'),
	__('Kargat', 'wp-ultimo'),
	__('Kochenëvo', 'wp-ultimo'),
	__('Kochki', 'wp-ultimo'),
	__('Kolyvan’', 'wp-ultimo'),
	__('Kol’tsovo', 'wp-ultimo'),
	__('Krasnoobsk', 'wp-ultimo'),
	__('Krasnozërskoye', 'wp-ultimo'),
	__('Krivodanovka', 'wp-ultimo'),
	__('Kudryashovskiy', 'wp-ultimo'),
	__('Kupino', 'wp-ultimo'),
	__('Kuybyshev', 'wp-ultimo'),
	__('Kyshtovka', 'wp-ultimo'),
	__('Linëvo', 'wp-ultimo'),
	__('Listvyanskiy', 'wp-ultimo'),
	__('Maslyanino', 'wp-ultimo'),
	__('Maslyaninskiy Rayon', 'wp-ultimo'),
	__('Mochishche', 'wp-ultimo'),
	__('Moshkovo', 'wp-ultimo'),
	__('Moshkovskiy Rayon', 'wp-ultimo'),
	__('Novolugovoye', 'wp-ultimo'),
	__('Novosibirsk', 'wp-ultimo'),
	__('Novosibirskiy Rayon', 'wp-ultimo'),
	__('Ob’', 'wp-ultimo'),
	__('Ordynskiy Rayon', 'wp-ultimo'),
	__('Ordynskoye', 'wp-ultimo'),
	__('Polovinnoye', 'wp-ultimo'),
	__('Prokudskoye', 'wp-ultimo'),
	__('Sadovyy', 'wp-ultimo'),
	__('Severnoye', 'wp-ultimo'),
	__('Severnyy Rayon', 'wp-ultimo'),
	__('Sokur', 'wp-ultimo'),
	__('Stantsionno-Oyashinskiy', 'wp-ultimo'),
	__('Suzun', 'wp-ultimo'),
	__('Tashara', 'wp-ultimo'),
	__('Tatarsk', 'wp-ultimo'),
	__('Tatarskiy Rayon', 'wp-ultimo'),
	__('Toguchin', 'wp-ultimo'),
	__('Tolmachëvo', 'wp-ultimo'),
	__('Ubinskoye', 'wp-ultimo'),
	__('Ust’-Tarka', 'wp-ultimo'),
	__('Vengerovo', 'wp-ultimo'),
	__('Verkh-Tula', 'wp-ultimo'),
	__('Yarkovo', 'wp-ultimo'),
	__('Zdvinsk', 'wp-ultimo'),
);
