<?php
/**
 * State City List for OMS - RU.
 *
 * City count: 38
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for OMS - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Azovo', 'wp-ultimo'),
	__('Beregovoy', 'wp-ultimo'),
	__('Bol’sherech’ye', 'wp-ultimo'),
	__('Cherlak', 'wp-ultimo'),
	__('Irtyshskiy', 'wp-ultimo'),
	__('Kalachinsk', 'wp-ultimo'),
	__('Kolosovka', 'wp-ultimo'),
	__('Kormilovka', 'wp-ultimo'),
	__('Krasnoyarka', 'wp-ultimo'),
	__('Krasnyy Yar', 'wp-ultimo'),
	__('Krutaya Gorka', 'wp-ultimo'),
	__('Krutinka', 'wp-ultimo'),
	__('Luzino', 'wp-ultimo'),
	__('Lyubinskiy', 'wp-ultimo'),
	__('Muromtsevo', 'wp-ultimo'),
	__('Muromtsevskiy Rayon', 'wp-ultimo'),
	__('Nazyvayevsk', 'wp-ultimo'),
	__('Nizhnyaya Omka', 'wp-ultimo'),
	__('Novoomskiy', 'wp-ultimo'),
	__('Novovarshavka', 'wp-ultimo'),
	__('Odesskoye', 'wp-ultimo'),
	__('Okoneshnikovo', 'wp-ultimo'),
	__('Omsk', 'wp-ultimo'),
	__('Pavlogradka', 'wp-ultimo'),
	__('Poltavka', 'wp-ultimo'),
	__('Rostovka', 'wp-ultimo'),
	__('Russkaya Polyana', 'wp-ultimo'),
	__('Sargatskoye', 'wp-ultimo'),
	__('Sedel’nikovskiy Rayon', 'wp-ultimo'),
	__('Sherbakul’', 'wp-ultimo'),
	__('Tara', 'wp-ultimo'),
	__('Tavricheskoye', 'wp-ultimo'),
	__('Tevriz', 'wp-ultimo'),
	__('Troitsk', 'wp-ultimo'),
	__('Tyukalinsk', 'wp-ultimo'),
	__('Ust’-Ishim', 'wp-ultimo'),
	__('Vkhodnoy', 'wp-ultimo'),
	__('Znamenskoye', 'wp-ultimo'),
);
