<?php
/**
 * State City List for ORE - RU.
 *
 * City count: 52
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for ORE - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Abdulino', 'wp-ultimo'),
	__('Adamovka', 'wp-ultimo'),
	__('Alandskoye', 'wp-ultimo'),
	__('Asekeyevo', 'wp-ultimo'),
	__('Belyayevka', 'wp-ultimo'),
	__('Buguruslan', 'wp-ultimo'),
	__('Buzuluk', 'wp-ultimo'),
	__('Dombarovskiy', 'wp-ultimo'),
	__('Energetik', 'wp-ultimo'),
	__('Gay', 'wp-ultimo'),
	__('Ilek', 'wp-ultimo'),
	__('Kardailovo', 'wp-ultimo'),
	__('Koltubanovskiy', 'wp-ultimo'),
	__('Krasnogvardeyets', 'wp-ultimo'),
	__('Krasnokholm', 'wp-ultimo'),
	__('Krasnoyarskiy', 'wp-ultimo'),
	__('Krasnyy Kommunar', 'wp-ultimo'),
	__('Kurmanayevka', 'wp-ultimo'),
	__('Kuvandyk', 'wp-ultimo'),
	__('Kvarkeno', 'wp-ultimo'),
	__('Kvarkenskiy Rayon', 'wp-ultimo'),
	__('Matveyevka', 'wp-ultimo'),
	__('Mednogorsk', 'wp-ultimo'),
	__('Nezhinka', 'wp-ultimo'),
	__('Nizhnepavlovka', 'wp-ultimo'),
	__('Novoorsk', 'wp-ultimo'),
	__('Novoorskiy Rayon', 'wp-ultimo'),
	__('Novorudnyy', 'wp-ultimo'),
	__('Novosergiyevka', 'wp-ultimo'),
	__('Novotroitsk', 'wp-ultimo'),
	__('Orenburg', 'wp-ultimo'),
	__('Orsk', 'wp-ultimo'),
	__('Perevolotskiy', 'wp-ultimo'),
	__('Pleshanovo', 'wp-ultimo'),
	__('Podgorodnyaya Pokrovka', 'wp-ultimo'),
	__('Prigorodnyy', 'wp-ultimo'),
	__('Sakmara', 'wp-ultimo'),
	__('Saraktash', 'wp-ultimo'),
	__('Saraktashskiy Rayon', 'wp-ultimo'),
	__('Severnoye', 'wp-ultimo'),
	__('Sharlyk', 'wp-ultimo'),
	__('Shil’da', 'wp-ultimo'),
	__('Sol’-Iletsk', 'wp-ultimo'),
	__('Sorochinsk', 'wp-ultimo'),
	__('Staraya Akkermanovka', 'wp-ultimo'),
	__('Svetlyy', 'wp-ultimo'),
	__('Tashla', 'wp-ultimo'),
	__('Tatarskaya Kargala', 'wp-ultimo'),
	__('Totskoye', 'wp-ultimo'),
	__('Tyul’gan', 'wp-ultimo'),
	__('Yasnyy', 'wp-ultimo'),
	__('Yelizavetinka', 'wp-ultimo'),
);
