<?php
/**
 * State City List for ORL - RU.
 *
 * City count: 27
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for ORL - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Bolkhov', 'wp-ultimo'),
	__('Bolkhovskiy Rayon', 'wp-ultimo'),
	__('Dmitrovsk-Orlovskiy', 'wp-ultimo'),
	__('Glazunovka', 'wp-ultimo'),
	__('Khomutovo', 'wp-ultimo'),
	__('Khotynets', 'wp-ultimo'),
	__('Kolpny', 'wp-ultimo'),
	__('Korsakovo', 'wp-ultimo'),
	__('Krasnaya Zarya', 'wp-ultimo'),
	__('Kromy', 'wp-ultimo'),
	__('Livny', 'wp-ultimo'),
	__('Maloarkhangel’sk', 'wp-ultimo'),
	__('Mtsensk', 'wp-ultimo'),
	__('Naryshkino', 'wp-ultimo'),
	__('Novosil’', 'wp-ultimo'),
	__('Orël', 'wp-ultimo'),
	__('Pokrovskoye', 'wp-ultimo'),
	__('Shablykino', 'wp-ultimo'),
	__('Soskovo', 'wp-ultimo'),
	__('Spasskoye-Lutovinovo', 'wp-ultimo'),
	__('Trosna', 'wp-ultimo'),
	__('Verkhov’ye', 'wp-ultimo'),
	__('Vyshneye Dolgoye', 'wp-ultimo'),
	__('Zalegoshch’', 'wp-ultimo'),
	__('Zmiyëvka', 'wp-ultimo'),
	__('Znamenka', 'wp-ultimo'),
	__('Znamenskoye', 'wp-ultimo'),
);
