<?php
/**
 * State City List for PER - RU.
 *
 * City count: 83
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for PER - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Aleksandrovsk', 'wp-ultimo'),
	__('Barda', 'wp-ultimo'),
	__('Berezniki', 'wp-ultimo'),
	__('Bershet’', 'wp-ultimo'),
	__('Chastyye', 'wp-ultimo'),
	__('Chaykovskaya', 'wp-ultimo'),
	__('Chaykovskiy', 'wp-ultimo'),
	__('Cherdyn’', 'wp-ultimo'),
	__('Chermoz', 'wp-ultimo'),
	__('Chernushka', 'wp-ultimo'),
	__('Chusovoy', 'wp-ultimo'),
	__('Dobryanka', 'wp-ultimo'),
	__('Ferma', 'wp-ultimo'),
	__('Filippovka', 'wp-ultimo'),
	__('Foki', 'wp-ultimo'),
	__('Froly', 'wp-ultimo'),
	__('Gamovo', 'wp-ultimo'),
	__('Gayny', 'wp-ultimo'),
	__('Gornozavodsk', 'wp-ultimo'),
	__('Gremyachinsk', 'wp-ultimo'),
	__('Gubakha', 'wp-ultimo'),
	__('Kalino', 'wp-ultimo'),
	__('Karagay', 'wp-ultimo'),
	__('Kerchevskiy', 'wp-ultimo'),
	__('Kizel', 'wp-ultimo'),
	__('Kochevo', 'wp-ultimo'),
	__('Komarikhinskiy', 'wp-ultimo'),
	__('Kondratovo', 'wp-ultimo'),
	__('Kosa', 'wp-ultimo'),
	__('Krasnokamsk', 'wp-ultimo'),
	__('Krasnovishersk', 'wp-ultimo'),
	__('Kudymkar', 'wp-ultimo'),
	__('Kukushtan', 'wp-ultimo'),
	__('Kultayevo', 'wp-ultimo'),
	__('Kungur', 'wp-ultimo'),
	__('Kuyeda', 'wp-ultimo'),
	__('Lobanovo', 'wp-ultimo'),
	__('Lyamino', 'wp-ultimo'),
	__('Lys’va', 'wp-ultimo'),
	__('Maykor', 'wp-ultimo'),
	__('Mendeleyevo', 'wp-ultimo'),
	__('Novyye Lyady', 'wp-ultimo'),
	__('Nyrob', 'wp-ultimo'),
	__('Nytva', 'wp-ultimo'),
	__('Ochër', 'wp-ultimo'),
	__('Okhansk', 'wp-ultimo'),
	__('Orda', 'wp-ultimo'),
	__('Osa', 'wp-ultimo'),
	__('Overyata', 'wp-ultimo'),
	__('Pashiya', 'wp-ultimo'),
	__('Pavlovskiy', 'wp-ultimo'),
	__('Perm', 'wp-ultimo'),
	__('Polazna', 'wp-ultimo'),
	__('Pozhva', 'wp-ultimo'),
	__('Sarany', 'wp-ultimo'),
	__('Sars', 'wp-ultimo'),
	__('Severnyy-Kospashskiy', 'wp-ultimo'),
	__('Shakhta', 'wp-ultimo'),
	__('Shirokovskiy', 'wp-ultimo'),
	__('Shumikhinskiy', 'wp-ultimo'),
	__('Siva', 'wp-ultimo'),
	__('Sokol', 'wp-ultimo'),
	__('Solikamsk', 'wp-ultimo'),
	__('Suksun', 'wp-ultimo'),
	__('Sylva', 'wp-ultimo'),
	__('Tëplaya Gora', 'wp-ultimo'),
	__('Ugleural’skiy', 'wp-ultimo'),
	__('Uinskoye', 'wp-ultimo'),
	__('Usol’ye', 'wp-ultimo'),
	__('Ust’-Kachka', 'wp-ultimo'),
	__('Ust’-Kishert’', 'wp-ultimo'),
	__('Vereshchagino', 'wp-ultimo'),
	__('Verkhnechusovskiye Gorodki', 'wp-ultimo'),
	__('Yayva', 'wp-ultimo'),
	__('Yelovo', 'wp-ultimo'),
	__('Yubileynyy', 'wp-ultimo'),
	__('Yug', 'wp-ultimo'),
	__('Yugo-Kamskiy', 'wp-ultimo'),
	__('Yurla', 'wp-ultimo'),
	__('Yus’vinskiy Rayon', 'wp-ultimo'),
	__('Yuzhnyy-Kospashskiy', 'wp-ultimo'),
	__('Zvëzdnyy', 'wp-ultimo'),
	__('Zyukayka', 'wp-ultimo'),
);
