<?php
/**
 * State City List for PNZ - RU.
 *
 * City count: 47
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for PNZ - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Bashmakovo', 'wp-ultimo'),
	__('Bekovo', 'wp-ultimo'),
	__('Belinskiy', 'wp-ultimo'),
	__('Bessonovka', 'wp-ultimo'),
	__('Bogoslovka', 'wp-ultimo'),
	__('Chaadayevka', 'wp-ultimo'),
	__('Chemodanovka', 'wp-ultimo'),
	__('Gorodishche', 'wp-ultimo'),
	__('Grabovo', 'wp-ultimo'),
	__('Inderka', 'wp-ultimo'),
	__('Issa', 'wp-ultimo'),
	__('Issinskiy Rayon', 'wp-ultimo'),
	__('Kanayevka', 'wp-ultimo'),
	__('Kolyshley', 'wp-ultimo'),
	__('Kondol’', 'wp-ultimo'),
	__('Kuznetsk', 'wp-ultimo'),
	__('Kuznetskiy Rayon', 'wp-ultimo'),
	__('Lermontovo', 'wp-ultimo'),
	__('Lopatino', 'wp-ultimo'),
	__('Lunino', 'wp-ultimo'),
	__('Makhalino', 'wp-ultimo'),
	__('Malaya Serdoba', 'wp-ultimo'),
	__('Mokshan', 'wp-ultimo'),
	__('Narovchat', 'wp-ultimo'),
	__('Neverkino', 'wp-ultimo'),
	__('Neverkinskiy Rayon', 'wp-ultimo'),
	__('Nikol’sk', 'wp-ultimo'),
	__('Nizhniy Lomov', 'wp-ultimo'),
	__('Pachelma', 'wp-ultimo'),
	__('Penza', 'wp-ultimo'),
	__('Poim', 'wp-ultimo'),
	__('Poselki', 'wp-ultimo'),
	__('Russkiy Kameshkir', 'wp-ultimo'),
	__('Serdobsk', 'wp-ultimo'),
	__('Shemysheyka', 'wp-ultimo'),
	__('Sosnovoborsk', 'wp-ultimo'),
	__('Spassk', 'wp-ultimo'),
	__('Srednyaya Yelyuzan’', 'wp-ultimo'),
	__('Sura', 'wp-ultimo'),
	__('Sursk', 'wp-ultimo'),
	__('Tamala', 'wp-ultimo'),
	__('Vadinsk', 'wp-ultimo'),
	__('Verkhniy Lomov', 'wp-ultimo'),
	__('Verkhozim', 'wp-ultimo'),
	__('Zarechnyy', 'wp-ultimo'),
	__('Zasechnoye', 'wp-ultimo'),
	__('Zemetchino', 'wp-ultimo'),
);
