<?php
/**
 * State City List for PRI - RU.
 *
 * City count: 96
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for PRI - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Anuchino', 'wp-ultimo'),
	__('Anuchinskiy Rayon', 'wp-ultimo'),
	__('Arsen’yev', 'wp-ultimo'),
	__('Artëm', 'wp-ultimo'),
	__('Barabash', 'wp-ultimo'),
	__('Blagodatnoye', 'wp-ultimo'),
	__('Bol’shoy Kamen’', 'wp-ultimo'),
	__('Chernigovka', 'wp-ultimo'),
	__('Chernigovskiy Rayon', 'wp-ultimo'),
	__('Chernyshëvka', 'wp-ultimo'),
	__('Chkalovskoye', 'wp-ultimo'),
	__('Chuguyevka', 'wp-ultimo'),
	__('Dalnegorsk', 'wp-ultimo'),
	__('Dalnerechensk', 'wp-ultimo'),
	__('Dostoyevka', 'wp-ultimo'),
	__('Dunay', 'wp-ultimo'),
	__('Emar', 'wp-ultimo'),
	__('Fokino', 'wp-ultimo'),
	__('Gornorechenskiy', 'wp-ultimo'),
	__('Gornyye Klyuchi', 'wp-ultimo'),
	__('Grazhdanka', 'wp-ultimo'),
	__('Ivanovka', 'wp-ultimo'),
	__('Kamenka', 'wp-ultimo'),
	__('Kamen’-Rybolov', 'wp-ultimo'),
	__('Kavalerovo', 'wp-ultimo'),
	__('Khasanskiy Rayon', 'wp-ultimo'),
	__('Khorol’', 'wp-ultimo'),
	__('Kirovskiy', 'wp-ultimo'),
	__('Knevichi', 'wp-ultimo'),
	__('Kraskino', 'wp-ultimo'),
	__('Krasnorechenskiy', 'wp-ultimo'),
	__('Lazo', 'wp-ultimo'),
	__('Lazovskiy Rayon', 'wp-ultimo'),
	__('Lesozavodsk', 'wp-ultimo'),
	__('Lipovtsy', 'wp-ultimo'),
	__('Livadiya', 'wp-ultimo'),
	__('Luchegorsk', 'wp-ultimo'),
	__('Luchki', 'wp-ultimo'),
	__('Lyalichi', 'wp-ultimo'),
	__('Mikhaylovka', 'wp-ultimo'),
	__('Mikhaylovskiy Rayon', 'wp-ultimo'),
	__('Mnogoudobnoye', 'wp-ultimo'),
	__('Monastyrishche', 'wp-ultimo'),
	__('Nadezhdinskiy Rayon', 'wp-ultimo'),
	__('Nakhodka', 'wp-ultimo'),
	__('Novonikol’sk', 'wp-ultimo'),
	__('Novopokrovka', 'wp-ultimo'),
	__('Novoshakhtinskiy', 'wp-ultimo'),
	__('Novosysoyevka', 'wp-ultimo'),
	__('Novyy', 'wp-ultimo'),
	__('Ol’ga', 'wp-ultimo'),
	__('Partizansk', 'wp-ultimo'),
	__('Plastun', 'wp-ultimo'),
	__('Pogranichnyy', 'wp-ultimo'),
	__('Pokrovka', 'wp-ultimo'),
	__('Popova', 'wp-ultimo'),
	__('Preobrazheniye', 'wp-ultimo'),
	__('Primorskiy', 'wp-ultimo'),
	__('Putyatin', 'wp-ultimo'),
	__('Razdol’noye', 'wp-ultimo'),
	__('Rettikhovka', 'wp-ultimo'),
	__('Romanovka', 'wp-ultimo'),
	__('Rudnaya Pristan’', 'wp-ultimo'),
	__('Rudnyy', 'wp-ultimo'),
	__('Russkiy', 'wp-ultimo'),
	__('Sergeyevka', 'wp-ultimo'),
	__('Shkotovo', 'wp-ultimo'),
	__('Shkotovskiy Rayon', 'wp-ultimo'),
	__('Shtykovo', 'wp-ultimo'),
	__('Sivakovka', 'wp-ultimo'),
	__('Slavyanka', 'wp-ultimo'),
	__('Smolyaninovo', 'wp-ultimo'),
	__('Spassk-Dal’niy', 'wp-ultimo'),
	__('Spasskiy Rayon', 'wp-ultimo'),
	__('Spasskoye', 'wp-ultimo'),
	__('Svetlaya', 'wp-ultimo'),
	__('Tavrichanka', 'wp-ultimo'),
	__('Terney', 'wp-ultimo'),
	__('Trudovoye', 'wp-ultimo'),
	__('Uglekamensk', 'wp-ultimo'),
	__('Uglovoye', 'wp-ultimo'),
	__('Ussuriysk', 'wp-ultimo'),
	__('Vladimiro-Aleksandrovskoye', 'wp-ultimo'),
	__('Vladivostok', 'wp-ultimo'),
	__('Volchanets', 'wp-ultimo'),
	__('Vol’no-Nadezhdinskoye', 'wp-ultimo'),
	__('Vostok', 'wp-ultimo'),
	__('Vozdvizhenka', 'wp-ultimo'),
	__('Vrangel’', 'wp-ultimo'),
	__('Yakovlevka', 'wp-ultimo'),
	__('Yakovlevskiy Rayon', 'wp-ultimo'),
	__('Yaroslavskiy', 'wp-ultimo'),
	__('Yekaterinovka', 'wp-ultimo'),
	__('Zarubino', 'wp-ultimo'),
	__('Zavodskoy', 'wp-ultimo'),
	__('Zharikovo', 'wp-ultimo'),
);
