<?php
/**
 * State City List for PSK - RU.
 *
 * City count: 44
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for PSK - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Bezhanitsy', 'wp-ultimo'),
	__('Dedovichi', 'wp-ultimo'),
	__('Dno', 'wp-ultimo'),
	__('Gdov', 'wp-ultimo'),
	__('Gdovskiy Rayon', 'wp-ultimo'),
	__('Idritsa', 'wp-ultimo'),
	__('Izborsk', 'wp-ultimo'),
	__('Krasnogorodsk', 'wp-ultimo'),
	__('Krasnyy Luch', 'wp-ultimo'),
	__('Kun’inskiy Rayon', 'wp-ultimo'),
	__('Loknya', 'wp-ultimo'),
	__('Nevel’', 'wp-ultimo'),
	__('Novorzhev', 'wp-ultimo'),
	__('Novorzhevskiy Rayon', 'wp-ultimo'),
	__('Novosokol’nicheskiy Rayon', 'wp-ultimo'),
	__('Novosokol’niki', 'wp-ultimo'),
	__('Novyy Izborsk', 'wp-ultimo'),
	__('Opochka', 'wp-ultimo'),
	__('Ostrov', 'wp-ultimo'),
	__('Ostrovskiy Rayon', 'wp-ultimo'),
	__('Palkino', 'wp-ultimo'),
	__('Palkinskiy Rayon', 'wp-ultimo'),
	__('Pechorskiy Rayon', 'wp-ultimo'),
	__('Pechory', 'wp-ultimo'),
	__('Plyussa', 'wp-ultimo'),
	__('Porkhov', 'wp-ultimo'),
	__('Porkhovskiy Rayon', 'wp-ultimo'),
	__('Pskov', 'wp-ultimo'),
	__('Pskovskiy Rayon', 'wp-ultimo'),
	__('Pushkino-Gorskiy Rayon', 'wp-ultimo'),
	__('Pushkinskiye Gory', 'wp-ultimo'),
	__('Pustoshka', 'wp-ultimo'),
	__('Pustoshkinskiy Rayon', 'wp-ultimo'),
	__('Pytalovo', 'wp-ultimo'),
	__('Pytalovskiy Rayon', 'wp-ultimo'),
	__('Sebezh', 'wp-ultimo'),
	__('Sebezhskiy Rayon', 'wp-ultimo'),
	__('Serëdka', 'wp-ultimo'),
	__('Strugi-Krasnyye', 'wp-ultimo'),
	__('Strugo-Krasnenskiy Rayon', 'wp-ultimo'),
	__('Usvyaty', 'wp-ultimo'),
	__('Velikiye Luki', 'wp-ultimo'),
	__('Velikolukskiy Rayon', 'wp-ultimo'),
	__('Vybor', 'wp-ultimo'),
);
