<?php
/**
 * State City List for RYA - RU.
 *
 * City count: 48
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for RYA - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Aleksandro-Nevskiy', 'wp-ultimo'),
	__('Bagramovo', 'wp-ultimo'),
	__('Chuchkovo', 'wp-ultimo'),
	__('Gus’-Zheleznyy', 'wp-ultimo'),
	__('Izhevskoye', 'wp-ultimo'),
	__('Kadom', 'wp-ultimo'),
	__('Kasimov', 'wp-ultimo'),
	__('Kasimovskiy Rayon', 'wp-ultimo'),
	__('Kiritsy', 'wp-ultimo'),
	__('Klepikovskiy Rayon', 'wp-ultimo'),
	__('Korablino', 'wp-ultimo'),
	__('Lashma', 'wp-ultimo'),
	__('Lesnoy', 'wp-ultimo'),
	__('Mikhaylov', 'wp-ultimo'),
	__('Miloslavskoye', 'wp-ultimo'),
	__('Murmino', 'wp-ultimo'),
	__('Novomichurinsk', 'wp-ultimo'),
	__('Oktyabr’skiy', 'wp-ultimo'),
	__('Pavelets', 'wp-ultimo'),
	__('Pitelino', 'wp-ultimo'),
	__('Polyany', 'wp-ultimo'),
	__('Pronsk', 'wp-ultimo'),
	__('Putyatino', 'wp-ultimo'),
	__('Ryazanskiy Rayon', 'wp-ultimo'),
	__('Ryazan’', 'wp-ultimo'),
	__('Ryazhsk', 'wp-ultimo'),
	__('Rybnovskiy Rayon', 'wp-ultimo'),
	__('Rybnoye', 'wp-ultimo'),
	__('Sapozhok', 'wp-ultimo'),
	__('Sarai', 'wp-ultimo'),
	__('Sasovo', 'wp-ultimo'),
	__('Shatsk', 'wp-ultimo'),
	__('Shilovo', 'wp-ultimo'),
	__('Skopin', 'wp-ultimo'),
	__('Solotcha', 'wp-ultimo'),
	__('Spas-Klepiki', 'wp-ultimo'),
	__('Spassk-Ryazanskiy', 'wp-ultimo'),
	__('Starozhilovo', 'wp-ultimo'),
	__('Syntul', 'wp-ultimo'),
	__('Tuma', 'wp-ultimo'),
	__('Ukholovo', 'wp-ultimo'),
	__('Vilenka', 'wp-ultimo'),
	__('Yambirno', 'wp-ultimo'),
	__('Yelat’ma', 'wp-ultimo'),
	__('Yermish’', 'wp-ultimo'),
	__('Zakharovo', 'wp-ultimo'),
	__('Zakharovskiy Rayon', 'wp-ultimo'),
	__('Zarechnyy', 'wp-ultimo'),
);
