<?php
/**
 * State City List for SA - RU.
 *
 * City count: 86
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for SA - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Abyysky District', 'wp-ultimo'),
	__('Aldan', 'wp-ultimo'),
	__('Allaikhovskiy Rayon', 'wp-ultimo'),
	__('Almaznyy', 'wp-ultimo'),
	__('Amga', 'wp-ultimo'),
	__('Anabarskiy Rayon', 'wp-ultimo'),
	__('Aykhal', 'wp-ultimo'),
	__('Batagay', 'wp-ultimo'),
	__('Batagay-Alyta', 'wp-ultimo'),
	__('Belaya Gora', 'wp-ultimo'),
	__('Berdigestyakh', 'wp-ultimo'),
	__('Berkakit', 'wp-ultimo'),
	__('Borogontsy', 'wp-ultimo'),
	__('Bulunskiy Rayon', 'wp-ultimo'),
	__('Chernyshevskiy', 'wp-ultimo'),
	__('Cherskiy', 'wp-ultimo'),
	__('Chokurdakh', 'wp-ultimo'),
	__('Chul’man', 'wp-ultimo'),
	__('Churapcha', 'wp-ultimo'),
	__('Deputatsky', 'wp-ultimo'),
	__('Dzhebariki-Khaya', 'wp-ultimo'),
	__('Eveno-Bytantaysky National District', 'wp-ultimo'),
	__('Gornyy Rayon', 'wp-ultimo'),
	__('Kangalassy', 'wp-ultimo'),
	__('Khandyga', 'wp-ultimo'),
	__('Khatassy', 'wp-ultimo'),
	__('Kobyayskiy Rayon', 'wp-ultimo'),
	__('Kysyl-Syr', 'wp-ultimo'),
	__('Lebedinyy', 'wp-ultimo'),
	__('Leninskiy', 'wp-ultimo'),
	__('Lensk', 'wp-ultimo'),
	__('Magan', 'wp-ultimo'),
	__('Markha', 'wp-ultimo'),
	__('Mayya', 'wp-ultimo'),
	__('Mirninskiy Rayon', 'wp-ultimo'),
	__('Mirny', 'wp-ultimo'),
	__('Mokhsogollokh', 'wp-ultimo'),
	__('Momsky District', 'wp-ultimo'),
	__('Namskiy Rayon', 'wp-ultimo'),
	__('Namtsy', 'wp-ultimo'),
	__('Neryungri', 'wp-ultimo'),
	__('Nezhdaninskoe', 'wp-ultimo'),
	__('Nizhniy Bestyakh', 'wp-ultimo'),
	__('Nizhniy Kuranakh', 'wp-ultimo'),
	__('Nyurba', 'wp-ultimo'),
	__('Nyurbinsky District', 'wp-ultimo'),
	__('Olenyok', 'wp-ultimo'),
	__('Olenyoksky District', 'wp-ultimo'),
	__('Olyokminsk', 'wp-ultimo'),
	__('Olyokminsky District', 'wp-ultimo'),
	__('Oymyakonskiy District', 'wp-ultimo'),
	__('Peleduy', 'wp-ultimo'),
	__('Pokrovsk', 'wp-ultimo'),
	__('Sangar', 'wp-ultimo'),
	__('Saskylakh', 'wp-ultimo'),
	__('Serebryanyy Bor', 'wp-ultimo'),
	__('Solnechnyy', 'wp-ultimo'),
	__('Srednekolymsk', 'wp-ultimo'),
	__('Srednekolymsky District', 'wp-ultimo'),
	__('Suntar', 'wp-ultimo'),
	__('Suntarskiy District', 'wp-ultimo'),
	__('Tabaga', 'wp-ultimo'),
	__('Tiksi', 'wp-ultimo'),
	__('Tommot', 'wp-ultimo'),
	__('Tomponskiy District', 'wp-ultimo'),
	__('Udachny', 'wp-ultimo'),
	__('Ust-Aldansky District', 'wp-ultimo'),
	__('Ust-Kuyga', 'wp-ultimo'),
	__('Ust-Maya', 'wp-ultimo'),
	__('Ust-Nera', 'wp-ultimo'),
	__('Ust’-Yanskiy Rayon', 'wp-ultimo'),
	__('Verkhnekolymsky District', 'wp-ultimo'),
	__('Verkhnevilyuysk', 'wp-ultimo'),
	__('Verkhnevilyuysky District', 'wp-ultimo'),
	__('Verkhoyansk', 'wp-ultimo'),
	__('Verkhoyansky District', 'wp-ultimo'),
	__('Vilyuysk', 'wp-ultimo'),
	__('Vilyuyskiy Rayon', 'wp-ultimo'),
	__('Vilyuysky District', 'wp-ultimo'),
	__('Vitim', 'wp-ultimo'),
	__('Yakutsk', 'wp-ultimo'),
	__('Ytyk-Kyuyël’', 'wp-ultimo'),
	__('Zhatay', 'wp-ultimo'),
	__('Zhigansk', 'wp-ultimo'),
	__('Zhigansky District', 'wp-ultimo'),
	__('Zyryanka', 'wp-ultimo'),
);
