<?php
/**
 * State City List for SAK - RU.
 *
 * City count: 42
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for SAK - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Aleksandrovsk-Sakhalinskiy', 'wp-ultimo'),
	__('Aniva', 'wp-ultimo'),
	__('Boshnyakovo', 'wp-ultimo'),
	__('Bykov', 'wp-ultimo'),
	__('Chekhov', 'wp-ultimo'),
	__('Dolinsk', 'wp-ultimo'),
	__('Gastello', 'wp-ultimo'),
	__('Gornozavodsk', 'wp-ultimo'),
	__('Kholmsk', 'wp-ultimo'),
	__('Korsakov', 'wp-ultimo'),
	__('Krasnogorsk', 'wp-ultimo'),
	__('Kurilsky District', 'wp-ultimo'),
	__('Kuril’sk', 'wp-ultimo'),
	__('Leonidovo', 'wp-ultimo'),
	__('Makarov', 'wp-ultimo'),
	__('Mgachi', 'wp-ultimo'),
	__('Nevel’sk', 'wp-ultimo'),
	__('Nogliki', 'wp-ultimo'),
	__('Okha', 'wp-ultimo'),
	__('Otrada', 'wp-ultimo'),
	__('Poronaysk', 'wp-ultimo'),
	__('Pravda', 'wp-ultimo'),
	__('Severo-Kuril’sk', 'wp-ultimo'),
	__('Shakhtersk', 'wp-ultimo'),
	__('Shebunino', 'wp-ultimo'),
	__('Shikotan', 'wp-ultimo'),
	__('Sinegorsk', 'wp-ultimo'),
	__('Smirnykh', 'wp-ultimo'),
	__('Sokol', 'wp-ultimo'),
	__('Tomari', 'wp-ultimo'),
	__('Troitskoye', 'wp-ultimo'),
	__('Tungor', 'wp-ultimo'),
	__('Tymovskoye', 'wp-ultimo'),
	__('Uglegorsk', 'wp-ultimo'),
	__('Uglegorskiy Rayon', 'wp-ultimo'),
	__('Uglezavodsk', 'wp-ultimo'),
	__('Vakhrushev', 'wp-ultimo'),
	__('Vostok', 'wp-ultimo'),
	__('Yablochnyy', 'wp-ultimo'),
	__('Yuzhno-Kurilsk', 'wp-ultimo'),
	__('Yuzhno-Kurilsky District', 'wp-ultimo'),
	__('Yuzhno-Sakhalinsk', 'wp-ultimo'),
);
