<?php
/**
 * State City List for SAM - RU.
 *
 * City count: 64
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for SAM - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Bakhilovo', 'wp-ultimo'),
	__('Balasheyka', 'wp-ultimo'),
	__('Berëza', 'wp-ultimo'),
	__('Bezenchuk', 'wp-ultimo'),
	__('Bogatoye', 'wp-ultimo'),
	__('Bogatyr’', 'wp-ultimo'),
	__('Borskoye', 'wp-ultimo'),
	__('Chapayevsk', 'wp-ultimo'),
	__('Chelno-Vershiny', 'wp-ultimo'),
	__('Dubovyy Umët', 'wp-ultimo'),
	__('Georgiyevka', 'wp-ultimo'),
	__('Isakly', 'wp-ultimo'),
	__('Kamyshla', 'wp-ultimo'),
	__('Khryashchevka', 'wp-ultimo'),
	__('Khvorostyanka', 'wp-ultimo'),
	__('Kinel’', 'wp-ultimo'),
	__('Kinel’-Cherkassy', 'wp-ultimo'),
	__('Kinel’skiy Rayon', 'wp-ultimo'),
	__('Klyavlino', 'wp-ultimo'),
	__('Koshki', 'wp-ultimo'),
	__('Krasnoarmeyskoye', 'wp-ultimo'),
	__('Krasnoyarskiy Rayon', 'wp-ultimo'),
	__('Krasnyy Yar', 'wp-ultimo'),
	__('Krotovka', 'wp-ultimo'),
	__('Kurumoch', 'wp-ultimo'),
	__('Mayskoye', 'wp-ultimo'),
	__('Mezhdurechensk', 'wp-ultimo'),
	__('Mirnyy', 'wp-ultimo'),
	__('Neftegorsk', 'wp-ultimo'),
	__('Neftegorskiy Rayon', 'wp-ultimo'),
	__('Novokuybyshevsk', 'wp-ultimo'),
	__('Novosemeykino', 'wp-ultimo'),
	__('Novyy Buyan', 'wp-ultimo'),
	__('Obsharovka', 'wp-ultimo'),
	__('Oktyabr’sk', 'wp-ultimo'),
	__('Osinki', 'wp-ultimo'),
	__('Otradnyy', 'wp-ultimo'),
	__('Perevoloki', 'wp-ultimo'),
	__('Pestravka', 'wp-ultimo'),
	__('Petra-Dubrava', 'wp-ultimo'),
	__('Podsolnechnoye', 'wp-ultimo'),
	__('Podstepki', 'wp-ultimo'),
	__('Pokhvistnevo', 'wp-ultimo'),
	__('Povolzhskiy', 'wp-ultimo'),
	__('Pribrezhnyy', 'wp-ultimo'),
	__('Roschinskiy', 'wp-ultimo'),
	__('Rozhdestveno', 'wp-ultimo'),
	__('Samara', 'wp-ultimo'),
	__('Sernovodsk', 'wp-ultimo'),
	__('Shentala', 'wp-ultimo'),
	__('Shigony', 'wp-ultimo'),
	__('Smyshlyayevka', 'wp-ultimo'),
	__('Spiridonovka', 'wp-ultimo'),
	__('Sukhodol', 'wp-ultimo'),
	__('Surgut', 'wp-ultimo'),
	__('Syzran’', 'wp-ultimo'),
	__('Tol’yatti', 'wp-ultimo'),
	__('Utevka', 'wp-ultimo'),
	__('Varlamovo', 'wp-ultimo'),
	__('Volzhskiy', 'wp-ultimo'),
	__('Yelkhovka', 'wp-ultimo'),
	__('Zhigulevsk', 'wp-ultimo'),
	__('Zhiguli', 'wp-ultimo'),
	__('Zol’noye', 'wp-ultimo'),
);
