<?php
/**
 * State City List for SAR - RU.
 *
 * City count: 71
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for SAR - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Aleksandrov Gay', 'wp-ultimo'),
	__('Alekseyevka', 'wp-ultimo'),
	__('Arkadak', 'wp-ultimo'),
	__('Atkarsk', 'wp-ultimo'),
	__('Atkarskiy Rayon', 'wp-ultimo'),
	__('Balakovo', 'wp-ultimo'),
	__('Balashov', 'wp-ultimo'),
	__('Baltay', 'wp-ultimo'),
	__('Baltayskiy Rayon', 'wp-ultimo'),
	__('Bazarno-Karabulakskiy Rayon', 'wp-ultimo'),
	__('Bazarnyy Karabulak', 'wp-ultimo'),
	__('Bol’shoy Karay', 'wp-ultimo'),
	__('Cherkasskoye', 'wp-ultimo'),
	__('Dergachi', 'wp-ultimo'),
	__('Dukhovnitskoye', 'wp-ultimo'),
	__('Engel’s', 'wp-ultimo'),
	__('Engel’sskiy Rayon', 'wp-ultimo'),
	__('Gornyy', 'wp-ultimo'),
	__('Ivanteyevka', 'wp-ultimo'),
	__('Kalininsk', 'wp-ultimo'),
	__('Kamenskiy', 'wp-ultimo'),
	__('Khvalynsk', 'wp-ultimo'),
	__('Khvalynskiy Rayon', 'wp-ultimo'),
	__('Khvatovka', 'wp-ultimo'),
	__('Kormëzhka', 'wp-ultimo'),
	__('Krasnoarmeysk', 'wp-ultimo'),
	__('Krasnyy Kut', 'wp-ultimo'),
	__('Krasnyy Oktyabr’', 'wp-ultimo'),
	__('Krasnyy Yar', 'wp-ultimo'),
	__('Lysyye Gory', 'wp-ultimo'),
	__('Marks', 'wp-ultimo'),
	__('Marksovskiy Rayon', 'wp-ultimo'),
	__('Mokrous', 'wp-ultimo'),
	__('Novouzensk', 'wp-ultimo'),
	__('Novyye Burasy', 'wp-ultimo'),
	__('Perelyub', 'wp-ultimo'),
	__('Petrovsk', 'wp-ultimo'),
	__('Pinerovka', 'wp-ultimo'),
	__('Piterka', 'wp-ultimo'),
	__('Podlesnoye', 'wp-ultimo'),
	__('Privolzhskiy', 'wp-ultimo'),
	__('Privolzhskoye', 'wp-ultimo'),
	__('Pugachev', 'wp-ultimo'),
	__('Pushkino', 'wp-ultimo'),
	__('Repnoye', 'wp-ultimo'),
	__('Romanovka', 'wp-ultimo'),
	__('Rovnoye', 'wp-ultimo'),
	__('Rtishchevo', 'wp-ultimo'),
	__('Samoylovka', 'wp-ultimo'),
	__('Saratov', 'wp-ultimo'),
	__('Saratovskiy Rayon', 'wp-ultimo'),
	__('Sennoy', 'wp-ultimo'),
	__('Shikhany', 'wp-ultimo'),
	__('Shumeyka', 'wp-ultimo'),
	__('Sinodskoye', 'wp-ultimo'),
	__('Sokolovyy', 'wp-ultimo'),
	__('Sovetskoye', 'wp-ultimo'),
	__('Staryye Ozinki', 'wp-ultimo'),
	__('Stepnoye', 'wp-ultimo'),
	__('Svetlyy', 'wp-ultimo'),
	__('Svobodnyy', 'wp-ultimo'),
	__('Tatishchevo', 'wp-ultimo'),
	__('Tersa', 'wp-ultimo'),
	__('Turki', 'wp-ultimo'),
	__('Vol’sk', 'wp-ultimo'),
	__('Vol’skiy Rayon', 'wp-ultimo'),
	__('Voskresenskiy Rayon', 'wp-ultimo'),
	__('Voskresenskoye', 'wp-ultimo'),
	__('Yekaterinovka', 'wp-ultimo'),
	__('Yelshanka', 'wp-ultimo'),
	__('Yershov', 'wp-ultimo'),
);
