<?php
/**
 * State City List for SE - RU.
 *
 * City count: 31
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for SE - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Alagir', 'wp-ultimo'),
	__('Alagirskiy Rayon', 'wp-ultimo'),
	__('Ardon', 'wp-ultimo'),
	__('Arkhonskaya', 'wp-ultimo'),
	__('Beslan', 'wp-ultimo'),
	__('Chermen', 'wp-ultimo'),
	__('Chikola', 'wp-ultimo'),
	__('Dachnoye', 'wp-ultimo'),
	__('Digora', 'wp-ultimo'),
	__('Digorskiy Rayon', 'wp-ultimo'),
	__('Gizel’', 'wp-ultimo'),
	__('Irafskiy Rayon', 'wp-ultimo'),
	__('Kambileyevskoye', 'wp-ultimo'),
	__('Kardzhin', 'wp-ultimo'),
	__('Khumalag', 'wp-ultimo'),
	__('Kirovskiy Rayon', 'wp-ultimo'),
	__('Kizlyar', 'wp-ultimo'),
	__('Mikhaylovskoye', 'wp-ultimo'),
	__('Mizur', 'wp-ultimo'),
	__('Mozdok', 'wp-ultimo'),
	__('Nogir', 'wp-ultimo'),
	__('Pavlodol’skaya', 'wp-ultimo'),
	__('Pravoberezhnyy Rayon', 'wp-ultimo'),
	__('Prigorodnyy Rayon', 'wp-ultimo'),
	__('Sunzha', 'wp-ultimo'),
	__('Tarskoye', 'wp-ultimo'),
	__('Terskaya', 'wp-ultimo'),
	__('Troitskoye', 'wp-ultimo'),
	__('Verkhniy Fiagdon', 'wp-ultimo'),
	__('Vladikavkaz', 'wp-ultimo'),
	__('Zmeyskaya', 'wp-ultimo'),
);
