<?php
/**
 * State City List for SMO - RU.
 *
 * City count: 36
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for SMO - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Demidov', 'wp-ultimo'),
	__('Desnogorsk', 'wp-ultimo'),
	__('Dorogobuzh', 'wp-ultimo'),
	__('Dukhovshchina', 'wp-ultimo'),
	__('Gagarin', 'wp-ultimo'),
	__('Glinka', 'wp-ultimo'),
	__('Golynki', 'wp-ultimo'),
	__('Kardymovo', 'wp-ultimo'),
	__("Katyn'", 'wp-ultimo'),
	__('Khislavichi', 'wp-ultimo'),
	__('Kholm-Zhirkovskiy', 'wp-ultimo'),
	__('Monastyrshchina', 'wp-ultimo'),
	__('Novodugino', 'wp-ultimo'),
	__('Oster', 'wp-ultimo'),
	__('Ozërnyy', 'wp-ultimo'),
	__('Pechersk', 'wp-ultimo'),
	__('Pochinok', 'wp-ultimo'),
	__('Roslavl’', 'wp-ultimo'),
	__('Rudnya', 'wp-ultimo'),
	__('Safonovo', 'wp-ultimo'),
	__('Safonovskiy Rayon', 'wp-ultimo'),
	__('Shatalovo', 'wp-ultimo'),
	__('Shumyachi', 'wp-ultimo'),
	__('Smolensk', 'wp-ultimo'),
	__('Stodolishche', 'wp-ultimo'),
	__('Sychëvka', 'wp-ultimo'),
	__('Talashkino', 'wp-ultimo'),
	__('Tëmkino', 'wp-ultimo'),
	__('Ugra', 'wp-ultimo'),
	__('Velizh', 'wp-ultimo'),
	__('Verkhnedneprovskiy', 'wp-ultimo'),
	__('Vyaz’ma', 'wp-ultimo'),
	__('Yartsevo', 'wp-ultimo'),
	__('Yekimovichi', 'wp-ultimo'),
	__('Yel’nya', 'wp-ultimo'),
	__('Yershichi', 'wp-ultimo'),
);
