<?php
/**
 * State City List for TAM - RU.
 *
 * City count: 35
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for TAM - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Bokino', 'wp-ultimo'),
	__('Bondarskiy Rayon', 'wp-ultimo'),
	__('Donskoye', 'wp-ultimo'),
	__('Gavrilovka Vtoraya', 'wp-ultimo'),
	__('Goreloye', 'wp-ultimo'),
	__('Inzhavino', 'wp-ultimo'),
	__('Kirsanov', 'wp-ultimo'),
	__('Kirsanovskiy Rayon', 'wp-ultimo'),
	__('Komsomolets', 'wp-ultimo'),
	__('Kotovsk', 'wp-ultimo'),
	__('Michurinsk', 'wp-ultimo'),
	__('Mordovo', 'wp-ultimo'),
	__('Morshansk', 'wp-ultimo'),
	__('Muchkapskiy', 'wp-ultimo'),
	__('Novaya Lyada', 'wp-ultimo'),
	__('Novopokrovka', 'wp-ultimo'),
	__('Pervomayskiy', 'wp-ultimo'),
	__('Pichayevo', 'wp-ultimo'),
	__('Platonovka', 'wp-ultimo'),
	__('Pokrovo-Prigorodnoye', 'wp-ultimo'),
	__('Rasskazovo', 'wp-ultimo'),
	__('Rasskazovskiy Rayon', 'wp-ultimo'),
	__('Rzhaksa', 'wp-ultimo'),
	__('Sampurskiy Rayon', 'wp-ultimo'),
	__('Satinka', 'wp-ultimo'),
	__('Selezni', 'wp-ultimo'),
	__('Sosnovka', 'wp-ultimo'),
	__('Staroyur’yevo', 'wp-ultimo'),
	__('Tambov', 'wp-ultimo'),
	__('Tokarevskiy Rayon', 'wp-ultimo'),
	__('Uvarovo', 'wp-ultimo'),
	__('Zavoronezhskoye', 'wp-ultimo'),
	__('Zherdevka', 'wp-ultimo'),
	__('Znamenka', 'wp-ultimo'),
	__('Znamenskiy Rayon', 'wp-ultimo'),
);
