<?php
/**
 * State City List for TOM - RU.
 *
 * City count: 30
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for TOM - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Aleksandrovskoye', 'wp-ultimo'),
	__('Asino', 'wp-ultimo'),
	__('Bakchar', 'wp-ultimo'),
	__('Belyy Yar', 'wp-ultimo'),
	__('Bogashevo', 'wp-ultimo'),
	__('Kaltay', 'wp-ultimo'),
	__('Kargasok', 'wp-ultimo'),
	__('Kedrovyy', 'wp-ultimo'),
	__('Kolpashevo', 'wp-ultimo'),
	__('Kozhevnikovo', 'wp-ultimo'),
	__('Krasnyy Yar', 'wp-ultimo'),
	__('Krivosheino', 'wp-ultimo'),
	__('Mel’nikovo', 'wp-ultimo'),
	__('Molchanovo', 'wp-ultimo'),
	__('Molchanovskiy Rayon', 'wp-ultimo'),
	__('Moryakovskiy Zaton', 'wp-ultimo'),
	__('Parabel’', 'wp-ultimo'),
	__('Pervomayskoye', 'wp-ultimo'),
	__('Podgornoye', 'wp-ultimo'),
	__('Samus’', 'wp-ultimo'),
	__('Seversk', 'wp-ultimo'),
	__('Strezhevoy', 'wp-ultimo'),
	__('Svetlyy', 'wp-ultimo'),
	__('Tegul’det', 'wp-ultimo'),
	__('Tegul’detskiy Rayon', 'wp-ultimo'),
	__('Timiryazevskoye', 'wp-ultimo'),
	__('Togur', 'wp-ultimo'),
	__('Tomsk', 'wp-ultimo'),
	__('Tomskiy Rayon', 'wp-ultimo'),
	__('Zyryanskoye', 'wp-ultimo'),
);
