<?php
/**
 * State City List for TUL - RU.
 *
 * City count: 64
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for TUL - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Ageyevo', 'wp-ultimo'),
	__('Aleksin', 'wp-ultimo'),
	__('Aleksinskiy Rayon', 'wp-ultimo'),
	__('Arsen’yevo', 'wp-ultimo'),
	__('Barsuki', 'wp-ultimo'),
	__('Begichevskiy', 'wp-ultimo'),
	__('Belëv', 'wp-ultimo'),
	__('Bogoroditsk', 'wp-ultimo'),
	__('Bolokhovo', 'wp-ultimo'),
	__('Bol’shoye Skuratovo', 'wp-ultimo'),
	__('Borodinskiy', 'wp-ultimo'),
	__('Brusyanka', 'wp-ultimo'),
	__('Chekalin', 'wp-ultimo'),
	__('Cherepet’', 'wp-ultimo'),
	__('Chern’', 'wp-ultimo'),
	__('Donskoy', 'wp-ultimo'),
	__('Dubna', 'wp-ultimo'),
	__('Dubovka', 'wp-ultimo'),
	__('Gorelki', 'wp-ultimo'),
	__('Gritsovskiy', 'wp-ultimo'),
	__('Kamenetskiy', 'wp-ultimo'),
	__('Kazachka', 'wp-ultimo'),
	__('Khanino', 'wp-ultimo'),
	__('Kimovsk', 'wp-ultimo'),
	__('Kireyevsk', 'wp-ultimo'),
	__('Kosaya Gora', 'wp-ultimo'),
	__('Krapivna', 'wp-ultimo'),
	__('Kurkino', 'wp-ultimo'),
	__('Leninskiy', 'wp-ultimo'),
	__('Lomintsevskiy', 'wp-ultimo'),
	__('Mayskiy', 'wp-ultimo'),
	__('Mendeleyevskiy', 'wp-ultimo'),
	__('Novogurovskiy', 'wp-ultimo'),
	__('Novomoskovsk', 'wp-ultimo'),
	__('Odoyev', 'wp-ultimo'),
	__('Partizan', 'wp-ultimo'),
	__('Pervomayskiy', 'wp-ultimo'),
	__('Plavsk', 'wp-ultimo'),
	__('Podlesnyy', 'wp-ultimo'),
	__('Priupskiy', 'wp-ultimo'),
	__('Revyakino', 'wp-ultimo'),
	__('Rozhdestvenskiy', 'wp-ultimo'),
	__('Severo-Zadonsk', 'wp-ultimo'),
	__('Shchëkino', 'wp-ultimo'),
	__('Shvartsevskiy', 'wp-ultimo'),
	__('Skuratovskiy', 'wp-ultimo'),
	__('Slavniy', 'wp-ultimo'),
	__('Suvorov', 'wp-ultimo'),
	__('Suvorovskiy Rayon', 'wp-ultimo'),
	__('Tovarkovskiy', 'wp-ultimo'),
	__('Tula', 'wp-ultimo'),
	__('Tëplo-Ogarëvskiy Rayon', 'wp-ultimo'),
	__('Tëploye', 'wp-ultimo'),
	__('Uzlovaya', 'wp-ultimo'),
	__('Venevskiy Rayon', 'wp-ultimo'),
	__('Venëv', 'wp-ultimo'),
	__('Volovo', 'wp-ultimo'),
	__('Yasnogorsk', 'wp-ultimo'),
	__('Yasnogorskiy Rayon', 'wp-ultimo'),
	__('Yefremov', 'wp-ultimo'),
	__('Yepifan’', 'wp-ultimo'),
	__('Zaokskiy', 'wp-ultimo'),
	__('Zaokskiy Rayon', 'wp-ultimo'),
	__('Zhdankovskiy', 'wp-ultimo'),
);
