<?php
/**
 * State City List for TVE - RU.
 *
 * City count: 89
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for TVE - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Andreapol’', 'wp-ultimo'),
	__('Andreapol’skiy Rayon', 'wp-ultimo'),
	__('Belyy', 'wp-ultimo'),
	__('Belyy Gorodok', 'wp-ultimo'),
	__('Bel’skiy Rayon', 'wp-ultimo'),
	__('Berezayka', 'wp-ultimo'),
	__('Bernovo', 'wp-ultimo'),
	__('Bezhetsk', 'wp-ultimo'),
	__('Bezhetskiy Rayon', 'wp-ultimo'),
	__('Bologovskiy Rayon', 'wp-ultimo'),
	__('Bologoye', 'wp-ultimo'),
	__('Bologoye-4', 'wp-ultimo'),
	__('Emmaus', 'wp-ultimo'),
	__('Firovo', 'wp-ultimo'),
	__('Firovskiy Rayon', 'wp-ultimo'),
	__('Gorodnya', 'wp-ultimo'),
	__('Il’inskoye', 'wp-ultimo'),
	__('Izoplit', 'wp-ultimo'),
	__('Kalashnikovo', 'wp-ultimo'),
	__('Kalininskiy Rayon', 'wp-ultimo'),
	__('Kalyazin', 'wp-ultimo'),
	__('Kalyazinskiy Rayon', 'wp-ultimo'),
	__('Kashin', 'wp-ultimo'),
	__('Kashinskiy Rayon', 'wp-ultimo'),
	__('Kesova Gora', 'wp-ultimo'),
	__('Kesovogorskiy Rayon', 'wp-ultimo'),
	__('Kimrskiy Rayon', 'wp-ultimo'),
	__('Kimry', 'wp-ultimo'),
	__('Konakovo', 'wp-ultimo'),
	__('Konakovskiy Rayon', 'wp-ultimo'),
	__('Kozlovo', 'wp-ultimo'),
	__('Krasnokholmskiy Rayon', 'wp-ultimo'),
	__('Krasnomayskiy', 'wp-ultimo'),
	__('Krasnyy Kholm', 'wp-ultimo'),
	__('Kuvshinovo', 'wp-ultimo'),
	__('Kuvshinovskiy Rayon', 'wp-ultimo'),
	__('Kuzhenkino', 'wp-ultimo'),
	__('Lesnoy Rayon', 'wp-ultimo'),
	__('Lesnoye', 'wp-ultimo'),
	__('Likhoslavl’', 'wp-ultimo'),
	__('Likhoslavl’skiy Rayon', 'wp-ultimo'),
	__('Maksatikha', 'wp-ultimo'),
	__('Maksatikhinskiy Rayon', 'wp-ultimo'),
	__('Molokovo', 'wp-ultimo'),
	__('Nelidovo', 'wp-ultimo'),
	__('Novozavidovskiy', 'wp-ultimo'),
	__('Olenino', 'wp-ultimo'),
	__('Orsha', 'wp-ultimo'),
	__('Ostashkov', 'wp-ultimo'),
	__('Ostashkovskiy Rayon', 'wp-ultimo'),
	__('Peno', 'wp-ultimo'),
	__('Penovskiy Rayon', 'wp-ultimo'),
	__('Radchenko', 'wp-ultimo'),
	__('Rameshki', 'wp-ultimo'),
	__('Rameshkovskiy Rayon', 'wp-ultimo'),
	__('Redkino', 'wp-ultimo'),
	__('Rzhev', 'wp-ultimo'),
	__('Sakharovo', 'wp-ultimo'),
	__('Sandovo', 'wp-ultimo'),
	__('Sandovskiy Rayon', 'wp-ultimo'),
	__('Selishche', 'wp-ultimo'),
	__('Selizharovo', 'wp-ultimo'),
	__('Selizharovskiy Rayon', 'wp-ultimo'),
	__('Sonkovo', 'wp-ultimo'),
	__('Spirovo', 'wp-ultimo'),
	__('Spirovskiy Rayon', 'wp-ultimo'),
	__('Stantsia Staritsa', 'wp-ultimo'),
	__('Staraya Toropa', 'wp-ultimo'),
	__('Staritsa', 'wp-ultimo'),
	__('Staritskiy Rayon', 'wp-ultimo'),
	__('Toropets', 'wp-ultimo'),
	__('Toropetskiy Rayon', 'wp-ultimo'),
	__('Torzhok', 'wp-ultimo'),
	__('Torzhokskiy Rayon', 'wp-ultimo'),
	__('Tver', 'wp-ultimo'),
	__('Udomlya', 'wp-ultimo'),
	__('Vasil’yevskiy Mokh', 'wp-ultimo'),
	__('Velikooktyabr’skiy', 'wp-ultimo'),
	__('Ves’yegonsk', 'wp-ultimo'),
	__('Ves’yegonskiy Rayon', 'wp-ultimo'),
	__('Vydropuzhsk', 'wp-ultimo'),
	__('Vypolzovo', 'wp-ultimo'),
	__('Vyshnevolotskiy Rayon', 'wp-ultimo'),
	__('Vyshniy Volochëk', 'wp-ultimo'),
	__('Zapadnaya Dvina', 'wp-ultimo'),
	__('Zavidovo', 'wp-ultimo'),
	__('Zharkovskiy', 'wp-ultimo'),
	__('Zubtsov', 'wp-ultimo'),
	__('Zubtsovskiy Rayon', 'wp-ultimo'),
);
