<?php
/**
 * State City List for TY - RU.
 *
 * City count: 21
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for TY - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Ak-Dovurak', 'wp-ultimo'),
	__('Balgazyn', 'wp-ultimo'),
	__('Bay-Khaak', 'wp-ultimo'),
	__('Chadan', 'wp-ultimo'),
	__('Erzin', 'wp-ultimo'),
	__('Kaa-Khem', 'wp-ultimo'),
	__('Khandagayty', 'wp-ultimo'),
	__('Khovu-Aksy', 'wp-ultimo'),
	__('Kungurtug', 'wp-ultimo'),
	__('Kyzyl', 'wp-ultimo'),
	__('Kyzyl-Khaya', 'wp-ultimo'),
	__('Kyzyl-Mazhalyk', 'wp-ultimo'),
	__('Mugur-Aksy', 'wp-ultimo'),
	__('Samagaltay', 'wp-ultimo'),
	__('Saryg-Sep', 'wp-ultimo'),
	__('Shagonar', 'wp-ultimo'),
	__('Sukpak', 'wp-ultimo'),
	__('Sut-Khol’', 'wp-ultimo'),
	__('Teeli', 'wp-ultimo'),
	__('Toora-Khem', 'wp-ultimo'),
	__('Turan', 'wp-ultimo'),
);
