<?php
/**
 * State City List for TYU - RU.
 *
 * City count: 46
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for TYU - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Abalak', 'wp-ultimo'),
	__('Abatskoye', 'wp-ultimo'),
	__('Antipino', 'wp-ultimo'),
	__('Armizonskiy Rayon', 'wp-ultimo'),
	__('Armizonskoye', 'wp-ultimo'),
	__('Aromashevo', 'wp-ultimo'),
	__('Berdyuzhskiy Rayon', 'wp-ultimo'),
	__('Bogandinskiy', 'wp-ultimo'),
	__('Borovskiy', 'wp-ultimo'),
	__('Chervishevo', 'wp-ultimo'),
	__('Golyshmanovo', 'wp-ultimo'),
	__('Golyshmanovskiy Rayon', 'wp-ultimo'),
	__('Irtyshskiy', 'wp-ultimo'),
	__('Isetskiy Rayon', 'wp-ultimo'),
	__('Isetskoye', 'wp-ultimo'),
	__('Ishim', 'wp-ultimo'),
	__('Ishimskiy Rayon', 'wp-ultimo'),
	__('Kazanskiy Rayon', 'wp-ultimo'),
	__('Kazanskoye', 'wp-ultimo'),
	__('Melioratorov', 'wp-ultimo'),
	__('Mendeleyevo', 'wp-ultimo'),
	__('Moskovskiy', 'wp-ultimo'),
	__('Nizhnyaya Tavda', 'wp-ultimo'),
	__('Novaya Zaimka', 'wp-ultimo'),
	__('Novoseleznëvo', 'wp-ultimo'),
	__('Omutinskiy', 'wp-ultimo'),
	__('Omutinskiy Rayon', 'wp-ultimo'),
	__('Onokhino', 'wp-ultimo'),
	__('Sladkovo', 'wp-ultimo'),
	__('Sladkovskiy Rayon', 'wp-ultimo'),
	__('Sumkino', 'wp-ultimo'),
	__('Tobol’sk', 'wp-ultimo'),
	__('Turtas', 'wp-ultimo'),
	__('Tyumen', 'wp-ultimo'),
	__('Uporovo', 'wp-ultimo'),
	__('Uporovskiy Rayon', 'wp-ultimo'),
	__('Uspenka', 'wp-ultimo'),
	__('Uvat', 'wp-ultimo'),
	__('Vagay', 'wp-ultimo'),
	__('Vagayskiy Rayon', 'wp-ultimo'),
	__('Vikulovo', 'wp-ultimo'),
	__('Vinzili', 'wp-ultimo'),
	__('Yalutorovsk', 'wp-ultimo'),
	__('Yarkovo', 'wp-ultimo'),
	__('Yurginskoye', 'wp-ultimo'),
	__('Zavodoukovsk', 'wp-ultimo'),
);
