<?php
/**
 * State City List for UD - RU.
 *
 * City count: 36
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for UD - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Alnashi', 'wp-ultimo'),
	__('Balezino', 'wp-ultimo'),
	__('Debesy', 'wp-ultimo'),
	__('Fakel', 'wp-ultimo'),
	__('Glazov', 'wp-ultimo'),
	__('Grakhovo', 'wp-ultimo'),
	__('Igra', 'wp-ultimo'),
	__('Izhevsk', 'wp-ultimo'),
	__('Kama', 'wp-ultimo'),
	__('Kambarka', 'wp-ultimo'),
	__('Karakulino', 'wp-ultimo'),
	__('Karakulinskiy Rayon', 'wp-ultimo'),
	__('Kez', 'wp-ultimo'),
	__('Khokhryaki', 'wp-ultimo'),
	__('Kiyasovo', 'wp-ultimo'),
	__('Kiyasovskiy Rayon', 'wp-ultimo'),
	__('Kizner', 'wp-ultimo'),
	__('Krasnogorskoye', 'wp-ultimo'),
	__('Malaya Purga', 'wp-ultimo'),
	__('Malopurginskiy Rayon', 'wp-ultimo'),
	__('Mozhga', 'wp-ultimo'),
	__('Pirogovo', 'wp-ultimo'),
	__('Pudem', 'wp-ultimo'),
	__('Pychas', 'wp-ultimo'),
	__('Sarapul', 'wp-ultimo'),
	__('Sarapul’skiy Rayon', 'wp-ultimo'),
	__('Selty', 'wp-ultimo'),
	__('Sharkan', 'wp-ultimo'),
	__('Sigayevo', 'wp-ultimo'),
	__('Syumsi', 'wp-ultimo'),
	__('Uva', 'wp-ultimo'),
	__('Vavozh', 'wp-ultimo'),
	__('Votkinsk', 'wp-ultimo'),
	__('Yar', 'wp-ultimo'),
	__('Yukamenskoye', 'wp-ultimo'),
	__('Zav’yalovskiy Rayon', 'wp-ultimo'),
);
