<?php
/**
 * State City List for ULY - RU.
 *
 * City count: 45
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for ULY - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Barysh', 'wp-ultimo'),
	__('Bazarnyy Syzgan', 'wp-ultimo'),
	__('Cherdaklinskiy Rayon', 'wp-ultimo'),
	__('Cherdakly', 'wp-ultimo'),
	__('Chufarovo', 'wp-ultimo'),
	__('Dimitrovgrad', 'wp-ultimo'),
	__('Glotovka', 'wp-ultimo'),
	__('Ignatovka', 'wp-ultimo'),
	__('Imeni Vladimira Il’icha Lenina', 'wp-ultimo'),
	__('Inza', 'wp-ultimo'),
	__('Isheyevka', 'wp-ultimo'),
	__('Izmaylovo', 'wp-ultimo'),
	__('Kanadey', 'wp-ultimo'),
	__('Karsun', 'wp-ultimo'),
	__('Krasnyy Gulyay', 'wp-ultimo'),
	__('Kuzovatovo', 'wp-ultimo'),
	__('Mayna', 'wp-ultimo'),
	__('Maynskiy Rayon', 'wp-ultimo'),
	__('Mirnyy', 'wp-ultimo'),
	__('Mullovka', 'wp-ultimo'),
	__('Nikolayevka', 'wp-ultimo'),
	__('Novaya Malykla', 'wp-ultimo'),
	__('Novaya Mayna', 'wp-ultimo'),
	__('Novocheremshansk', 'wp-ultimo'),
	__('Novospasskoye', 'wp-ultimo'),
	__('Novoul’yanovsk', 'wp-ultimo'),
	__('Pavlovka', 'wp-ultimo'),
	__('Pavlovskiy Rayon', 'wp-ultimo'),
	__('Radishchevo', 'wp-ultimo'),
	__('Sengiley', 'wp-ultimo'),
	__('Silikatnyy', 'wp-ultimo'),
	__('Staraya Kulatka', 'wp-ultimo'),
	__('Staraya Mayna', 'wp-ultimo'),
	__('Starokulatkinskiy Rayon', 'wp-ultimo'),
	__('Starotimoshkino', 'wp-ultimo'),
	__('Surskoye', 'wp-ultimo'),
	__('Teren’gul’skiy Rayon', 'wp-ultimo'),
	__('Tsil’na', 'wp-ultimo'),
	__('Tsil’ninskiy Rayon', 'wp-ultimo'),
	__('Ulyanovsk', 'wp-ultimo'),
	__('Ulyanovskiy Rayon', 'wp-ultimo'),
	__('Undory', 'wp-ultimo'),
	__('Veshkayma', 'wp-ultimo'),
	__('Yazykovo', 'wp-ultimo'),
	__('Zhadovka', 'wp-ultimo'),
);
