<?php
/**
 * State City List for VLA - RU.
 *
 * City count: 66
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for VLA - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Aleksandrov', 'wp-ultimo'),
	__('Aleksandrovskiy Rayon', 'wp-ultimo'),
	__('Andreyevo', 'wp-ultimo'),
	__('Anopino', 'wp-ultimo'),
	__('Arsaki', 'wp-ultimo'),
	__('Balakirevo', 'wp-ultimo'),
	__('Bavleny', 'wp-ultimo'),
	__('Belaya Rechka', 'wp-ultimo'),
	__('Bogolyubovo', 'wp-ultimo'),
	__('Dobryatino', 'wp-ultimo'),
	__('Galitsy', 'wp-ultimo'),
	__('Golovino', 'wp-ultimo'),
	__('Gorokhovets', 'wp-ultimo'),
	__('Gusevskiy', 'wp-ultimo'),
	__('Gus’-Khrustal’nyy', 'wp-ultimo'),
	__('Imeni Vorovskogo', 'wp-ultimo'),
	__('Ivanishchi', 'wp-ultimo'),
	__('Kameshkovo', 'wp-ultimo'),
	__('Karabanovo', 'wp-ultimo'),
	__('Kideksha', 'wp-ultimo'),
	__('Kirzhach', 'wp-ultimo'),
	__('Kol’chugino', 'wp-ultimo'),
	__('Kol’chuginskiy Rayon', 'wp-ultimo'),
	__('Kommunar', 'wp-ultimo'),
	__('Kosterevo', 'wp-ultimo'),
	__('Kovrov', 'wp-ultimo'),
	__('Krasnaya Gorbatka', 'wp-ultimo'),
	__('Krasnyy Bogatyr’', 'wp-ultimo'),
	__('Krasnyy Oktyabr’', 'wp-ultimo'),
	__('Kurlovo', 'wp-ultimo'),
	__('Lakinsk', 'wp-ultimo'),
	__('Luknovo', 'wp-ultimo'),
	__('Melekhovo', 'wp-ultimo'),
	__('Melenki', 'wp-ultimo'),
	__('Melenkovskiy Rayon', 'wp-ultimo'),
	__('Mezinovskiy', 'wp-ultimo'),
	__('Mstera', 'wp-ultimo'),
	__('Murom', 'wp-ultimo'),
	__('Muromskiy Rayon', 'wp-ultimo'),
	__('Muromtsevo', 'wp-ultimo'),
	__('Nikologory', 'wp-ultimo'),
	__('Novki', 'wp-ultimo'),
	__('Novovyazniki', 'wp-ultimo'),
	__('Oktyabr’skiy', 'wp-ultimo'),
	__('Orgtrud', 'wp-ultimo'),
	__('Petushinskiy Rayon', 'wp-ultimo'),
	__('Petushki', 'wp-ultimo'),
	__('Pokrov', 'wp-ultimo'),
	__('Raduzhnyy', 'wp-ultimo'),
	__('Sobinka', 'wp-ultimo'),
	__('Sobinskiy Rayon', 'wp-ultimo'),
	__('Stavrovo', 'wp-ultimo'),
	__('Stepantsevo', 'wp-ultimo'),
	__('Strunino', 'wp-ultimo'),
	__('Sudogda', 'wp-ultimo'),
	__('Sudogodskiy Rayon', 'wp-ultimo'),
	__('Suzdal’', 'wp-ultimo'),
	__('Suzdal’skiy Rayon', 'wp-ultimo'),
	__('Urshel’skiy', 'wp-ultimo'),
	__('Velikodvorskiy', 'wp-ultimo'),
	__('Vladimir', 'wp-ultimo'),
	__('Vorsha', 'wp-ultimo'),
	__('Vyazniki', 'wp-ultimo'),
	__('Yur’yev-Pol’skiy', 'wp-ultimo'),
	__('Yur’yev-Pol’skiy Rayon', 'wp-ultimo'),
	__('Zolotkovo', 'wp-ultimo'),
);
