<?php
/**
 * State City List for VLG - RU.
 *
 * City count: 63
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for VLG - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Babayevo', 'wp-ultimo'),
	__('Babayevskiy Rayon', 'wp-ultimo'),
	__('Belozërsk', 'wp-ultimo'),
	__('Belozërskiy Rayon', 'wp-ultimo'),
	__('Chagoda', 'wp-ultimo'),
	__('Chagodoshchenskiy Rayon', 'wp-ultimo'),
	__('Chebsara', 'wp-ultimo'),
	__('Cherepovets', 'wp-ultimo'),
	__('Cherepovetskiy Rayon', 'wp-ultimo'),
	__('Ferapontovo', 'wp-ultimo'),
	__('Goritsy', 'wp-ultimo'),
	__('Gryazovets', 'wp-ultimo'),
	__('Gryazovetskiy Rayon', 'wp-ultimo'),
	__('Imeni Babushkina', 'wp-ultimo'),
	__('Imeni Zhelyabova', 'wp-ultimo'),
	__('Kadnikov', 'wp-ultimo'),
	__('Kaduy', 'wp-ultimo'),
	__('Kaduyskiy Rayon', 'wp-ultimo'),
	__('Kharovsk', 'wp-ultimo'),
	__('Kharovskiy Rayon', 'wp-ultimo'),
	__('Khokhlovo', 'wp-ultimo'),
	__('Kichmengskiy Gorodok', 'wp-ultimo'),
	__('Kichmengsko-Gorodetskiy Rayon', 'wp-ultimo'),
	__('Kirillov', 'wp-ultimo'),
	__('Kirillovskiy Rayon', 'wp-ultimo'),
	__('Krasavino', 'wp-ultimo'),
	__('Kuzino', 'wp-ultimo'),
	__('Lipin Bor', 'wp-ultimo'),
	__('Mezhdurechenskiy Rayon', 'wp-ultimo'),
	__('Molochnoye', 'wp-ultimo'),
	__('Myaksa', 'wp-ultimo'),
	__('Nelazskoye', 'wp-ultimo'),
	__('Nikol’sk', 'wp-ultimo'),
	__('Nyuksenitsa', 'wp-ultimo'),
	__('Sazonovo', 'wp-ultimo'),
	__('Sheksna', 'wp-ultimo'),
	__('Sheksninskiy Rayon', 'wp-ultimo'),
	__('Shuyskoye', 'wp-ultimo'),
	__('Sokol', 'wp-ultimo'),
	__('Sokol’skiy Rayon', 'wp-ultimo'),
	__('Suda', 'wp-ultimo'),
	__('Syamzha', 'wp-ultimo'),
	__('Syamzhenskiy Rayon', 'wp-ultimo'),
	__('Tarnogskiy Gorodok', 'wp-ultimo'),
	__('Tarnogskiy Rayon', 'wp-ultimo'),
	__('Tonshalovo', 'wp-ultimo'),
	__('Totemskiy Rayon', 'wp-ultimo'),
	__('Tot’ma', 'wp-ultimo'),
	__('Ustyuzhenskiy Rayon', 'wp-ultimo'),
	__('Ustyuzhna', 'wp-ultimo'),
	__('Ust’-Kubinskiy Rayon', 'wp-ultimo'),
	__('Ust’ye', 'wp-ultimo'),
	__('Velikiy Ustyug', 'wp-ultimo'),
	__('Velikoustyugskiy Rayon', 'wp-ultimo'),
	__('Verkhovazhskiy Rayon', 'wp-ultimo'),
	__('Verkhovazh’ye', 'wp-ultimo'),
	__('Vokhtoga', 'wp-ultimo'),
	__('Vologda', 'wp-ultimo'),
	__('Vologodskiy Rayon', 'wp-ultimo'),
	__('Vozhega', 'wp-ultimo'),
	__('Vytegorskiy Rayon', 'wp-ultimo'),
	__('Vytegra', 'wp-ultimo'),
	__('Zubovo', 'wp-ultimo'),
);
