<?php
/**
 * State City List for VOR - RU.
 *
 * City count: 92
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for VOR - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Abramovka', 'wp-ultimo'),
	__('Anna', 'wp-ultimo'),
	__('Anninskiy Rayon', 'wp-ultimo'),
	__('Belogor’ye', 'wp-ultimo'),
	__('Bobrov', 'wp-ultimo'),
	__('Bobrovskiy Rayon', 'wp-ultimo'),
	__('Boguchar', 'wp-ultimo'),
	__('Borisoglebsk', 'wp-ultimo'),
	__('Buturlinovka', 'wp-ultimo'),
	__('Buturlinovskiy Rayon', 'wp-ultimo'),
	__('Davydovka', 'wp-ultimo'),
	__('Devitsa', 'wp-ultimo'),
	__('Drakino', 'wp-ultimo'),
	__('Ertil’', 'wp-ultimo'),
	__('Ertil’skiy Rayon', 'wp-ultimo'),
	__('Gribanovskiy', 'wp-ultimo'),
	__('Gribanovskiy Rayon', 'wp-ultimo'),
	__('Imeni Pervogo Maya', 'wp-ultimo'),
	__('Kalach', 'wp-ultimo'),
	__('Kamenka', 'wp-ultimo'),
	__('Kamenskiy Rayon', 'wp-ultimo'),
	__('Kantemirovka', 'wp-ultimo'),
	__('Kashirskiy Rayon', 'wp-ultimo'),
	__('Kashirskoye', 'wp-ultimo'),
	__('Khrenovoye', 'wp-ultimo'),
	__('Kolodeznyy', 'wp-ultimo'),
	__('Korotoyak', 'wp-ultimo'),
	__('Kozlovka', 'wp-ultimo'),
	__('Krasnolesnyy', 'wp-ultimo'),
	__('Latnaya', 'wp-ultimo'),
	__('Liski', 'wp-ultimo'),
	__('Liskinskiy Rayon', 'wp-ultimo'),
	__('Losevo', 'wp-ultimo'),
	__('Maslovka', 'wp-ultimo'),
	__('Mitrofanovka', 'wp-ultimo'),
	__('Nizhnedevitsk', 'wp-ultimo'),
	__('Nizhnedevitskiy Rayon', 'wp-ultimo'),
	__('Nizhniy Kislyay', 'wp-ultimo'),
	__('Nizhniy Mamon', 'wp-ultimo'),
	__('Novaya Chigla', 'wp-ultimo'),
	__('Novaya Usman’', 'wp-ultimo'),
	__('Novokhoperskiy Rayon', 'wp-ultimo'),
	__('Novokhopërsk', 'wp-ultimo'),
	__('Novousmanskiy Rayon', 'wp-ultimo'),
	__('Novovoronezh', 'wp-ultimo'),
	__('Novozhivotinnoye', 'wp-ultimo'),
	__('Ol’khovatka', 'wp-ultimo'),
	__('Ol’khovatskiy Rayon', 'wp-ultimo'),
	__('Orlovo', 'wp-ultimo'),
	__('Ostrogozhsk', 'wp-ultimo'),
	__('Panino', 'wp-ultimo'),
	__('Paninskiy Rayon', 'wp-ultimo'),
	__('Pavlovsk', 'wp-ultimo'),
	__('Pavlovskiy Rayon', 'wp-ultimo'),
	__('Pereleshino', 'wp-ultimo'),
	__('Pereleshinskiy', 'wp-ultimo'),
	__('Podgorenskiy', 'wp-ultimo'),
	__('Podgorenskiy Rayon', 'wp-ultimo'),
	__('Podgornoye', 'wp-ultimo'),
	__('Podkletnoye', 'wp-ultimo'),
	__('Povorino', 'wp-ultimo'),
	__('Povorinskiy Rayon', 'wp-ultimo'),
	__('Pridonskoy', 'wp-ultimo'),
	__('Ramonskiy Rayon', 'wp-ultimo'),
	__('Ramon’', 'wp-ultimo'),
	__('Rep’yevskiy Rayon', 'wp-ultimo'),
	__('Rossoshanskiy Rayon', 'wp-ultimo'),
	__('Rossosh’', 'wp-ultimo'),
	__('Sadovoye', 'wp-ultimo'),
	__('Semiluki', 'wp-ultimo'),
	__('Semilukskiy Rayon', 'wp-ultimo'),
	__('Shilovo', 'wp-ultimo'),
	__('Sloboda', 'wp-ultimo'),
	__('Somovo', 'wp-ultimo'),
	__('Sredniy Ikorets', 'wp-ultimo'),
	__('Strelitsa', 'wp-ultimo'),
	__('Talovaya', 'wp-ultimo'),
	__('Ternovka', 'wp-ultimo'),
	__('Ternovskiy Rayon', 'wp-ultimo'),
	__('Uglyanets', 'wp-ultimo'),
	__('Uryv-Pokrovka', 'wp-ultimo'),
	__('Verkhniy Mamon', 'wp-ultimo'),
	__('Verkhnyaya Khava', 'wp-ultimo'),
	__('Verkhnyaya Tishanka', 'wp-ultimo'),
	__('Volya', 'wp-ultimo'),
	__('Vorob’yevskiy Rayon', 'wp-ultimo'),
	__('Voronezh', 'wp-ultimo'),
	__('Vorontsovka', 'wp-ultimo'),
	__('Yelan’-Koleno', 'wp-ultimo'),
	__('Yelan’-Kolenovskiy', 'wp-ultimo'),
	__('Zabolotovka', 'wp-ultimo'),
	__('Zemlyansk', 'wp-ultimo'),
);
