<?php
/**
 * State City List for YAN - RU.
 *
 * City count: 24
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for YAN - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Aksarka', 'wp-ultimo'),
	__('Gubkinskiy', 'wp-ultimo'),
	__('Kharp', 'wp-ultimo'),
	__('Korotchaevo', 'wp-ultimo'),
	__('Labytnangi', 'wp-ultimo'),
	__('Muravlenko', 'wp-ultimo'),
	__('Muzhi', 'wp-ultimo'),
	__('Mys-Kamennyy', 'wp-ultimo'),
	__('Nadym', 'wp-ultimo'),
	__('Nadymskiy Rayon', 'wp-ultimo'),
	__('Novyy Urengoy', 'wp-ultimo'),
	__('Noyabrsk', 'wp-ultimo'),
	__('Nyda', 'wp-ultimo'),
	__('Pangody', 'wp-ultimo'),
	__('Priural’skiy Rayon', 'wp-ultimo'),
	__('Purovskiy Rayon', 'wp-ultimo'),
	__('Purpe', 'wp-ultimo'),
	__('Salekhard', 'wp-ultimo'),
	__('Shuryshkarskiy Rayon', 'wp-ultimo'),
	__('Staryy Nadym', 'wp-ultimo'),
	__('Tarko-Sale', 'wp-ultimo'),
	__('Tazovskiy', 'wp-ultimo'),
	__('Urengoy', 'wp-ultimo'),
	__('Yar-Sale', 'wp-ultimo'),
);
