<?php
/**
 * State City List for YAR - RU.
 *
 * City count: 52
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for YAR - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Berendeyevo', 'wp-ultimo'),
	__('Bol’shesel’skiy Rayon', 'wp-ultimo'),
	__('Bol’shoye Selo', 'wp-ultimo'),
	__('Borisoglebskiy', 'wp-ultimo'),
	__('Borisoglebskiy Rayon', 'wp-ultimo'),
	__('Borok', 'wp-ultimo'),
	__('Breytovo', 'wp-ultimo'),
	__('Breytovskiy Rayon', 'wp-ultimo'),
	__('Burmakino', 'wp-ultimo'),
	__('Danilov', 'wp-ultimo'),
	__('Danilovskiy Rayon', 'wp-ultimo'),
	__('Dubki', 'wp-ultimo'),
	__('Gavrilov-Yam', 'wp-ultimo'),
	__('Gavrilov-Yamskiy Rayon', 'wp-ultimo'),
	__('Ishnya', 'wp-ultimo'),
	__('Konstantinovskiy', 'wp-ultimo'),
	__('Krasnyy Profintern', 'wp-ultimo'),
	__('Krasnyye Tkachi', 'wp-ultimo'),
	__('Kukoboy', 'wp-ultimo'),
	__('Kurba', 'wp-ultimo'),
	__('Levashevo', 'wp-ultimo'),
	__('Lyubim', 'wp-ultimo'),
	__('Lyubimskiy Rayon', 'wp-ultimo'),
	__('Myshkin', 'wp-ultimo'),
	__('Myshkinskiy Rayon', 'wp-ultimo'),
	__('Nekouzskiy Rayon', 'wp-ultimo'),
	__('Nekrasovskiy Rayon', 'wp-ultimo'),
	__('Nekrasovskoye', 'wp-ultimo'),
	__('Novyy Nekouz', 'wp-ultimo'),
	__('Pereslavl’-Zalesskiy', 'wp-ultimo'),
	__('Pereslavskiy Rayon', 'wp-ultimo'),
	__('Pervomayskiy Rayon', 'wp-ultimo'),
	__('Pesochnoye', 'wp-ultimo'),
	__('Petrovsk', 'wp-ultimo'),
	__('Porech’ye-Rybnoye', 'wp-ultimo'),
	__('Poshekhonskiy Rayon', 'wp-ultimo'),
	__('Poshekhon’ye', 'wp-ultimo'),
	__('Prechistoye', 'wp-ultimo'),
	__('Rostov', 'wp-ultimo'),
	__('Rostovskiy Rayon', 'wp-ultimo'),
	__('Rybinsk', 'wp-ultimo'),
	__('Rybinskiy Rayon', 'wp-ultimo'),
	__('Semibratovo', 'wp-ultimo'),
	__('Sudoverf’', 'wp-ultimo'),
	__('Tunoshna', 'wp-ultimo'),
	__('Tutayev', 'wp-ultimo'),
	__('Tutayevskiy Rayon', 'wp-ultimo'),
	__('Uglich', 'wp-ultimo'),
	__('Uglichskiy Rayon', 'wp-ultimo'),
	__('Volga', 'wp-ultimo'),
	__('Yaroslavl', 'wp-ultimo'),
	__('Yaroslavskiy Rayon', 'wp-ultimo'),
);
