<?php
/**
 * State City List for YEV - RU.
 *
 * City count: 18
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for YEV - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Amurzet', 'wp-ultimo'),
	__('Babstovo', 'wp-ultimo'),
	__('Bira', 'wp-ultimo'),
	__('Birakan', 'wp-ultimo'),
	__('Birobidzhan', 'wp-ultimo'),
	__('Birobidzhanskiy Rayon', 'wp-ultimo'),
	__('Izvestkovyy', 'wp-ultimo'),
	__('Khingansk', 'wp-ultimo'),
	__('Kul’dur', 'wp-ultimo'),
	__('Leninskiy Rayon', 'wp-ultimo'),
	__('Leninskoye', 'wp-ultimo'),
	__('Londoko', 'wp-ultimo'),
	__('Obluchenskiy Rayon', 'wp-ultimo'),
	__('Oktyabr’skiy Rayon', 'wp-ultimo'),
	__('Priamurskiy', 'wp-ultimo'),
	__('Smidovich', 'wp-ultimo'),
	__('Smidovichskiy Rayon', 'wp-ultimo'),
	__('Volochayevka Vtoraya', 'wp-ultimo'),
);
