<?php
/**
 * State City List for ZAB - RU.
 *
 * City count: 75
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for ZAB - RU.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Aginskoye', 'wp-ultimo'),
	__('Aksha', 'wp-ultimo'),
	__('Akshinskiy Rayon', 'wp-ultimo'),
	__('Aleksandrovo-Zavodskiy Rayon', 'wp-ultimo'),
	__('Aleksandrovskiy Zavod', 'wp-ultimo'),
	__('Amazar', 'wp-ultimo'),
	__('Atamanovka', 'wp-ultimo'),
	__('Bada', 'wp-ultimo'),
	__('Baley', 'wp-ultimo'),
	__('Baleyskiy Rayon', 'wp-ultimo'),
	__('Balyaga', 'wp-ultimo'),
	__('Bol’shaya Tura', 'wp-ultimo'),
	__('Borzinskiy Rayon', 'wp-ultimo'),
	__('Borzya', 'wp-ultimo'),
	__('Bukachacha', 'wp-ultimo'),
	__('Chara', 'wp-ultimo'),
	__('Chernyshevsk', 'wp-ultimo'),
	__('Chita', 'wp-ultimo'),
	__('Chitinskiy Rayon', 'wp-ultimo'),
	__('Darasun', 'wp-ultimo'),
	__('Dauriya', 'wp-ultimo'),
	__('Domna', 'wp-ultimo'),
	__('Drovyanaya', 'wp-ultimo'),
	__('Dul’durga', 'wp-ultimo'),
	__('Gazimuro-Zavodskiy Rayon', 'wp-ultimo'),
	__('Gazimurskiy Zavod', 'wp-ultimo'),
	__('Kadaya', 'wp-ultimo'),
	__('Kalanguy', 'wp-ultimo'),
	__('Kalga', 'wp-ultimo'),
	__('Karymskoye', 'wp-ultimo'),
	__('Khilok', 'wp-ultimo'),
	__('Kholbon', 'wp-ultimo'),
	__('Klichka', 'wp-ultimo'),
	__('Klyuchevskiy', 'wp-ultimo'),
	__('Kokuy', 'wp-ultimo'),
	__('Krasnokamensk', 'wp-ultimo'),
	__('Krasnyy Chikoy', 'wp-ultimo'),
	__('Kuanda', 'wp-ultimo'),
	__('Kurort-Darasun', 'wp-ultimo'),
	__('Kyra', 'wp-ultimo'),
	__('Makkaveyevo', 'wp-ultimo'),
	__('Mogocha', 'wp-ultimo'),
	__('Mogoytuy', 'wp-ultimo'),
	__('Mogzon', 'wp-ultimo'),
	__('Nerchinsk', 'wp-ultimo'),
	__('Nerchinskiy Zavod', 'wp-ultimo'),
	__('Nerchinsko-Zavodskiy Rayon', 'wp-ultimo'),
	__('Nizhniy Tsasuchey', 'wp-ultimo'),
	__('Novaya Chara', 'wp-ultimo'),
	__('Novokruchininskiy', 'wp-ultimo'),
	__('Novoorlovsk', 'wp-ultimo'),
	__('Novopavlovka', 'wp-ultimo'),
	__('Olovyannaya', 'wp-ultimo'),
	__('Olovyanninskiy Rayon', 'wp-ultimo'),
	__('Orlovskiy', 'wp-ultimo'),
	__('Pervomayskiy', 'wp-ultimo'),
	__('Petrovsk-Zabaykal’skiy', 'wp-ultimo'),
	__('Priargunsk', 'wp-ultimo'),
	__('Priargunskiy Rayon', 'wp-ultimo'),
	__('Priiskovyy', 'wp-ultimo'),
	__('Shelopugino', 'wp-ultimo'),
	__('Shilka', 'wp-ultimo'),
	__('Shilkinskiy Rayon', 'wp-ultimo'),
	__('Smolenka', 'wp-ultimo'),
	__('Sretensk', 'wp-ultimo'),
	__('Sretenskiy Rayon', 'wp-ultimo'),
	__('Tarbagatay', 'wp-ultimo'),
	__('Uletovskiy Rayon', 'wp-ultimo'),
	__('Ulety', 'wp-ultimo'),
	__('Ust’-Karsk', 'wp-ultimo'),
	__('Verkh-Usugli', 'wp-ultimo'),
	__('Vershino-Darasunskiy', 'wp-ultimo'),
	__('Vershino-Shakhtaminskiy', 'wp-ultimo'),
	__('Zabaykal’sk', 'wp-ultimo'),
	__('Zhireken', 'wp-ultimo'),
);
