<?php
/**
 * State City List for 1 - NE.
 *
 * City count: 6
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 1 - NE.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Agadez', 'wp-ultimo'),
	__('Alaghsas', 'wp-ultimo'),
	__('Arlit', 'wp-ultimo'),
	__('Bilma', 'wp-ultimo'),
	__('Département de Bilma', 'wp-ultimo'),
	__('Département de Tchirozérine', 'wp-ultimo'),
);
