<?php
/**
 * State City List for 2 - NE.
 *
 * City count: 6
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 2 - NE.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Diffa', 'wp-ultimo'),
	__('Département de Diffa', 'wp-ultimo'),
	__('Département de Maïné-Soroa', 'wp-ultimo'),
	__('Département de Nguigmi', 'wp-ultimo'),
	__('Maïné Soroa', 'wp-ultimo'),
	__('Nguigmi', 'wp-ultimo'),
);
