<?php
/**
 * State City List for 3 - NE.
 *
 * City count: 8
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 3 - NE.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Boboye Department', 'wp-ultimo'),
	__('Dogondoutchi', 'wp-ultimo'),
	__('Dosso', 'wp-ultimo'),
	__('Département de Dogondoutchi', 'wp-ultimo'),
	__('Département de Dosso', 'wp-ultimo'),
	__('Département de Gaya', 'wp-ultimo'),
	__('Département de Loga', 'wp-ultimo'),
	__('Gaya', 'wp-ultimo'),
);
