<?php
/**
 * State City List for 4 - NE.
 *
 * City count: 12
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 4 - NE.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Aguié', 'wp-ultimo'),
	__('Dakoro', 'wp-ultimo'),
	__('Département de Dakoro', 'wp-ultimo'),
	__('Département de Mayahi', 'wp-ultimo'),
	__('Département de Tessaoua', 'wp-ultimo'),
	__('Département d’Aguié', 'wp-ultimo'),
	__('Guidan Roumdji Department', 'wp-ultimo'),
	__('Madarounfa', 'wp-ultimo'),
	__('Maradi', 'wp-ultimo'),
	__('Mayahi', 'wp-ultimo'),
	__('Tessaoua', 'wp-ultimo'),
	__('Tibiri', 'wp-ultimo'),
);
