<?php
/**
 * State City List for 5 - NE.
 *
 * City count: 15
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 5 - NE.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Abalak', 'wp-ultimo'),
	__('Birni N Konni', 'wp-ultimo'),
	__('Bouza', 'wp-ultimo'),
	__("Département d' Illéla", 'wp-ultimo'),
	__('Département de Birni Nkonni', 'wp-ultimo'),
	__('Département de Bouza', 'wp-ultimo'),
	__('Département de Keïta', 'wp-ultimo'),
	__('Département de Madaoua', 'wp-ultimo'),
	__('Département de Tahoua', 'wp-ultimo'),
	__('Département de Tchin-Tabaraden', 'wp-ultimo'),
	__('Illéla', 'wp-ultimo'),
	__('Keïta', 'wp-ultimo'),
	__('Madaoua', 'wp-ultimo'),
	__('Tahoua', 'wp-ultimo'),
	__('Tchintabaraden', 'wp-ultimo'),
);
