<?php
/**
 * State City List for 6 - NE.
 *
 * City count: 14
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 6 - NE.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Ayorou', 'wp-ultimo'),
	__('Balleyara', 'wp-ultimo'),
	__('Département de Filingué', 'wp-ultimo'),
	__('Département de Ouallam', 'wp-ultimo'),
	__('Département de Say', 'wp-ultimo'),
	__('Filingué', 'wp-ultimo'),
	__('Kollo', 'wp-ultimo'),
	__('Kollo Department', 'wp-ultimo'),
	__('Ouallam', 'wp-ultimo'),
	__('Say', 'wp-ultimo'),
	__('Tera Department', 'wp-ultimo'),
	__('Tillaberi Department', 'wp-ultimo'),
	__('Tillabéri', 'wp-ultimo'),
	__('Téra', 'wp-ultimo'),
);
