<?php
/**
 * State City List for 7 - NE.
 *
 * City count: 9
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 7 - NE.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Département de Gouré', 'wp-ultimo'),
	__('Département de Kantché', 'wp-ultimo'),
	__('Département de Tânout', 'wp-ultimo'),
	__('Gouré', 'wp-ultimo'),
	__('Magaria', 'wp-ultimo'),
	__('Matamey', 'wp-ultimo'),
	__('Mirriah', 'wp-ultimo'),
	__('Tanout', 'wp-ultimo'),
	__('Zinder', 'wp-ultimo'),
);
