<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'setasign\\Fpdi\\' => array($vendorDir . '/setasign/fpdi/src'),
    'phpseclib3\\' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'bcmath_compat\\' => array($vendorDir . '/phpseclib/bcmath_compat/src'),
    'WP_Ultimo\\Dependencies\\phpDocumentor\\Reflection\\' => array($vendorDir . '/phpdocumentor/reflection-common/src', $vendorDir . '/phpdocumentor/reflection-docblock/src', $vendorDir . '/phpdocumentor/type-resolver/src'),
    'WP_Ultimo\\Dependencies\\Webmozart\\Assert\\' => array($vendorDir . '/webmozart/assert/src'),
    'WP_Ultimo\\Dependencies\\Symfony\\Contracts\\Translation\\' => array($vendorDir . '/symfony/translation-contracts'),
    'WP_Ultimo\\Dependencies\\Stripe\\' => array($vendorDir . '/stripe/stripe-php/lib'),
    'WP_Ultimo\\Dependencies\\Spatie\\SslCertificate\\' => array($vendorDir . '/spatie/ssl-certificate/src'),
    'WP_Ultimo\\Dependencies\\Spatie\\Macroable\\' => array($vendorDir . '/spatie/macroable/src'),
    'WP_Ultimo\\Dependencies\\ScssPhp\\ScssPhp\\' => array($vendorDir . '/scssphp/scssphp/src'),
    'WP_Ultimo\\Dependencies\\React\\Promise\\Timer\\' => array($vendorDir . '/react/promise-timer/src'),
    'WP_Ultimo\\Dependencies\\React\\Promise\\' => array($vendorDir . '/react/promise/src'),
    'WP_Ultimo\\Dependencies\\React\\EventLoop\\' => array($vendorDir . '/react/event-loop/src'),
    'WP_Ultimo\\Dependencies\\React\\Dns\\' => array($vendorDir . '/react/dns/src'),
    'WP_Ultimo\\Dependencies\\React\\Cache\\' => array($vendorDir . '/react/cache/src'),
    'WP_Ultimo\\Dependencies\\Rakit\\Validation\\' => array($vendorDir . '/rakit/validation/src'),
    'WP_Ultimo\\Dependencies\\ParagonIE\\ConstantTime\\' => array($vendorDir . '/paragonie/constant_time_encoding/src'),
    'WP_Ultimo\\Dependencies\\Pablo_Pacheco\\WP_Namespace_Autoloader\\' => array($vendorDir . '/pablo-sg-pacheco/wp-namespace-autoloader/src'),
    'WP_Ultimo\\Dependencies\\Ifsnop\\' => array($vendorDir . '/ifsnop/mysqldump-php/src/Ifsnop'),
    'WP_Ultimo\\Dependencies\\Hashids\\' => array($vendorDir . '/hashids/hashids/src'),
    'WP_Ultimo\\Dependencies\\Gemz\\Dns\\' => array($vendorDir . '/gemz/dns/src'),
    'WP_Ultimo\\Dependencies\\DeepCopy\\' => array($vendorDir . '/myclabs/deep-copy/src/DeepCopy'),
    'WP_Ultimo\\Dependencies\\Carbon\\' => array($vendorDir . '/nesbot/carbon/src/Carbon'),
    'WP_Ultimo\\Dependencies\\BerlinDB\\Database\\' => array($vendorDir . '/berlindb/core'),
    'WP_Ultimo\\Dependencies\\Aura\\Session\\' => array($vendorDir . '/aura/session/src'),
    'WP_Ultimo\\Dependencies\\Arrch\\' => array($vendorDir . '/rpnzl/arrch/src/Arrch'),
    'Symfony\\Polyfill\\Php80\\' => array($vendorDir . '/symfony/polyfill-php80'),
    'Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'Symfony\\Polyfill\\Ctype\\' => array($vendorDir . '/symfony/polyfill-ctype'),
    'Symfony\\Component\\Translation\\' => array($vendorDir . '/symfony/translation'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'Mpdf\\' => array($vendorDir . '/mpdf/mpdf/src'),
    'Faker\\' => array($vendorDir . '/fzaninotto/faker/src/Faker'),
);
