<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'ad155f8f1cf0d418fe49e248db8c661b' => $vendorDir . '/react/promise/src/functions_include.php',
    '0e6d7bf4a5811bfa5cf40c5ccd6fae6a' => $vendorDir . '/symfony/polyfill-mbstring/bootstrap.php',
    'a4a119a56e50fbb293281d9a48007e0e' => $vendorDir . '/symfony/polyfill-php80/bootstrap.php',
    '972fda704d680a3a53c68e34e193cb22' => $vendorDir . '/react/promise-timer/src/functions_include.php',
    '320cde22f66dd4f5d3fd621d3e88b98f' => $vendorDir . '/symfony/polyfill-ctype/bootstrap.php',
    'a1105708a18b76903365ca1c4aa61b02' => $vendorDir . '/symfony/translation/Resources/functions.php',
    '6124b4c8570aa390c21fafd04a26c69f' => $vendorDir . '/myclabs/deep-copy/src/DeepCopy/deep_copy.php',
    'decc78cc4436b1292c6c0d151b19445c' => $vendorDir . '/phpseclib/phpseclib/phpseclib/bootstrap.php',
    '56823cacd97af379eceaf82ad00b928f' => $vendorDir . '/phpseclib/bcmath_compat/lib/bcmath.php',
    '6576cecdc0cf89139d7b600c9ffaa124' => $vendorDir . '/spatie/ssl-certificate/src/helpers.php',
    '7eeebdc1a70966b81324720640660da2' => $baseDir . '/inc/api/trait-rest-api.php',
    'b0e0eba807464c8ba8c156b62d86d80d' => $baseDir . '/inc/api/trait-wp-cli.php',
    '3e6dcfbeb46eb6de68167e3ad82548f5' => $baseDir . '/inc/traits/trait-singleton.php',
    'db493680630213f0e3acb82ae069e9d5' => $baseDir . '/inc/traits/trait-wp-ultimo-deprecated.php',
    '4645f21f0152744165081c4999369ef1' => $baseDir . '/inc/traits/trait-wp-ultimo-plan-deprecated.php',
    '0664eb34e92f667593f9c47f3a23dc67' => $baseDir . '/inc/traits/trait-wp-ultimo-coupon-deprecated.php',
    '6fad7777f58d10668231c9b36d42c630' => $baseDir . '/inc/traits/trait-wp-ultimo-site-deprecated.php',
    '934be1d61681808aeb0ba05066758f6b' => $baseDir . '/inc/traits/trait-wp-ultimo-settings-deprecated.php',
    'c64ba798c5243232ecddc1f5d8f601fd' => $baseDir . '/inc/models/traits/trait-limitable.php',
    'aa4242508af3904081d57f1d25a5e84d' => $baseDir . '/inc/models/traits/trait-billable.php',
);
