<?php
/**
 * Country Class for Russia (RU).
 *
 * State/province count: 84
 * City count: 5545
 * City count per state/province:
 * - UA-40: 147 cities
 * - MOS: 332 cities
 * - KDA: 229 cities
 * - DA: 175 cities
 * - ALT: 153 cities
 * - LEN: 141 cities
 * - SVE: 138 cities
 * - NIZ: 127 cities
 * - STA: 120 cities
 * - BA: 111 cities
 * - KYA: 109 cities
 * - ROS: 109 cities
 * - TA: 105 cities
 * - PRI: 96 cities
 * - CHE: 94 cities
 * - VOR: 92 cities
 * - MOW: 92 cities
 * - KIR: 89 cities
 * - TVE: 89 cities
 * - SA: 86 cities
 * - CE: 85 cities
 * - PER: 83 cities
 * - BRY: 83 cities
 * - VGG: 82 cities
 * - ZAB: 75 cities
 * - KEM: 72 cities
 * - SAR: 71 cities
 * - ARK: 71 cities
 * - KLU: 70 cities
 * - VLA: 66 cities
 * - BU: 66 cities
 * - TUL: 64 cities
 * - KB: 64 cities
 * - SAM: 64 cities
 * - VLG: 63 cities
 * - IVA: 61 cities
 * - NVS: 59 cities
 * - SPE: 58 cities
 * - AMU: 58 cities
 * - BEL: 56 cities
 * - NGR: 54 cities
 * - ORE: 52 cities
 * - YAR: 52 cities
 * - KO: 51 cities
 * - CU: 49 cities
 * - RYA: 48 cities
 * - MO: 48 cities
 * - KR: 48 cities
 * - PNZ: 47 cities
 * - LIP: 47 cities
 * - TYU: 46 cities
 * - ULY: 45 cities
 * - KHM: 44 cities
 * - KOS: 44 cities
 * - KRS: 44 cities
 * - PSK: 44 cities
 * - MUR: 42 cities
 * - SAK: 42 cities
 * - AST: 40 cities
 * - KHA: 40 cities
 * - OMS: 38 cities
 * - KGD: 37 cities
 * - UD: 36 cities
 * - SMO: 36 cities
 * - TAM: 35 cities
 * - ME: 35 cities
 * - KC: 34 cities
 * - SE: 31 cities
 * - KGN: 31 cities
 * - AD: 30 cities
 * - TOM: 30 cities
 * - ORL: 27 cities
 * - KAM: 26 cities
 * - AL: 25 cities
 * - IN: 25 cities
 * - YAN: 24 cities
 * - KK: 22 cities
 * - MAG: 22 cities
 * - TY: 21 cities
 * - YEV: 18 cities
 * - KL: 18 cities
 * - CHU: 10 cities
 * - NEN: 2 cities
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

namespace WP_Ultimo\Country;

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * Country Class for Russia (RU).
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @property-read string $code
 * @property-read string $currency
 * @property-read int $phone_code
 */
class Country_RU extends Country {

	use \WP_Ultimo\Traits\Singleton;

	/**
	 * General country attributes.
	 *
	 * This might be useful, might be not.
	 * In case of doubt, keep it.
	 *
	 * @since 2.0.11
	 * @var array
	 */
	protected $attributes = array(
		'country_code' => 'RU',
		'currency'     => 'RUB',
		'phone_code'   => 7,
	);

	/**
	 * The type of nomenclature used to refer to the country sub-divisions.
	 *
	 * @since 2.0.11
	 * @var string
	 */
	protected $state_type = 'unknown';

	/**
	 * Return the country name.
	 *
	 * @since 2.0.11
	 * @return string
	 */
	public function get_name() {

		return __('Russia', 'wp-ultimo');

	} // end get_name;

	/**
	 * Returns the list of states for RU.
	 *
	 * @since 2.0.11
	 * @return array The list of state/provinces for the country.
	 */
	protected function states() {

		return array(
			'ALT' => __('Altai Krai', 'wp-ultimo'),
			'AL' => __('Altai Republic', 'wp-ultimo'),
			'AMU' => __('Amur Oblast', 'wp-ultimo'),
			'ARK' => __('Arkhangelsk', 'wp-ultimo'),
			'AST' => __('Astrakhan Oblast', 'wp-ultimo'),
			'BEL' => __('Belgorod Oblast', 'wp-ultimo'),
			'BRY' => __('Bryansk Oblast', 'wp-ultimo'),
			'CE' => __('Chechen Republic', 'wp-ultimo'),
			'CHE' => __('Chelyabinsk Oblast', 'wp-ultimo'),
			'CHU' => __('Chukotka Autonomous Okrug', 'wp-ultimo'),
			'CU' => __('Chuvash Republic', 'wp-ultimo'),
			'IRK' => __('Irkutsk', 'wp-ultimo'),
			'IVA' => __('Ivanovo Oblast', 'wp-ultimo'),
			'YEV' => __('Jewish Autonomous Oblast', 'wp-ultimo'),
			'KB' => __('Kabardino-Balkar Republic', 'wp-ultimo'),
			'KGD' => __('Kaliningrad', 'wp-ultimo'),
			'KLU' => __('Kaluga Oblast', 'wp-ultimo'),
			'KAM' => __('Kamchatka Krai', 'wp-ultimo'),
			'KC' => __('Karachay-Cherkess Republic', 'wp-ultimo'),
			'KEM' => __('Kemerovo Oblast', 'wp-ultimo'),
			'KHA' => __('Khabarovsk Krai', 'wp-ultimo'),
			'KHM' => __('Khanty-Mansi Autonomous Okrug', 'wp-ultimo'),
			'KIR' => __('Kirov Oblast', 'wp-ultimo'),
			'KO' => __('Komi Republic', 'wp-ultimo'),
			'KOS' => __('Kostroma Oblast', 'wp-ultimo'),
			'KDA' => __('Krasnodar Krai', 'wp-ultimo'),
			'KYA' => __('Krasnoyarsk Krai', 'wp-ultimo'),
			'KGN' => __('Kurgan Oblast', 'wp-ultimo'),
			'KRS' => __('Kursk Oblast', 'wp-ultimo'),
			'LEN' => __('Leningrad Oblast', 'wp-ultimo'),
			'LIP' => __('Lipetsk Oblast', 'wp-ultimo'),
			'MAG' => __('Magadan Oblast', 'wp-ultimo'),
			'ME' => __('Mari El Republic', 'wp-ultimo'),
			'MOW' => __('Moscow', 'wp-ultimo'),
			'MOS' => __('Moscow Oblast', 'wp-ultimo'),
			'MUR' => __('Murmansk Oblast', 'wp-ultimo'),
			'NEN' => __('Nenets Autonomous Okrug', 'wp-ultimo'),
			'NIZ' => __('Nizhny Novgorod Oblast', 'wp-ultimo'),
			'NGR' => __('Novgorod Oblast', 'wp-ultimo'),
			'NVS' => __('Novosibirsk', 'wp-ultimo'),
			'OMS' => __('Omsk Oblast', 'wp-ultimo'),
			'ORE' => __('Orenburg Oblast', 'wp-ultimo'),
			'ORL' => __('Oryol Oblast', 'wp-ultimo'),
			'PNZ' => __('Penza Oblast', 'wp-ultimo'),
			'PER' => __('Perm Krai', 'wp-ultimo'),
			'PRI' => __('Primorsky Krai', 'wp-ultimo'),
			'PSK' => __('Pskov Oblast', 'wp-ultimo'),
			'AD' => __('Republic of Adygea', 'wp-ultimo'),
			'BA' => __('Republic of Bashkortostan', 'wp-ultimo'),
			'BU' => __('Republic of Buryatia', 'wp-ultimo'),
			'DA' => __('Republic of Dagestan', 'wp-ultimo'),
			'IN' => __('Republic of Ingushetia', 'wp-ultimo'),
			'KL' => __('Republic of Kalmykia', 'wp-ultimo'),
			'KR' => __('Republic of Karelia', 'wp-ultimo'),
			'KK' => __('Republic of Khakassia', 'wp-ultimo'),
			'MO' => __('Republic of Mordovia', 'wp-ultimo'),
			'SE' => __('Republic of North Ossetia-Alania', 'wp-ultimo'),
			'TA' => __('Republic of Tatarstan', 'wp-ultimo'),
			'ROS' => __('Rostov Oblast', 'wp-ultimo'),
			'RYA' => __('Ryazan Oblast', 'wp-ultimo'),
			'SPE' => __('Saint Petersburg', 'wp-ultimo'),
			'SA' => __('Sakha Republic', 'wp-ultimo'),
			'SAK' => __('Sakhalin', 'wp-ultimo'),
			'SAM' => __('Samara Oblast', 'wp-ultimo'),
			'SAR' => __('Saratov Oblast', 'wp-ultimo'),
			'UA-40' => __('Sevastopol', 'wp-ultimo'),
			'SMO' => __('Smolensk Oblast', 'wp-ultimo'),
			'STA' => __('Stavropol Krai', 'wp-ultimo'),
			'SVE' => __('Sverdlovsk', 'wp-ultimo'),
			'TAM' => __('Tambov Oblast', 'wp-ultimo'),
			'TOM' => __('Tomsk Oblast', 'wp-ultimo'),
			'TUL' => __('Tula Oblast', 'wp-ultimo'),
			'TY' => __('Tuva Republic', 'wp-ultimo'),
			'TVE' => __('Tver Oblast', 'wp-ultimo'),
			'TYU' => __('Tyumen Oblast', 'wp-ultimo'),
			'UD' => __('Udmurt Republic', 'wp-ultimo'),
			'ULY' => __('Ulyanovsk Oblast', 'wp-ultimo'),
			'VLA' => __('Vladimir Oblast', 'wp-ultimo'),
			'VGG' => __('Volgograd Oblast', 'wp-ultimo'),
			'VLG' => __('Vologda Oblast', 'wp-ultimo'),
			'VOR' => __('Voronezh Oblast', 'wp-ultimo'),
			'YAN' => __('Yamalo-Nenets Autonomous Okrug', 'wp-ultimo'),
			'YAR' => __('Yaroslavl Oblast', 'wp-ultimo'),
			'ZAB' => __('Zabaykalsky Krai', 'wp-ultimo'),
		);

	} // end states;

} // end class Country_RU;
