<?php
/**
 * Country Class for The Netherlands (NL).
 *
 * State/province count: 15
 * City count: 1740
 * City count per state/province:
 * - NB: 317 cities
 * - GE: 271 cities
 * - ZH: 224 cities
 * - LI: 205 cities
 * - NH: 172 cities
 * - FR: 132 cities
 * - OV: 90 cities
 * - UT: 86 cities
 * - GR: 79 cities
 * - DR: 76 cities
 * - ZE: 74 cities
 * - FL: 14 cities
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

namespace WP_Ultimo\Country;

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * Country Class for The Netherlands (NL).
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @property-read string $code
 * @property-read string $currency
 * @property-read int $phone_code
 */
class Country_NL extends Country {

	use \WP_Ultimo\Traits\Singleton;

	/**
	 * General country attributes.
	 *
	 * This might be useful, might be not.
	 * In case of doubt, keep it.
	 *
	 * @since 2.0.11
	 * @var array
	 */
	protected $attributes = array(
		'country_code' => 'NL',
		'currency'     => 'EUR',
		'phone_code'   => 31,
	);

	/**
	 * The type of nomenclature used to refer to the country sub-divisions.
	 *
	 * @since 2.0.11
	 * @var string
	 */
	protected $state_type = 'province';

	/**
	 * Return the country name.
	 *
	 * @since 2.0.11
	 * @return string
	 */
	public function get_name() {

		return __('The Netherlands', 'wp-ultimo');

	} // end get_name;

	/**
	 * Returns the list of states for NL.
	 *
	 * @since 2.0.11
	 * @return array The list of state/provinces for the country.
	 */
	protected function states() {

		return array(
			'BQ1' => __('Bonaire', 'wp-ultimo'),
			'DR' => __('Drenthe', 'wp-ultimo'),
			'FL' => __('Flevoland', 'wp-ultimo'),
			'FR' => __('Friesland', 'wp-ultimo'),
			'GE' => __('Gelderland', 'wp-ultimo'),
			'GR' => __('Groningen', 'wp-ultimo'),
			'LI' => __('Limburg', 'wp-ultimo'),
			'NB' => __('North Brabant', 'wp-ultimo'),
			'NH' => __('North Holland', 'wp-ultimo'),
			'OV' => __('Overijssel', 'wp-ultimo'),
			'BQ2' => __('Saba', 'wp-ultimo'),
			'BQ3' => __('Sint Eustatius', 'wp-ultimo'),
			'ZH' => __('South Holland', 'wp-ultimo'),
			'UT' => __('Utrecht', 'wp-ultimo'),
			'ZE' => __('Zeeland', 'wp-ultimo'),
		);

	} // end states;

} // end class Country_NL;
