<?php
/**
 * Country Class for United States (US).
 *
 * State/province count: 66
 * City count: 19817
 * City count per state/province:
 * - TX: 1277 cities
 * - CA: 1123 cities
 * - NY: 1054 cities
 * - PA: 1053 cities
 * - IL: 855 cities
 * - FL: 845 cities
 * - OH: 756 cities
 * - NC: 554 cities
 * - NJ: 549 cities
 * - GA: 534 cities
 * - MI: 526 cities
 * - MO: 510 cities
 * - VA: 503 cities
 * - WI: 492 cities
 * - MN: 460 cities
 * - IN: 434 cities
 * - WA: 433 cities
 * - MA: 404 cities
 * - KY: 388 cities
 * - TN: 386 cities
 * - IA: 383 cities
 * - AL: 378 cities
 * - MD: 364 cities
 * - LA: 344 cities
 * - OK: 320 cities
 * - KS: 319 cities
 * - MS: 295 cities
 * - CO: 289 cities
 * - AR: 287 cities
 * - SC: 283 cities
 * - ME: 271 cities
 * - PR: 255 cities
 * - OR: 255 cities
 * - NE: 238 cities
 * - AZ: 227 cities
 * - WV: 217 cities
 * - UT: 207 cities
 * - CT: 191 cities
 * - NH: 186 cities
 * - NM: 182 cities
 * - SD: 167 cities
 * - MT: 161 cities
 * - ID: 142 cities
 * - ND: 133 cities
 * - HI: 121 cities
 * - VT: 96 cities
 * - AK: 95 cities
 * - NV: 82 cities
 * - WY: 80 cities
 * - RI: 54 cities
 * - DE: 54 cities
 * - DC: 5 cities
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

namespace WP_Ultimo\Country;

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * Country Class for United States (US).
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @property-read string $code
 * @property-read string $currency
 * @property-read int $phone_code
 */
class Country_US extends Country {

	use \WP_Ultimo\Traits\Singleton;

	/**
	 * General country attributes.
	 *
	 * This might be useful, might be not.
	 * In case of doubt, keep it.
	 *
	 * @since 2.0.11
	 * @var array
	 */
	protected $attributes = array(
		'country_code' => 'US',
		'currency'     => 'USD',
		'phone_code'   => 1,
	);

	/**
	 * The type of nomenclature used to refer to the country sub-divisions.
	 *
	 * @since 2.0.11
	 * @var string
	 */
	protected $state_type = 'state';

	/**
	 * Return the country name.
	 *
	 * @since 2.0.11
	 * @return string
	 */
	public function get_name() {

		return __('United States', 'wp-ultimo');

	} // end get_name;

	/**
	 * Returns the list of states for US.
	 *
	 * @since 2.0.11
	 * @return array The list of state/provinces for the country.
	 */
	protected function states() {

		return array(
			'AL' => __('Alabama', 'wp-ultimo'),
			'AK' => __('Alaska', 'wp-ultimo'),
			'AS' => __('American Samoa', 'wp-ultimo'),
			'AZ' => __('Arizona', 'wp-ultimo'),
			'AR' => __('Arkansas', 'wp-ultimo'),
			'UM-81' => __('Baker Island', 'wp-ultimo'),
			'CA' => __('California', 'wp-ultimo'),
			'CO' => __('Colorado', 'wp-ultimo'),
			'CT' => __('Connecticut', 'wp-ultimo'),
			'DE' => __('Delaware', 'wp-ultimo'),
			'DC' => __('District of Columbia', 'wp-ultimo'),
			'FL' => __('Florida', 'wp-ultimo'),
			'GA' => __('Georgia', 'wp-ultimo'),
			'GU' => __('Guam', 'wp-ultimo'),
			'HI' => __('Hawaii', 'wp-ultimo'),
			'UM-84' => __('Howland Island', 'wp-ultimo'),
			'ID' => __('Idaho', 'wp-ultimo'),
			'IL' => __('Illinois', 'wp-ultimo'),
			'IN' => __('Indiana', 'wp-ultimo'),
			'IA' => __('Iowa', 'wp-ultimo'),
			'UM-86' => __('Jarvis Island', 'wp-ultimo'),
			'UM-67' => __('Johnston Atoll', 'wp-ultimo'),
			'KS' => __('Kansas', 'wp-ultimo'),
			'KY' => __('Kentucky', 'wp-ultimo'),
			'UM-89' => __('Kingman Reef', 'wp-ultimo'),
			'LA' => __('Louisiana', 'wp-ultimo'),
			'ME' => __('Maine', 'wp-ultimo'),
			'MD' => __('Maryland', 'wp-ultimo'),
			'MA' => __('Massachusetts', 'wp-ultimo'),
			'MI' => __('Michigan', 'wp-ultimo'),
			'UM-71' => __('Midway Atoll', 'wp-ultimo'),
			'MN' => __('Minnesota', 'wp-ultimo'),
			'MS' => __('Mississippi', 'wp-ultimo'),
			'MO' => __('Missouri', 'wp-ultimo'),
			'MT' => __('Montana', 'wp-ultimo'),
			'UM-76' => __('Navassa Island', 'wp-ultimo'),
			'NE' => __('Nebraska', 'wp-ultimo'),
			'NV' => __('Nevada', 'wp-ultimo'),
			'NH' => __('New Hampshire', 'wp-ultimo'),
			'NJ' => __('New Jersey', 'wp-ultimo'),
			'NM' => __('New Mexico', 'wp-ultimo'),
			'NY' => __('New York', 'wp-ultimo'),
			'NC' => __('North Carolina', 'wp-ultimo'),
			'ND' => __('North Dakota', 'wp-ultimo'),
			'MP' => __('Northern Mariana Islands', 'wp-ultimo'),
			'OH' => __('Ohio', 'wp-ultimo'),
			'OK' => __('Oklahoma', 'wp-ultimo'),
			'OR' => __('Oregon', 'wp-ultimo'),
			'UM-95' => __('Palmyra Atoll', 'wp-ultimo'),
			'PA' => __('Pennsylvania', 'wp-ultimo'),
			'PR' => __('Puerto Rico', 'wp-ultimo'),
			'RI' => __('Rhode Island', 'wp-ultimo'),
			'SC' => __('South Carolina', 'wp-ultimo'),
			'SD' => __('South Dakota', 'wp-ultimo'),
			'TN' => __('Tennessee', 'wp-ultimo'),
			'TX' => __('Texas', 'wp-ultimo'),
			'UM' => __('United States Minor Outlying Islands', 'wp-ultimo'),
			'VI' => __('United States Virgin Islands', 'wp-ultimo'),
			'UT' => __('Utah', 'wp-ultimo'),
			'VT' => __('Vermont', 'wp-ultimo'),
			'VA' => __('Virginia', 'wp-ultimo'),
			'UM-79' => __('Wake Island', 'wp-ultimo'),
			'WA' => __('Washington', 'wp-ultimo'),
			'WV' => __('West Virginia', 'wp-ultimo'),
			'WI' => __('Wisconsin', 'wp-ultimo'),
			'WY' => __('Wyoming', 'wp-ultimo'),
		);

	} // end states;

} // end class Country_US;
