<?php
/**
 * State City List for AH - CN.
 *
 * City count: 37
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for AH - CN.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Anqing', 'wp-ultimo'),
	__('Anqing Shi', 'wp-ultimo'),
	__('Bengbu', 'wp-ultimo'),
	__('Bozhou', 'wp-ultimo'),
	__('Chaohu', 'wp-ultimo'),
	__('Chizhou', 'wp-ultimo'),
	__('Chizhou Shi', 'wp-ultimo'),
	__('Chuzhou', 'wp-ultimo'),
	__('Chuzhou Shi', 'wp-ultimo'),
	__('Datong', 'wp-ultimo'),
	__('Fuyang', 'wp-ultimo'),
	__('Fuyang Shi', 'wp-ultimo'),
	__('Gushu', 'wp-ultimo'),
	__('Hefei', 'wp-ultimo'),
	__('Hefei Shi', 'wp-ultimo'),
	__('Huaibei', 'wp-ultimo'),
	__('Huainan', 'wp-ultimo'),
	__('Huainan Shi', 'wp-ultimo'),
	__('Huaiyuan Chengguanzhen', 'wp-ultimo'),
	__('Huangshan', 'wp-ultimo'),
	__('Huangshan Shi', 'wp-ultimo'),
	__('Huoqiu Chengguanzhen', 'wp-ultimo'),
	__('Jieshou', 'wp-ultimo'),
	__('Lucheng', 'wp-ultimo'),
	__('Lu’an', 'wp-ultimo'),
	__('Mengcheng Chengguanzhen', 'wp-ultimo'),
	__('Mingguang', 'wp-ultimo'),
	__('Suixi', 'wp-ultimo'),
	__('Suzhou', 'wp-ultimo'),
	__('Suzhou Shi', 'wp-ultimo'),
	__('Tangzhai', 'wp-ultimo'),
	__('Wucheng', 'wp-ultimo'),
	__('Wuhu', 'wp-ultimo'),
	__('Wusong', 'wp-ultimo'),
	__('Wuyang', 'wp-ultimo'),
	__('Xuanzhou', 'wp-ultimo'),
	__('Yingshang Chengguanzhen', 'wp-ultimo'),
);
