<?php
/**
 * State City List for BJ - CN.
 *
 * City count: 8
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for BJ - CN.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Beijing', 'wp-ultimo'),
	__('Changping', 'wp-ultimo'),
	__('Daxing', 'wp-ultimo'),
	__('Fangshan', 'wp-ultimo'),
	__('Liangxiang', 'wp-ultimo'),
	__('Mentougou', 'wp-ultimo'),
	__('Shunyi', 'wp-ultimo'),
	__('Tongzhou', 'wp-ultimo'),
);
