<?php
/**
 * State City List for CQ - CN.
 *
 * City count: 18
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for CQ - CN.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Beibei', 'wp-ultimo'),
	__('Caijia', 'wp-ultimo'),
	__('Chongqing', 'wp-ultimo'),
	__('Dongxi', 'wp-ultimo'),
	__('Fuling', 'wp-ultimo'),
	__('Ganshui', 'wp-ultimo'),
	__('Guofuchang', 'wp-ultimo'),
	__('Hechuan', 'wp-ultimo'),
	__('Jijiang', 'wp-ultimo'),
	__('Liangping District', 'wp-ultimo'),
	__('Puhechang', 'wp-ultimo'),
	__('Shapingba District', 'wp-ultimo'),
	__('Shijiaochang', 'wp-ultimo'),
	__('Wanxian', 'wp-ultimo'),
	__('Wanzhou District', 'wp-ultimo'),
	__('Yongchuan', 'wp-ultimo'),
	__('Yudong', 'wp-ultimo'),
	__('Yuzhong District', 'wp-ultimo'),
);
