<?php
/**
 * State City List for GD - CN.
 *
 * City count: 72
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for GD - CN.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Anbu', 'wp-ultimo'),
	__('Chaozhou', 'wp-ultimo'),
	__('Chenghua', 'wp-ultimo'),
	__('Daliang', 'wp-ultimo'),
	__('Danshui', 'wp-ultimo'),
	__('Dasha', 'wp-ultimo'),
	__('Dongguan', 'wp-ultimo'),
	__('Donghai', 'wp-ultimo'),
	__('Ducheng', 'wp-ultimo'),
	__('Encheng', 'wp-ultimo'),
	__('Foshan', 'wp-ultimo'),
	__('Foshan Shi', 'wp-ultimo'),
	__('Gaoyao', 'wp-ultimo'),
	__('Gaozhou', 'wp-ultimo'),
	__('Guangzhou', 'wp-ultimo'),
	__('Guangzhou Shi', 'wp-ultimo'),
	__('Haikuotiankong', 'wp-ultimo'),
	__('Haimen', 'wp-ultimo'),
	__('Hepo', 'wp-ultimo'),
	__('Heyuan', 'wp-ultimo'),
	__('Huaicheng', 'wp-ultimo'),
	__('Huanggang', 'wp-ultimo'),
	__('Huazhou', 'wp-ultimo'),
	__('Huicheng', 'wp-ultimo'),
	__('Huizhou', 'wp-ultimo'),
	__('Humen', 'wp-ultimo'),
	__('Jiangmen', 'wp-ultimo'),
	__('Jiazi', 'wp-ultimo'),
	__('Jieshi', 'wp-ultimo'),
	__('Jieyang', 'wp-ultimo'),
	__('Lecheng', 'wp-ultimo'),
	__('Lianjiang', 'wp-ultimo'),
	__('Lianzhou', 'wp-ultimo'),
	__('Licheng', 'wp-ultimo'),
	__('Lubu', 'wp-ultimo'),
	__('Luocheng', 'wp-ultimo'),
	__('Luoyang', 'wp-ultimo'),
	__('Maba', 'wp-ultimo'),
	__('Maoming', 'wp-ultimo'),
	__('Meizhou', 'wp-ultimo'),
	__('Nanfeng', 'wp-ultimo'),
	__('Pingshan', 'wp-ultimo'),
	__('Puning', 'wp-ultimo'),
	__('Qingyuan', 'wp-ultimo'),
	__('Sanshui', 'wp-ultimo'),
	__('Shantou', 'wp-ultimo'),
	__('Shanwei', 'wp-ultimo'),
	__('Shaoguan', 'wp-ultimo'),
	__('Shaping', 'wp-ultimo'),
	__('Shenzhen', 'wp-ultimo'),
	__('Shilong', 'wp-ultimo'),
	__('Shiqi', 'wp-ultimo'),
	__('Shiqiao', 'wp-ultimo'),
	__('Shiwan', 'wp-ultimo'),
	__('Shixing', 'wp-ultimo'),
	__('Taishan', 'wp-ultimo'),
	__('Tangping', 'wp-ultimo'),
	__('Wuchuan', 'wp-ultimo'),
	__('Xingning', 'wp-ultimo'),
	__('Xinhui', 'wp-ultimo'),
	__('Xinyi', 'wp-ultimo'),
	__('Xiongzhou', 'wp-ultimo'),
	__('Xucheng', 'wp-ultimo'),
	__('Yangchun', 'wp-ultimo'),
	__('Yangjiang', 'wp-ultimo'),
	__('Yingcheng', 'wp-ultimo'),
	__('Yunfu', 'wp-ultimo'),
	__('Zhanjiang', 'wp-ultimo'),
	__('Zhaoqing', 'wp-ultimo'),
	__('Zhongshan', 'wp-ultimo'),
	__('Zhongshan Prefecture', 'wp-ultimo'),
	__('Zhuhai', 'wp-ultimo'),
);
