<?php
/**
 * State City List for GS - CN.
 *
 * City count: 20
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for GS - CN.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Baiyin', 'wp-ultimo'),
	__('Beidao', 'wp-ultimo'),
	__('Dingxi Shi', 'wp-ultimo'),
	__('Hezuo', 'wp-ultimo'),
	__('Jiayuguan', 'wp-ultimo'),
	__('Jinchang', 'wp-ultimo'),
	__('Jiuquan', 'wp-ultimo'),
	__('Lanzhou', 'wp-ultimo'),
	__('Laojunmiao', 'wp-ultimo'),
	__('Linxia Chengguanzhen', 'wp-ultimo'),
	__('Linxia Huizu Zizhizhou', 'wp-ultimo'),
	__('Longnan Shi', 'wp-ultimo'),
	__('Mawu', 'wp-ultimo'),
	__('Pingliang', 'wp-ultimo'),
	__('Qincheng', 'wp-ultimo'),
	__('Qingyang Shi', 'wp-ultimo'),
	__('Tianshui', 'wp-ultimo'),
	__('Wuwei', 'wp-ultimo'),
	__('Zhangye', 'wp-ultimo'),
	__('Zhangye Shi', 'wp-ultimo'),
);
