<?php
/**
 * State City List for GX - CN.
 *
 * City count: 28
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for GX - CN.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Babu', 'wp-ultimo'),
	__('Baihe', 'wp-ultimo'),
	__('Baise City', 'wp-ultimo'),
	__('Baise Shi', 'wp-ultimo'),
	__('Beihai', 'wp-ultimo'),
	__('Chongzuo Shi', 'wp-ultimo'),
	__('Dazhai', 'wp-ultimo'),
	__('Fangchenggang Shi', 'wp-ultimo'),
	__('Guigang', 'wp-ultimo'),
	__('Guilin', 'wp-ultimo'),
	__('Guilin Shi', 'wp-ultimo'),
	__('Guiping', 'wp-ultimo'),
	__('Hechi Shi', 'wp-ultimo'),
	__('Jinji', 'wp-ultimo'),
	__('Laibin', 'wp-ultimo'),
	__('Lianzhou', 'wp-ultimo'),
	__('Lingcheng', 'wp-ultimo'),
	__('Liuzhou Shi', 'wp-ultimo'),
	__('Luorong', 'wp-ultimo'),
	__('Nandu', 'wp-ultimo'),
	__('Nanning', 'wp-ultimo'),
	__('Pingnan', 'wp-ultimo'),
	__('Pumiao', 'wp-ultimo'),
	__('Qinzhou', 'wp-ultimo'),
	__('Wuzhou', 'wp-ultimo'),
	__('Yangshuo', 'wp-ultimo'),
	__('Yashan', 'wp-ultimo'),
	__('Yulin', 'wp-ultimo'),
);
