<?php
/**
 * State City List for GZ - CN.
 *
 * City count: 54
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for GZ - CN.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Anshun', 'wp-ultimo'),
	__('Aoshi', 'wp-ultimo'),
	__('Bahuang', 'wp-ultimo'),
	__('Baishi', 'wp-ultimo'),
	__('Bangdong', 'wp-ultimo'),
	__('Benchu', 'wp-ultimo'),
	__('Bijie', 'wp-ultimo'),
	__('Chadian', 'wp-ultimo'),
	__('Changsha', 'wp-ultimo'),
	__('Chumi', 'wp-ultimo'),
	__('Dabachang', 'wp-ultimo'),
	__('Darong', 'wp-ultimo'),
	__('Dundong', 'wp-ultimo'),
	__('Duyun', 'wp-ultimo'),
	__('Gaoniang', 'wp-ultimo'),
	__('Gaowu', 'wp-ultimo'),
	__('Gaozeng', 'wp-ultimo'),
	__('Guandu', 'wp-ultimo'),
	__('Guiyang', 'wp-ultimo'),
	__('Hongzhou', 'wp-ultimo'),
	__('Huaqiu', 'wp-ultimo'),
	__('Lantian', 'wp-ultimo'),
	__('Liangcunchang', 'wp-ultimo'),
	__('Liupanshui', 'wp-ultimo'),
	__('Longlisuo', 'wp-ultimo'),
	__('Loushanguan', 'wp-ultimo'),
	__('Maoping', 'wp-ultimo'),
	__('Ouyang', 'wp-ultimo'),
	__('Pingjiang', 'wp-ultimo'),
	__('Qiandongnan Miao and Dong Autonomous Prefecture', 'wp-ultimo'),
	__('Qianxinan Bouyeizu Miaozu Zizhizhou', 'wp-ultimo'),
	__('Qimeng', 'wp-ultimo'),
	__('Qinglang', 'wp-ultimo'),
	__('Runsong', 'wp-ultimo'),
	__('Sanchahe', 'wp-ultimo'),
	__('Sangmu', 'wp-ultimo'),
	__('Shiqian', 'wp-ultimo'),
	__('Songkan', 'wp-ultimo'),
	__('Tingdong', 'wp-ultimo'),
	__('Tonggu', 'wp-ultimo'),
	__('Tongren', 'wp-ultimo'),
	__('Tongren Diqu', 'wp-ultimo'),
	__('Weining', 'wp-ultimo'),
	__('Wenshui', 'wp-ultimo'),
	__('Xiajiang', 'wp-ultimo'),
	__('Xiaoweizhai', 'wp-ultimo'),
	__('Xinzhan', 'wp-ultimo'),
	__('Xishan', 'wp-ultimo'),
	__('Xujiaba', 'wp-ultimo'),
	__('Yangtou', 'wp-ultimo'),
	__('Youyupu', 'wp-ultimo'),
	__('Zhongchao', 'wp-ultimo'),
	__('Zhujiachang', 'wp-ultimo'),
	__('Zunyi', 'wp-ultimo'),
);
