<?php
/**
 * State City List for HA - CN.
 *
 * City count: 55
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for HA - CN.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Anyang', 'wp-ultimo'),
	__('Anyang Shi', 'wp-ultimo'),
	__('Binhe', 'wp-ultimo'),
	__('Chengguan', 'wp-ultimo'),
	__('Chengjiao', 'wp-ultimo'),
	__('Daokou', 'wp-ultimo'),
	__('Dingcheng', 'wp-ultimo'),
	__('Hancheng', 'wp-ultimo'),
	__('Hebi', 'wp-ultimo'),
	__('Huaidian', 'wp-ultimo'),
	__('Huazhou', 'wp-ultimo'),
	__('Huichang', 'wp-ultimo'),
	__('Jianshe', 'wp-ultimo'),
	__('Jiaozuo', 'wp-ultimo'),
	__('Jishui', 'wp-ultimo'),
	__('Jiyuan', 'wp-ultimo'),
	__('Kaifeng', 'wp-ultimo'),
	__('Kaiyuan', 'wp-ultimo'),
	__('Lingbao Chengguanzhen', 'wp-ultimo'),
	__('Luohe', 'wp-ultimo'),
	__('Luohe Shi', 'wp-ultimo'),
	__('Luoyang', 'wp-ultimo'),
	__('Minggang', 'wp-ultimo'),
	__('Nanyang', 'wp-ultimo'),
	__('Pingdingshan', 'wp-ultimo'),
	__('Puyang Chengguanzhen', 'wp-ultimo'),
	__('Puyang Shi', 'wp-ultimo'),
	__('Qingping', 'wp-ultimo'),
	__('Runing', 'wp-ultimo'),
	__('Ruzhou', 'wp-ultimo'),
	__('Shangqiu', 'wp-ultimo'),
	__('Songyang', 'wp-ultimo'),
	__('Suohe', 'wp-ultimo'),
	__('Tanbei', 'wp-ultimo'),
	__('Wacheng', 'wp-ultimo'),
	__('Xiangcheng Chengguanzhen', 'wp-ultimo'),
	__('Xincheng', 'wp-ultimo'),
	__('Xinhualu', 'wp-ultimo'),
	__('Xinxiang', 'wp-ultimo'),
	__('Xinxiang Shi', 'wp-ultimo'),
	__('Xinyang', 'wp-ultimo'),
	__('Xixiang', 'wp-ultimo'),
	__('Xuchang', 'wp-ultimo'),
	__('Xuchang Shi', 'wp-ultimo'),
	__('Yakou', 'wp-ultimo'),
	__('Yanshi Chengguanzhen', 'wp-ultimo'),
	__('Yigou', 'wp-ultimo'),
	__('Yima', 'wp-ultimo'),
	__('Yingchuan', 'wp-ultimo'),
	__('Yunyang', 'wp-ultimo'),
	__('Zhengzhou', 'wp-ultimo'),
	__('Zhoukou', 'wp-ultimo'),
	__('Zhumadian', 'wp-ultimo'),
	__('Zhumadian Shi', 'wp-ultimo'),
	__('Zijinglu', 'wp-ultimo'),
);
