<?php
/**
 * State City List for HB - CN.
 *
 * City count: 55
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for HB - CN.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Anlu', 'wp-ultimo'),
	__('Buhe', 'wp-ultimo'),
	__('Caidian', 'wp-ultimo'),
	__('Caohe', 'wp-ultimo'),
	__('Chengzhong', 'wp-ultimo'),
	__('Danjiangkou', 'wp-ultimo'),
	__('Daye', 'wp-ultimo'),
	__('Duobao', 'wp-ultimo'),
	__('Enshi', 'wp-ultimo'),
	__('Enshi Tujiazu Miaozu Zizhizhou', 'wp-ultimo'),
	__('Ezhou', 'wp-ultimo'),
	__('Ezhou Shi', 'wp-ultimo'),
	__('Fengkou', 'wp-ultimo'),
	__('Guangshui', 'wp-ultimo'),
	__('Gucheng Chengguanzhen', 'wp-ultimo'),
	__('Hanchuan', 'wp-ultimo'),
	__('Huanggang', 'wp-ultimo'),
	__('Huangmei', 'wp-ultimo'),
	__('Huangpi', 'wp-ultimo'),
	__('Huangshi', 'wp-ultimo'),
	__('Huangzhou', 'wp-ultimo'),
	__('Jingling', 'wp-ultimo'),
	__('Jingmen', 'wp-ultimo'),
	__('Jingmen Shi', 'wp-ultimo'),
	__('Jingzhou', 'wp-ultimo'),
	__('Laohekou', 'wp-ultimo'),
	__('Lichuan', 'wp-ultimo'),
	__('Macheng', 'wp-ultimo'),
	__('Nanzhang Chengguanzhen', 'wp-ultimo'),
	__('Puqi', 'wp-ultimo'),
	__('Qianjiang', 'wp-ultimo'),
	__('Qingquan', 'wp-ultimo'),
	__('Shashi', 'wp-ultimo'),
	__('Shennongjia', 'wp-ultimo'),
	__('Shiyan', 'wp-ultimo'),
	__('Suizhou', 'wp-ultimo'),
	__('Wuhan', 'wp-ultimo'),
	__('Wuxue', 'wp-ultimo'),
	__('Xiangyang', 'wp-ultimo'),
	__('Xianning', 'wp-ultimo'),
	__('Xianning Prefecture', 'wp-ultimo'),
	__('Xiantao', 'wp-ultimo'),
	__('Xiaogan', 'wp-ultimo'),
	__('Xihe', 'wp-ultimo'),
	__('Xindi', 'wp-ultimo'),
	__('Xinshi', 'wp-ultimo'),
	__('Xinzhou', 'wp-ultimo'),
	__('Xiulin', 'wp-ultimo'),
	__('Yichang', 'wp-ultimo'),
	__('Yicheng', 'wp-ultimo'),
	__('Yunmeng Chengguanzhen', 'wp-ultimo'),
	__('Zaoyang', 'wp-ultimo'),
	__('Zhicheng', 'wp-ultimo'),
	__('Zhijiang', 'wp-ultimo'),
	__('Zhongxiang', 'wp-ultimo'),
);
