<?php
/**
 * State City List for HE - CN.
 *
 * City count: 39
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for HE - CN.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Baoding', 'wp-ultimo'),
	__('Beidaihehaibin', 'wp-ultimo'),
	__('Botou', 'wp-ultimo'),
	__('Cangzhou', 'wp-ultimo'),
	__('Cangzhou Shi', 'wp-ultimo'),
	__('Changli', 'wp-ultimo'),
	__('Chengde', 'wp-ultimo'),
	__('Chengde Prefecture', 'wp-ultimo'),
	__('Dingzhou', 'wp-ultimo'),
	__('Fengrun', 'wp-ultimo'),
	__('Guye', 'wp-ultimo'),
	__('Handan', 'wp-ultimo'),
	__('Hecun', 'wp-ultimo'),
	__('Hengshui', 'wp-ultimo'),
	__('Langfang', 'wp-ultimo'),
	__('Langfang Shi', 'wp-ultimo'),
	__('Linshui', 'wp-ultimo'),
	__('Linxi', 'wp-ultimo'),
	__('Luancheng', 'wp-ultimo'),
	__('Nangong', 'wp-ultimo'),
	__('Pengcheng', 'wp-ultimo'),
	__('Qinhuangdao', 'wp-ultimo'),
	__('Renqiu', 'wp-ultimo'),
	__('Shahecheng', 'wp-ultimo'),
	__('Shanhaiguan', 'wp-ultimo'),
	__('Shijiazhuang', 'wp-ultimo'),
	__('Shijiazhuang Shi', 'wp-ultimo'),
	__('Songling', 'wp-ultimo'),
	__('Tangjiazhuang', 'wp-ultimo'),
	__('Tangshan', 'wp-ultimo'),
	__('Tangshan Shi', 'wp-ultimo'),
	__('Tianchang', 'wp-ultimo'),
	__('Xingtai', 'wp-ultimo'),
	__('Xinji', 'wp-ultimo'),
	__('Zhangjiakou', 'wp-ultimo'),
	__('Zhangjiakou Shi', 'wp-ultimo'),
	__('Zhangjiakou Shi Xuanhua Qu', 'wp-ultimo'),
	__('Zhaogezhuang', 'wp-ultimo'),
	__('Zunhua', 'wp-ultimo'),
);
