<?php
/**
 * State City List for HI - CN.
 *
 * City count: 14
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for HI - CN.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Basuo', 'wp-ultimo'),
	__('Chongshan', 'wp-ultimo'),
	__('Dadonghai', 'wp-ultimo'),
	__('Haikou', 'wp-ultimo'),
	__('Jinjiang', 'wp-ultimo'),
	__('Lincheng', 'wp-ultimo'),
	__('Nada', 'wp-ultimo'),
	__('Qionghai', 'wp-ultimo'),
	__('Qiongshan', 'wp-ultimo'),
	__('Sansha', 'wp-ultimo'),
	__('Sanya', 'wp-ultimo'),
	__('Wanning', 'wp-ultimo'),
	__('Wenchang', 'wp-ultimo'),
	__('Xiuying', 'wp-ultimo'),
);
