<?php
/**
 * State City List for JL - CN.
 *
 * City count: 52
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for JL - CN.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Baicheng', 'wp-ultimo'),
	__('Baishan', 'wp-ultimo'),
	__('Baishishan', 'wp-ultimo'),
	__('Changchun', 'wp-ultimo'),
	__('Changling', 'wp-ultimo'),
	__('Chaoyang', 'wp-ultimo'),
	__('Dalai', 'wp-ultimo'),
	__('Dashitou', 'wp-ultimo'),
	__('Dehui', 'wp-ultimo'),
	__('Dongfeng', 'wp-ultimo'),
	__('Dunhua', 'wp-ultimo'),
	__('Erdaojiang', 'wp-ultimo'),
	__('Fuyu', 'wp-ultimo'),
	__('Gongzhuling', 'wp-ultimo'),
	__('Guangming', 'wp-ultimo'),
	__('Helong', 'wp-ultimo'),
	__('Hepingjie', 'wp-ultimo'),
	__('Huadian', 'wp-ultimo'),
	__('Huangnihe', 'wp-ultimo'),
	__('Huinan', 'wp-ultimo'),
	__('Hunchun', 'wp-ultimo'),
	__('Jilin', 'wp-ultimo'),
	__('Jishu', 'wp-ultimo'),
	__('Jiutai', 'wp-ultimo'),
	__('Ji’an', 'wp-ultimo'),
	__('Kaitong', 'wp-ultimo'),
	__('Liaoyuan', 'wp-ultimo'),
	__('Linjiang', 'wp-ultimo'),
	__('Lishu', 'wp-ultimo'),
	__('Liuhe', 'wp-ultimo'),
	__('Longjing', 'wp-ultimo'),
	__('Meihekou', 'wp-ultimo'),
	__('Mingyue', 'wp-ultimo'),
	__('Minzhu', 'wp-ultimo'),
	__('Panshi', 'wp-ultimo'),
	__('Sanchazi', 'wp-ultimo'),
	__('Shuangyang', 'wp-ultimo'),
	__('Shulan', 'wp-ultimo'),
	__('Siping', 'wp-ultimo'),
	__('Songjianghe', 'wp-ultimo'),
	__('Songyuan', 'wp-ultimo'),
	__('Tonghua', 'wp-ultimo'),
	__('Tonghua Shi', 'wp-ultimo'),
	__('Tumen', 'wp-ultimo'),
	__('Wangqing', 'wp-ultimo'),
	__('Xinglongshan', 'wp-ultimo'),
	__('Yanbian Chaoxianzu Zizhizhou', 'wp-ultimo'),
	__('Yanji', 'wp-ultimo'),
	__('Yantongshan', 'wp-ultimo'),
	__('Yushu', 'wp-ultimo'),
	__('Zhengjiatun', 'wp-ultimo'),
	__('Zhenlai', 'wp-ultimo'),
);
