<?php
/**
 * State City List for JX - CN.
 *
 * City count: 16
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for JX - CN.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Changleng', 'wp-ultimo'),
	__('Fenyi', 'wp-ultimo'),
	__('Ganzhou', 'wp-ultimo'),
	__('Ganzhou Shi', 'wp-ultimo'),
	__('Guixi', 'wp-ultimo'),
	__('Jianguang', 'wp-ultimo'),
	__('Jingdezhen', 'wp-ultimo'),
	__('Jingdezhen Shi', 'wp-ultimo'),
	__('Jiujiang', 'wp-ultimo'),
	__('Ji’an', 'wp-ultimo'),
	__('Nanchang', 'wp-ultimo'),
	__('Pingxiang', 'wp-ultimo'),
	__('Poyang', 'wp-ultimo'),
	__('Shangrao', 'wp-ultimo'),
	__('Xinyu', 'wp-ultimo'),
	__('Yichun', 'wp-ultimo'),
);
