<?php
/**
 * State City List for LN - CN.
 *
 * City count: 51
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for LN - CN.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Anshan', 'wp-ultimo'),
	__('Beipiao', 'wp-ultimo'),
	__('Benxi', 'wp-ultimo'),
	__('Changtu', 'wp-ultimo'),
	__('Chaoyang', 'wp-ultimo'),
	__('Dalian', 'wp-ultimo'),
	__('Dalianwan', 'wp-ultimo'),
	__('Dandong', 'wp-ultimo'),
	__('Dashiqiao', 'wp-ultimo'),
	__('Dongling', 'wp-ultimo'),
	__('Fengcheng', 'wp-ultimo'),
	__('Fushun', 'wp-ultimo'),
	__('Fuxin', 'wp-ultimo'),
	__('Gaizhou', 'wp-ultimo'),
	__('Gongchangling', 'wp-ultimo'),
	__('Haicheng', 'wp-ultimo'),
	__('Heishan', 'wp-ultimo'),
	__('Huanren', 'wp-ultimo'),
	__('Huludao', 'wp-ultimo'),
	__('Huludao Shi', 'wp-ultimo'),
	__('Hushitai', 'wp-ultimo'),
	__('Jinzhou', 'wp-ultimo'),
	__('Jiupu', 'wp-ultimo'),
	__('Kaiyuan', 'wp-ultimo'),
	__('Kuandian', 'wp-ultimo'),
	__('Langtoucun', 'wp-ultimo'),
	__('Lianshan', 'wp-ultimo'),
	__('Liaoyang', 'wp-ultimo'),
	__('Liaozhong', 'wp-ultimo'),
	__('Linghai', 'wp-ultimo'),
	__('Lingyuan', 'wp-ultimo'),
	__('Lüshun', 'wp-ultimo'),
	__('Nanpiao', 'wp-ultimo'),
	__('Nantai', 'wp-ultimo'),
	__('Panjin Shi', 'wp-ultimo'),
	__('Panshan', 'wp-ultimo'),
	__('Pulandian', 'wp-ultimo'),
	__('Shenyang', 'wp-ultimo'),
	__('Sujiatun', 'wp-ultimo'),
	__('Tieling', 'wp-ultimo'),
	__('Tieling Shi', 'wp-ultimo'),
	__('Wafangdian', 'wp-ultimo'),
	__('Xiaoshi', 'wp-ultimo'),
	__('Xifeng', 'wp-ultimo'),
	__('Xingcheng', 'wp-ultimo'),
	__('Xinmin', 'wp-ultimo'),
	__('Xinxing', 'wp-ultimo'),
	__('Xiuyan', 'wp-ultimo'),
	__('Yebaishou', 'wp-ultimo'),
	__('Yingkou', 'wp-ultimo'),
	__('Zhuanghe', 'wp-ultimo'),
);
