<?php
/**
 * State City List for NM - CN.
 *
 * City count: 33
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for NM - CN.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Baotou', 'wp-ultimo'),
	__('Bayan Nur', 'wp-ultimo'),
	__('Bayannur Shi', 'wp-ultimo'),
	__('Beichengqu', 'wp-ultimo'),
	__('Chifeng', 'wp-ultimo'),
	__('Dongsheng', 'wp-ultimo'),
	__('Erenhot', 'wp-ultimo'),
	__('E’erguna', 'wp-ultimo'),
	__('Genhe', 'wp-ultimo'),
	__('Hailar', 'wp-ultimo'),
	__('Hohhot', 'wp-ultimo'),
	__('Hulunbuir Region', 'wp-ultimo'),
	__('Jalai Nur', 'wp-ultimo'),
	__('Jiagedaqi', 'wp-ultimo'),
	__('Jining', 'wp-ultimo'),
	__('Manzhouli', 'wp-ultimo'),
	__('Mositai', 'wp-ultimo'),
	__('Mujiayingzi', 'wp-ultimo'),
	__('Ordos', 'wp-ultimo'),
	__('Ordos Shi', 'wp-ultimo'),
	__('Oroqen Zizhiqi', 'wp-ultimo'),
	__('Pingzhuang', 'wp-ultimo'),
	__('Salaqi', 'wp-ultimo'),
	__('Shiguai', 'wp-ultimo'),
	__('Tongliao', 'wp-ultimo'),
	__('Ulanhot', 'wp-ultimo'),
	__('Wenquan', 'wp-ultimo'),
	__('Wuda', 'wp-ultimo'),
	__('Wuhai', 'wp-ultimo'),
	__('Xilin Gol Meng', 'wp-ultimo'),
	__('Xilin Hot', 'wp-ultimo'),
	__('Yakeshi', 'wp-ultimo'),
	__('Zhalantun', 'wp-ultimo'),
);
