<?php
/**
 * State City List for NX - CN.
 *
 * City count: 7
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for NX - CN.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Dawukou', 'wp-ultimo'),
	__('Dongta', 'wp-ultimo'),
	__('Shitanjing', 'wp-ultimo'),
	__('Shizuishan', 'wp-ultimo'),
	__('Wuzhong', 'wp-ultimo'),
	__('Yinchuan', 'wp-ultimo'),
	__('Zhongwei', 'wp-ultimo'),
);
