<?php
/**
 * State City List for QH - CN.
 *
 * City count: 8
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for QH - CN.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Delingha', 'wp-ultimo'),
	__('Golmud', 'wp-ultimo'),
	__('Golog Tibetan Autonomous Prefecture', 'wp-ultimo'),
	__('Haibei Tibetan Autonomous Prefecture', 'wp-ultimo'),
	__('Huangnan Zangzu Zizhizhou', 'wp-ultimo'),
	__('Xining', 'wp-ultimo'),
	__('Xireg', 'wp-ultimo'),
	__('Yushu Zangzu Zizhizhou', 'wp-ultimo'),
);
