<?php
/**
 * State City List for SC - CN.
 *
 * City count: 49
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for SC - CN.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Aba Zangzu Qiangzu Zizhizhou', 'wp-ultimo'),
	__('Barkam', 'wp-ultimo'),
	__('Bazhong Shi', 'wp-ultimo'),
	__('Changchi', 'wp-ultimo'),
	__('Chengdu', 'wp-ultimo'),
	__('Chonglong', 'wp-ultimo'),
	__('Dadukou', 'wp-ultimo'),
	__('Dazhou', 'wp-ultimo'),
	__('Deyang', 'wp-ultimo'),
	__('Dongxi', 'wp-ultimo'),
	__('Fangting', 'wp-ultimo'),
	__('Fubao', 'wp-ultimo'),
	__('Gaoping', 'wp-ultimo'),
	__('Garzê Zangzu Zizhizhou', 'wp-ultimo'),
	__('Guangyuan', 'wp-ultimo'),
	__('Guang’an', 'wp-ultimo'),
	__('Jiancheng', 'wp-ultimo'),
	__('Jiangyou', 'wp-ultimo'),
	__('Jiannan', 'wp-ultimo'),
	__('Kangding', 'wp-ultimo'),
	__('Langzhong', 'wp-ultimo'),
	__('Leshan', 'wp-ultimo'),
	__('Liangshan Yizu Zizhizhou', 'wp-ultimo'),
	__('Linqiong', 'wp-ultimo'),
	__('Luocheng', 'wp-ultimo'),
	__('Luzhou', 'wp-ultimo'),
	__('Meishan Shi', 'wp-ultimo'),
	__('Mianyang', 'wp-ultimo'),
	__('Nanchong', 'wp-ultimo'),
	__('Nanlong', 'wp-ultimo'),
	__('Neijiang', 'wp-ultimo'),
	__('Panzhihua', 'wp-ultimo'),
	__('Puji', 'wp-ultimo'),
	__('Shuanghejiedao', 'wp-ultimo'),
	__('Suining', 'wp-ultimo'),
	__('Taihe', 'wp-ultimo'),
	__('Taiping', 'wp-ultimo'),
	__('Tianpeng', 'wp-ultimo'),
	__('Tongchuan', 'wp-ultimo'),
	__('Xialiang', 'wp-ultimo'),
	__('Xiantan', 'wp-ultimo'),
	__('Xichang', 'wp-ultimo'),
	__('Xunchang', 'wp-ultimo'),
	__('Yanjiang', 'wp-ultimo'),
	__('Yibin', 'wp-ultimo'),
	__('Yucheng', 'wp-ultimo'),
	__('Zengjia', 'wp-ultimo'),
	__('Zhongba', 'wp-ultimo'),
	__('Zigong', 'wp-ultimo'),
);
