<?php
/**
 * State City List for SD - CN.
 *
 * City count: 90
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for SD - CN.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Anqiu', 'wp-ultimo'),
	__('Beizhai', 'wp-ultimo'),
	__('Bianzhuang', 'wp-ultimo'),
	__('Binzhou', 'wp-ultimo'),
	__('Boshan', 'wp-ultimo'),
	__('Changqing', 'wp-ultimo'),
	__('Chengqu', 'wp-ultimo'),
	__('Chengtangcun', 'wp-ultimo'),
	__('Chengyang', 'wp-ultimo'),
	__('Dengying', 'wp-ultimo'),
	__('Dengzhou', 'wp-ultimo'),
	__('Dezhou', 'wp-ultimo'),
	__('Dingtao', 'wp-ultimo'),
	__('Dongcun', 'wp-ultimo'),
	__('Dongdu', 'wp-ultimo'),
	__('Feicheng', 'wp-ultimo'),
	__('Gaomi', 'wp-ultimo'),
	__('Hanting', 'wp-ultimo'),
	__('Heze', 'wp-ultimo'),
	__('Jiamaying', 'wp-ultimo'),
	__('Jiaozhou', 'wp-ultimo'),
	__('Jiehu', 'wp-ultimo'),
	__('Jimo', 'wp-ultimo'),
	__('Jinan', 'wp-ultimo'),
	__('Jining', 'wp-ultimo'),
	__('Juye', 'wp-ultimo'),
	__('Kuiju', 'wp-ultimo'),
	__('Kutao', 'wp-ultimo'),
	__('Laiwu', 'wp-ultimo'),
	__('Laixi', 'wp-ultimo'),
	__('Laiyang', 'wp-ultimo'),
	__('Laizhou', 'wp-ultimo'),
	__('Laocheng', 'wp-ultimo'),
	__('Liaocheng', 'wp-ultimo'),
	__('Linqu', 'wp-ultimo'),
	__('Linyi', 'wp-ultimo'),
	__('Longgang', 'wp-ultimo'),
	__('Mengyin', 'wp-ultimo'),
	__('Mingshui', 'wp-ultimo'),
	__('Mizhou', 'wp-ultimo'),
	__('Nanding', 'wp-ultimo'),
	__('Nanma', 'wp-ultimo'),
	__('Ninghai', 'wp-ultimo'),
	__('Ningyang', 'wp-ultimo'),
	__('Pingdu', 'wp-ultimo'),
	__('Pingyi', 'wp-ultimo'),
	__('Pingyin', 'wp-ultimo'),
	__('Qingdao', 'wp-ultimo'),
	__('Qingnian', 'wp-ultimo'),
	__('Qingshancun', 'wp-ultimo'),
	__('Qingyang', 'wp-ultimo'),
	__('Qingzhou', 'wp-ultimo'),
	__('Qufu', 'wp-ultimo'),
	__('Rizhao', 'wp-ultimo'),
	__('Shancheng', 'wp-ultimo'),
	__('Shanting', 'wp-ultimo'),
	__('Shazikou', 'wp-ultimo'),
	__('Shengli', 'wp-ultimo'),
	__('Shilaorencun', 'wp-ultimo'),
	__('Shizilu', 'wp-ultimo'),
	__('Shouguang', 'wp-ultimo'),
	__('Sishui', 'wp-ultimo'),
	__('Suozhen', 'wp-ultimo'),
	__('Tai’an', 'wp-ultimo'),
	__('Taozhuang', 'wp-ultimo'),
	__('Tianfu', 'wp-ultimo'),
	__('Weifang', 'wp-ultimo'),
	__('Weihai', 'wp-ultimo'),
	__('Wenshang', 'wp-ultimo'),
	__('Xiazhen', 'wp-ultimo'),
	__('Xiazhuang', 'wp-ultimo'),
	__('Xiliguantun', 'wp-ultimo'),
	__('Xindian', 'wp-ultimo'),
	__('Xintai', 'wp-ultimo'),
	__('Yanggu', 'wp-ultimo'),
	__('Yanta', 'wp-ultimo'),
	__('Yantai', 'wp-ultimo'),
	__('Yanzhou', 'wp-ultimo'),
	__('Yatou', 'wp-ultimo'),
	__('Yinzhu', 'wp-ultimo'),
	__('Yishui', 'wp-ultimo'),
	__('Yucheng', 'wp-ultimo'),
	__('Zaozhuang', 'wp-ultimo'),
	__('Zhaoyuan', 'wp-ultimo'),
	__('Zhoucheng', 'wp-ultimo'),
	__('Zhoucun', 'wp-ultimo'),
	__('Zhu Cheng City', 'wp-ultimo'),
	__('Zhuangyuan', 'wp-ultimo'),
	__('Zibo', 'wp-ultimo'),
	__('Zoucheng', 'wp-ultimo'),
);
