<?php
/**
 * State City List for SH - CN.
 *
 * City count: 4
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for SH - CN.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Shanghai', 'wp-ultimo'),
	__('Songjiang', 'wp-ultimo'),
	__('Zhabei', 'wp-ultimo'),
	__('Zhujiajiao', 'wp-ultimo'),
);
