<?php
/**
 * State City List for SN - CN.
 *
 * City count: 14
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for SN - CN.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Ankang', 'wp-ultimo'),
	__('Baoji Shi', 'wp-ultimo'),
	__('Guozhen', 'wp-ultimo'),
	__('Hancheng', 'wp-ultimo'),
	__('Hanzhong', 'wp-ultimo'),
	__('Huayin', 'wp-ultimo'),
	__('Lintong', 'wp-ultimo'),
	__('Tongchuanshi', 'wp-ultimo'),
	__('Weinan', 'wp-ultimo'),
	__('Xianyang', 'wp-ultimo'),
	__('Xi’an', 'wp-ultimo'),
	__('Yanliang', 'wp-ultimo'),
	__('Yulinshi', 'wp-ultimo'),
	__('Yuxia', 'wp-ultimo'),
);
