<?php
/**
 * State City List for SX - CN.
 *
 * City count: 18
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for SX - CN.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Changzhi', 'wp-ultimo'),
	__('Datong', 'wp-ultimo'),
	__('Datong Shi', 'wp-ultimo'),
	__('Gutao', 'wp-ultimo'),
	__('Jiexiu', 'wp-ultimo'),
	__('Jincheng', 'wp-ultimo'),
	__('Jinzhong Shi', 'wp-ultimo'),
	__('Linfen', 'wp-ultimo'),
	__('Lüliang', 'wp-ultimo'),
	__('Shuozhou', 'wp-ultimo'),
	__('Taiyuan', 'wp-ultimo'),
	__('Xintian', 'wp-ultimo'),
	__('Xinzhi', 'wp-ultimo'),
	__('Xinzhou', 'wp-ultimo'),
	__('Yangquan', 'wp-ultimo'),
	__('Yuanping', 'wp-ultimo'),
	__('Yuci', 'wp-ultimo'),
	__('Yuncheng', 'wp-ultimo'),
);
