<?php
/**
 * State City List for XJ - CN.
 *
 * City count: 37
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for XJ - CN.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Ailan Mubage', 'wp-ultimo'),
	__('Aksu', 'wp-ultimo'),
	__('Aksu Diqu', 'wp-ultimo'),
	__('Altay', 'wp-ultimo'),
	__('Altay Diqu', 'wp-ultimo'),
	__('Aral', 'wp-ultimo'),
	__('Aykol', 'wp-ultimo'),
	__('Baijiantan', 'wp-ultimo'),
	__('Baluntaicun', 'wp-ultimo'),
	__('Bayingolin Mongol Zizhizhou', 'wp-ultimo'),
	__('Changji', 'wp-ultimo'),
	__('Changji Huizu Zizhizhou', 'wp-ultimo'),
	__('Fukang', 'wp-ultimo'),
	__('Hami', 'wp-ultimo'),
	__('Hotan', 'wp-ultimo'),
	__('Hoxtolgay', 'wp-ultimo'),
	__('Huocheng', 'wp-ultimo'),
	__('Ili Kazak Zizhizhou', 'wp-ultimo'),
	__('Karamay', 'wp-ultimo'),
	__('Karamay Shi', 'wp-ultimo'),
	__('Kashgar', 'wp-ultimo'),
	__('Kaxgar Diqu', 'wp-ultimo'),
	__('Korla', 'wp-ultimo'),
	__('Kuqa', 'wp-ultimo'),
	__('Kuytun', 'wp-ultimo'),
	__('Qapqal', 'wp-ultimo'),
	__('Shache', 'wp-ultimo'),
	__('Shihezi', 'wp-ultimo'),
	__('Sishilichengzi', 'wp-ultimo'),
	__('Tacheng', 'wp-ultimo'),
	__('Tacheng Diqu', 'wp-ultimo'),
	__('Turpan', 'wp-ultimo'),
	__('Turpan Diqu', 'wp-ultimo'),
	__('Urumqi Shi', 'wp-ultimo'),
	__('Xinyuan', 'wp-ultimo'),
	__('Zangguy', 'wp-ultimo'),
	__('Ürümqi', 'wp-ultimo'),
);
