<?php
/**
 * State City List for XZ - CN.
 *
 * City count: 13
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for XZ - CN.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Burang', 'wp-ultimo'),
	__('Dêqên', 'wp-ultimo'),
	__('Jiangzi', 'wp-ultimo'),
	__('Lhasa', 'wp-ultimo'),
	__('Nagqu', 'wp-ultimo'),
	__('Nagqu Diqu', 'wp-ultimo'),
	__('Ngari Diqu', 'wp-ultimo'),
	__('Nyingchi Prefecture', 'wp-ultimo'),
	__('Qamdo', 'wp-ultimo'),
	__('Qamdo Shi', 'wp-ultimo'),
	__('Rikaze', 'wp-ultimo'),
	__('Saga', 'wp-ultimo'),
	__('Shannan Diqu', 'wp-ultimo'),
);
