<?php
/**
 * State City List for YN - CN.
 *
 * City count: 29
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for YN - CN.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-05
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.10
 */
return array(
	__('Chuxiong Yizu Zizhizhou', 'wp-ultimo'),
	__('Dali', 'wp-ultimo'),
	__('Dali Baizu Zizhizhou', 'wp-ultimo'),
	__('Dehong Daizu Jingpozu Zizhizhou', 'wp-ultimo'),
	__('Dêqên Tibetan Autonomous Prefecture', 'wp-ultimo'),
	__('Gejiu', 'wp-ultimo'),
	__('Haikou', 'wp-ultimo'),
	__('Honghe Hanizu Yizu Zizhizhou', 'wp-ultimo'),
	__('Jinghong', 'wp-ultimo'),
	__('Kaihua', 'wp-ultimo'),
	__('Kaiyuan', 'wp-ultimo'),
	__('Kunming', 'wp-ultimo'),
	__('Lianran', 'wp-ultimo'),
	__('Lijiang', 'wp-ultimo'),
	__('Lincang Shi', 'wp-ultimo'),
	__('Longquan', 'wp-ultimo'),
	__('Mabai', 'wp-ultimo'),
	__('Majie', 'wp-ultimo'),
	__('Miyang', 'wp-ultimo'),
	__('Nujiang Lisuzu Zizhizhou', 'wp-ultimo'),
	__('Qujing', 'wp-ultimo'),
	__('Shangri-La', 'wp-ultimo'),
	__('Shilin', 'wp-ultimo'),
	__('Wenlan', 'wp-ultimo'),
	__('Wenshan City', 'wp-ultimo'),
	__('Wenshan Zhuangzu Miaozu Zizhizhou', 'wp-ultimo'),
	__('Yuxi', 'wp-ultimo'),
	__('Zhaotong', 'wp-ultimo'),
	__('Zhongshu', 'wp-ultimo'),
);
